### PR TITLE
Fixes #1127. Removed haxby_simple

### LINKED ISSUE #1127: Get rid of fetch_haxby_simple
It's confusing to have 2 haxby fetchers. In addition, it puts strains on generating the documentation (more downloads, less shared path to cache) and it clogs the download folders of people.

I vote to remove fetch_haxby_simple. The examples should all be changed accordingly.

### PR DESCRIPTION
**Pull request by sahmed95**
Removed redundant fetcher.

### CODE REVIEW

**Comment by AlexandreAbraham** [comment]
Thanks for the PR. 3 remarks though (with points to discuss):
* examples relying on haxby_simple must be updated
* we should probably discuss if we remove it bluntly or if we "deprecate it" (and make it rely on fetch_haxby)
* the test of haxby_simple is the only one to actually "download" a file (it is a dummy file from the repo itself) and therefor to test the full dataset fetching process. We have to replace it by another one (can be done in a separate PR).

**Comment by sahmed95** [comment]
(1) is resolved by using haxby rather than haxby_simple in the relevant examples. For (3), I can look at the test. (2) Perhaps needs discussion with other developers as I am a new-bie to nilearn. :smile:

**Comment by bthirion** [comment]
It's better practice to deprecate `fetch_haxby_simple`, and indeed remove it from the examples.

**Comment by bthirion** [comment]
OK, superseded by #1158.

**Comment by sahmed95** [comment]
Does this mean we can close this in favour of 1158 ?

**Comment by GaelVaroquaux** [comment]
Yes it does, thanks @sahmed95 !

**Pull request closed without merging**
