### PR TITLE
Deal with non-full rank confounds

### LINKED ISSUE #561: confounds removal
I am unsure about what the signal.clean is supposed to output. Isn't the cleaned signal the residual from the  least squares regression ?
I have been comparing the residuals obtained using scipy.linalg.lstsq and the output of signal.clean. With confounds with full rank, the results match. On the other hand, I have a systhematic mismatch between  the two outputs when the confounds do not have full rank (adding for instance a constant array to confounds or using the same confound twice).

### PR DESCRIPTION
**Pull request by salma1601**
Fixes #561
It remains to add a test to check that output from regessing out confounds equals residue obtained with scipy least squares. May be it will be better to add it after PR #553 is merged, because this PR will affect the way the regression is done.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
@salma1601 : thanks a lot.

The tests are not passing on scipy 0.9.0, which we must support as it is the standard version in one of the ubuntu distributions that we support.

The reason is trivial: the 'pivoting' argument to scipy.linalg.qr was added in version 0.10.1.

The solution is to test for the version of scipy, and use the 'pivoting' only if the version is greater. One example of such code to do this can be found on 
https://github.com/nilearn/nilearn/blob/master/nilearn/decomposition/canica.py#L153

Thanks!

**Comment by eickenberg** [comment]
I may be completely mistaken, but the problem may not have crept up if `signal -= confounds.dot(np.linalg.lstsq(confounds, signal)[0])` or `signal -= confounds.dot(np.linalg.pinv(confounds).dot(signal))` had been used instead of the lower-level QR decomp technique.

**Comment by GaelVaroquaux** [comment]
Yes, but the QR is significantly faster. The Leipzig people were impressed at how fast this was.

**Comment by eickenberg** [comment]
Why is it faster? Computing the decomposition vs computing the pinv can
hardly be the problem. The re-multiplications afterwards are of exactly the
same shape.

**Comment by GaelVaroquaux** [comment]
OK, maybe not faster. I just know that it is the recommended way of doing it.

**Comment by GaelVaroquaux** [comment]
Closing this PR as superseeded by #580

**Pull request closed without merging**
