### PR TITLE
Prettier picture on front page

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
One last thing before release: let's have a prettier image in the carrousel.

### CODE REVIEW

**Comment by KamalakerDadi** [comment]
We need CircleCI may be to check this.

**Comment by GaelVaroquaux** [comment]
I agree. Let's wait, it's almost there

**Comment by GaelVaroquaux** [comment]
Seems to look good: https://2959-1235740-gh.circle-artifacts.com/0/home/ubuntu/nilearn/doc/_build/html/index.html

**Comment by KamalakerDadi** [comment]
LGTM

**Comment by KamalakerDadi** [comment]
Merging. Thanks

**Pull request merged**
