### PR TITLE
[INFRA] add a GH workflow to regularly update pre-commit hooks

### LINKED ISSUE #3490: [INFRA] add a GH workflow to regularly update pre-commit hooks
Done.

Once this is merged I will open a separate PR with a workflow to check and update the hooks version weekly so we don't have to remember to regularly update this.

_Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/pull/3484#discussion_r1098683579_

### PR DESCRIPTION
**Pull request by Remi-Gau**
Closes #3490

Changes proposed in this pull request:

- add a github workflow to automatically to check for update of all the pre-commit hooks every monday
- if some hooks require to be updated then the pre-commit config is updated and a PR is opened against the main branch
- only the upstream repo should be affected to avoid extra noise on the 500 forks of nilearn
- this workflow is not trigger by pushes or PR but can be triggered manually by maintainers from the action tab.

I forced a this to trigger a PR on my fork to give an example:

https://github.com/Remi-Gau/nilearn/pull/7

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Unsure if this requires a changelog entry.

**Comment by bthirion** [comment]
Need to rebase after the merge of #3506 to clean tests, but LGTM.

**Comment by Remi-Gau** [comment]
FYI: the diff is very small because the rest of the file was already added in main by my PR mistake in https://github.com/nilearn/nilearn/pull/3515

hence the whole file for this workflow is here: https://github.com/nilearn/nilearn/blob/06d47222d537cbc6e32edd3e361104c3cdb1bdb0/.github/workflows/update_precommit_hooks.yml

**Review by ymzayek — APPROVED** [review]
LGTM @Remi-Gau

**Comment by ymzayek** [comment]
Why close this?

**Comment by ymzayek** [comment]
BTW I think it can be merged already

**Comment by Remi-Gau** [comment]
> Why close this?

I misfired a `git push -d`

**Comment by ymzayek** [comment]
@Remi-Gau thx!

**Pull request merged**
