### PR TITLE
[DOC] adapt example to show how to use load confounds with bids dataset

### LINKED ISSUE #4178: [ENH] update example ti show how to use load_confounds with first_level_from_bids
- Follow up fo https://github.com/nilearn/nilearn/pull/4103
- probably best done in: https://nilearn.github.io/stable/auto_examples/04_glm_first_level/plot_bids_features.html#sphx-glr-auto-examples-04-glm-first-level-plot-bids-features-py

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes #4178 

Changes proposed in this pull request:

- use load confounds in bids example

### CODE REVIEW

**Comment by Remi-Gau** [comment]
It seems that it will not be possible to use this dataset to demonstrate this.

The fmriprep data is too old for what load_confounds supports.

```
/home/remi/miniconda3/bin/python /home/remi/github/nilearn/nilearn/examples/04_glm_first_level/plot_bids_features.py
Traceback (most recent call last):
  File "/home/remi/github/nilearn/nilearn/examples/04_glm_first_level/plot_bids_features.py", line 99, in <module>
    ) = first_level_from_bids(
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/glm/first_level/first_level.py", line 1440, in first_level_from_bids
    confounds = _get_confounds(
                ^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/glm/first_level/first_level.py", line 1724, in _get_confounds
    confounds, _ = load_confounds(img_files=imgs, **kwargs_load_confounds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/interfaces/fmriprep/load_confounds.py", line 302, in load_confounds
    sample_mask, conf = _load_confounds_for_single_image_file(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/interfaces/fmriprep/load_confounds.py", line 367, in _load_confounds_for_single_image_file
    return _load_single_confounds_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/interfaces/fmriprep/load_confounds.py", line 414, in _load_single_confounds_file
    confounds_all = load_confounds_file_as_dataframe(confounds_file)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/interfaces/fmriprep/load_confounds_utils.py", line 336, in load_confounds_file_as_dataframe
    raise ValueError(
ValueError: The confound file contains header in camel case. This is likely the output from 1.0.x and 1.1.x series. We only support fmriprep outputs >= 1.2.0.Index(['WhiteMatter', 'GlobalSignal', 'stdDVARS', 'non-stdDVARS',
       'vx-wisestdDVARS', 'FramewiseDisplacement', 'tCompCor00', 'tCompCor01',
       'tCompCor02', 'tCompCor03', 'tCompCor04', 'tCompCor05', 'aCompCor00',
       'aCompCor01', 'aCompCor02', 'aCompCor03', 'aCompCor04', 'aCompCor05',
       'X', 'Y', 'Z', 'RotX', 'RotY', 'RotZ'],
      dtype='object')
```

**Comment by Remi-Gau** [comment]
If we want to showcase this, it may require adding a new BIDS dataset to the list of Nilearn fetchers.

**IF** we think it is worth it we may want to take a bit of time to pick a dataset that could be used for many different things, probably worth discussing at the next dev metting (if we have time?) and probably worth removing this from the 0.11 release as this is not "urgent".

**Comment by bthirion** [comment]
Not urgent IMHO.

**Comment by Remi-Gau** [comment]
closing as this will anyway require a new dataset

**Pull request closed without merging**
