### PR TITLE
Fix threshold application during plotting for affine with rotation

### LINKED ISSUE #599: Plotting thresholds are ignored for images whose affine contains a rotation
I've run into an issue trying to use nilearn to visualize data in native space. This came up when trying to plot ROIs:

```python
plot_roi(roi_img, epi_img)
```
4jxsfhcftoutz on44aeto5 amrliyfontmfmzgztu1pwycbeokebeeliotdtslqgp4eqqgghlwwnbkiiiyquguejqgghhbscngzcccgefijgaygeeeikqaobeeiiiywg0uaiiysqqtboiiqqqkghadqqqgghpba0ggghhbbscbonhbbccckejqzcccgefijgaygeeeikqaobeeiiiywg0uaiiysqqtboiiqqqkghadqqqgghpba0gggh

(where `roi_img` and `epi_img` are `nibabel.Nifti1Image` objects).

This issue does not appear to occur with the example [haxby data](https://nilearn.github.io/auto_examples/manipulating_visualizing/plot_roi_extraction.html).

Something similar is happening with a continuous statistical map:

```python
plot_stat_map(z_img, epi_img, threshold=9)
```
nu3t7u8rkyrl bt89cviofaqfqvnxy6pvq4ybgqgjvlw84vps0lkjuljykgtk5 cbxv1dxvbt27p6lkycbgaas6kxsvglfy82d udhx9xexm5li9fruvxrysnj0c5otlyuvzq7ozm6ruwdxaaalac5gabaadliqabaadliqabaadliqabaadliqabaadliqabaadliqabaadliqabaadliqabaadliqabaadliqabaadliqabaadliqaba

I've tracked down the issue to [this line of code](https://github.com/nilearn/nilearn/blob/0.1.3/nilearn/plotting/displays.py#L532). The `img` object that goes into the `reorder_img` function has a masked data array, but the `img` that comes out of it just has a bare float array of 1s and 0s (in the case of the ROI image).

My native space images have a LPS orientation; presumably the mask  information is getting lost somewhere as the data are reordered to RAS. Presumably that step is skipped for the Haxby data, which are already oriented properly, and that is why the examples look fine.

I'm using nilearn 1.3.

### PR DESCRIPTION
**Pull request by lesteve**
* threshold application is done after image reordering/resampling
* add regression test

Fix #599.

### CODE REVIEW

**Comment by AlexandreAbraham** [comment]
:+1:

**Comment by bthirion** [comment]
Sounds good.

**Comment by lesteve** [comment]
Merging this one then.

**Comment by GaelVaroquaux** [comment]
Good job!

**Pull request merged**
