### PR TITLE
[WIP] Investigate CircleCI error

### PR DESCRIPTION
**Pull request by NicolasGensollen**

### CODE REVIEW

**Comment by jeromedockes** [comment]
not sure if it would be useful but you should be able to rerun a circleci workflow on a node you can ssh into

**Comment by NicolasGensollen** [comment]
>not sure if it would be useful but you should be able to rerun a circleci workflow on a node you can ssh into

Thanks @jeromedockes. It could, but it's not failing consistently and it takes some time (usually between 40min and 1h). AFAICT, it looks like a memory error, so I'm not sure SSHing into the node after it fails will be useful. 
For now, I'm trying to understand exactly which line is causing this...

**Comment by larsoner** [comment]
> memory error, so I'm not sure SSHing into the node after it fails will be useful.

In MNE-Python we restrict our examples to use less than 1 GB generally. CircleCI has a 4 GB limit and if examples use more than this (and you have a lot of examples) it'll get killed.

We use various memory-outputting config stuff to make it possible to debug these failures, maybe it will help you. See for example:

- Making sure memory is profiled by sphinx-gallery: https://github.com/mne-tools/mne-python/blob/a50535b709d02acad0d48b9ac4bc701dc5659022/doc/conf.py#L410
- Looking at memory usage this produces: https://mne.tools/dev/auto_tutorials/inverse/sg_execution_times.html (note you have these, too, but they appear not to be configured to `show_memory`: https://nilearn.github.io/stable/auto_examples/sg_execution_times.html
- Using sphinx-gallery resetter functionality to print memory usage on the fly ourselves, too: https://github.com/mne-tools/mne-python/blob/a50535b709d02acad0d48b9ac4bc701dc5659022/doc/conf.py#L326-L332
- Having a Makefile option to test this locally (e.g., make html_dev-memory): https://github.com/mne-tools/mne-python/blob/a50535b709d02acad0d48b9ac4bc701dc5659022/doc/Makefile#L44-L45
- Actually using this option on CircleCI: https://github.com/mne-tools/mne-python/blob/a50535b709d02acad0d48b9ac4bc701dc5659022/tools/circleci_download.sh#L3-L5

**Comment by larsoner** [comment]
... also apparently CircleCI now has a timeout that is shorter -- our MNE builds take 2-3h and apparently now they've implemented a new limit that is much lower than that: https://app.circleci.com/pipelines/github/mne-tools/mne-python/11466/workflows/2cdc35c4-e9cf-4fe6-872a-87a499804609/jobs/38423

**Comment by NicolasGensollen** [comment]
Thanks @larsoner ! I'll take a look at the links you provided.
I don't know what the issue is for the moment. For some builds, [like this one](https://app.circleci.com/pipelines/github/nilearn/nilearn/3467/workflows/8aacc5fb-6c70-438c-81b5-e8353a5465cc/jobs/8716), I get a `Bus error (core dumped)` error, some other builds like [this one](https://app.circleci.com/pipelines/github/nilearn/nilearn/3476/workflows/3a0f8581-7cb8-41b5-82c7-402cd1daf948/jobs/8719) get stuck and finally timed out, and some are fine.

**Comment by larsoner** [comment]
Locally I see:
```
$ make html SPHINXOPTS="-D sphinx_gallery_conf.filename_pattern=plot_data_driven -D sphinx_gallery_conf.show_memory=True"
...
    - ../examples/03_connectivity/plot_data_driven_parcellations.py:              53.50 sec   1766.6 MB
...
```
I would try getting this to be < 1 GB to see if all of the problems magically go away

**Comment by NicolasGensollen** [comment]
Closing this PR as #3062 seems to have fixed the issue for now.

**Pull request closed without merging**
