### PR TITLE
Release 0.10.0

### PR DESCRIPTION
**Pull request by ymzayek**

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Review by NicolasGensollen — APPROVED** [review]
Thanks @ymzayek ! This LGTM ! 👍 
Wondering whether we should try to merge #3453 for the release, and rebase to avoid tagging a commit with test failures.
Might also be worth triggering a full documentation build before merging.

**Comment by ymzayek** [comment]
@NicolasGensollen yes those are good points thanks!

**Comment by jeromedockes** [comment]
re the pep8 checks that gives spurious failures since the last flake8 release, until we have a solution should we temporarily [disable the workflow](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow#disabling-a-workflow) ?

**Comment by ymzayek** [comment]
@jeromedockes yes I'll get on that tomorrow. Thanks for the reminder!

**Comment by jeromedockes** [comment]
> yes I'll get on that tomorrow

ok I just disabled it then. to re-enable it we just have to go to github actions, select that workflow and click "enable workflow"

**Comment by ymzayek** [comment]
> ok I just disabled it then. to re-enable it we just have to go to github actions, select that workflow and click "enable workflow"

Great thanks!

**Comment by bthirion** [comment]
Thx !

**Pull request merged**
