### PR TITLE
[DOC] split atlases section by probabilistic and deterministic

### LINKED ISSUE #4277: Atlas fetching API summary section of the doc does not always mention which ones are probabilistic and deterministic
Currently only some of them mention it.

May even be better to split this in 2 sections.

https://nilearn.github.io/stable/modules/datasets.html#atlases

Screenshot from 2024-02-21 11-34-48

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes #4277

Changes proposed in this pull request:

- split atlases by deterministic and probabilistic
- some are mentioned twice as they can do both

### CODE REVIEW

**Review by man-shu — APPROVED** [review]
LGTM!

**Review by bthirion — APPROVED** [review]
LGTM. Just need to check generated doc

**Comment by Remi-Gau** [comment]
the doc hosting seems to be because of 500 errors from where we usually get the build artefacts from: https://nightly.link/nilearn/nilearn/actions/runs/11971187558

**Comment by Remi-Gau** [comment]
View of the doc

https://output.circle-artifacts.com/output/job/5380f744-3a7d-4922-a9b7-254b8472b507/artifacts/0/dev/modules/datasets.html#atlases

**Pull request merged**
