### PR TITLE
[MAINT] add reminder in bug report template

### PR DESCRIPTION
**Pull request by htwangtw**
Just thought this is an important detail that should be here in addition to the contribution guide.

Changes proposed in this pull request:

- Prompt people to submit a minimal runnable example with nilearn data.

### CODE REVIEW

**Review by ymzayek — APPROVED** [review]
LGTM thx @htwangtw !

**Review by bthirion — APPROVED** [review]
Indeed !

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks @htwangtw !

**Comment by ymzayek** [comment]
Merging

**Pull request merged**
