### PR TITLE
[FIX] Fix missing title in `plot_surf`

### LINKED ISSUE #2941: Titles get ignored in plot_surf_*
Titles are not displayed

Nilearn version:0.8.1

### Expected behavior
Title show off when provided

### Actual behavior
Title not diplsayed

### Steps and code to reproduce bug
for instance:
https://nilearn.github.io/auto_examples/01_plotting/plot_3d_map_to_surface_projection.html#sphx-glr-auto-examples-01-plotting-plot-3d-map-to-surface-projection-py

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Fixes #2941

### CODE REVIEW

**Comment by NicolasGensollen** [comment]
Thanks @bthirion !

I proposed a fix for the title with legends. Here is the [link to the latest artifacts](https://7983-1235740-gh.circle-artifacts.com/0/dev/auto_examples/01_plotting/plot_3d_map_to_surface_projection.html#sphx-glr-auto-examples-01-plotting-plot-3d-map-to-surface-projection-py) which seem to look fine.

>What about view_surf* ?

Title seems to be working fine for these. Did you spot a bug ?

**Review by bthirion — APPROVED** [review]
LGTM. Can you check if codecov complains rightfully ?

**Comment by NicolasGensollen** [comment]
>Can you check if codecov complains rightfully ?

It was indeed... It should be good now!

**Review by bthirion — APPROVED** [review]
Thx !

**Comment by NicolasGensollen** [comment]
Thanks! Merging...

**Pull request merged**
