### PR TITLE
Pre-release 0.10.1rc1

### PR DESCRIPTION
**Pull request by ymzayek**

### CODE REVIEW

**Comment by bthirion** [comment]
When do you do the pre-release ?

**Comment by ymzayek** [comment]
I can do it today or tomorrow. We should hold off on merging anything else at this point until I do the release and a post-release PR. Once the tests pass I'd say it's ready.

**Review by Remi-Gau — APPROVED** [review]
Good with me but let me know if I should make a mention of the changes in terms of formatting.

I am starting to feel that it may be better to keep track regularly of those changes rather than having a single entry "in the end" because the end may take a while to get there and some changes involve more than just "reformatting" so it may help to have some bread crumbs for those in the changelog.

**Comment by ymzayek** [comment]
@Remi-Gau we could go ahead and add it in this PR. Maybe an entry (or more if needed) under changes? I think it's worth mentioning the reformatting since this could concern contributors in general, however I think I would still leave CI stuff out. I was actually thinking to open an issue/PR to add to this [README file](https://github.com/nilearn/nilearn/blob/main/.github/workflows/README.md) to document everything that's happening with the CI (specifically GitHub Actions).

**Review by bthirion — APPROVED** [review]
LGTM

**Comment by ymzayek** [comment]
@Remi-Gau would it suffice to add this?

```rst
- Modules :mod:`~nilearn.decomposition` and :mod:`~nilearn.decoding` code and docstrings have been reformatted using black. Changes resulted in improved readability overall and increased consistency (:gh:`3491` and :gh:`3484` by `Remi Gau`_).
```

**Comment by Remi-Gau** [comment]
> @Remi-Gau would it suffice to add this?
> 
> ```rst
> - Modules :mod:`~nilearn.decomposition` and :mod:`~nilearn.decoding` code and docstrings have been reformatted using black. Changes resulted in improved readability overall and increased consistency (:gh:`3491` and :gh:`3484` by `Remi Gau`_).
> ```

Yes that's good with me. Thanks.

**Comment by ymzayek** [comment]
Merging this. Then will tag it, build, and upload the distributions to pypi and github

**Pull request merged**
