### PR TITLE
[DOC] Run the events.tsv generation example

### PR DESCRIPTION
**Pull request by tsalo**
Closes None. I realized that the example that uses `plot_event` (9.5.2) is not actually run, so there's no real "example" of the generated figure.

Changes proposed in this pull request:

- Update `examples/04_glm_first_level/write_events_file.py` to run in the sphinx gallery.
- Include the full citation for the ARCHI Standard task.
- Make some minor changes to formatting and text within the example.

### CODE REVIEW

**Comment by tsalo** [comment]
Here's the link to the rendered example, in case anyone wants to look at it: https://9028-1235740-gh.circle-artifacts.com/0/dev/auto_examples/04_glm_first_level/plot_write_events_file.html#sphx-glr-auto-examples-04-glm-first-level-plot-write-events-file-py

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Review by NicolasGensollen — COMMENTED** [review]
Thanks @tsalo !
Just a couple formatting suggestions but LGTM otherwise!

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks @tsalo !

**Comment by NicolasGensollen** [comment]
Merging...

**Pull request merged**
