### PR TITLE
[ENH] Set appropriate cut coordinates for NiftiLabelsMasker reports

### LINKED ISSUE #3110: masker.generate_report doesn't center on ROI if overlaid on functional data
When using masker.generate_report(), if no functional data is given ROIs are plotted on the MNI template, and the cursor centers on one of the ROIs. However, if the masker is first fit to functional data, ROIs are plotted on the functional data, but the cursor does not center on any of the ROIs. If the atlas happens to fall outside of where the cursor is, you cant see any of the ROIs and can't tell if the alignment is good or not.

Nilearn version: 0.8.0

### Expected behavior
Figure generated by masker.generate_report() be centered somewhere on atlas, so alignment can be judged.

### Actual behavior
When functional data is used as the underlay, cursor is always at y=17, x=19, z=56, whether the atlas is visible in those slices or not.

image

### Steps and code to reproduce bug
ROI attached, but I am not able to share functional image - any functional in MNI space should work.
```python
# load nilearn harvard oxford atlas
atlasI = nimg.load_img('/autofs/cluster/neuromod/personal_folders/walker_pedersen/BNSTmni/MNI152_T1_1mm-RBNST.nii.gz', dtype=int)
labelL = ['Background','RBNST']
# load atlas into masker
masker = input_data.NiftiLabelsMasker(
            atlasI, labels=labelL, standardize=False,
            verbose=0, detrend=False)
# visualize atlas ROIs
masker.fit()
report1 = masker.generate_report()
masker.fit(cleanI)
report2 = masker.generate_report()
```
[MNI152_T1_1mm-RBNST.nii.gz](https://github.com/nilearn/nilearn/files/7758303/MNI152_T1_1mm-RBNST.nii.gz)

### PR DESCRIPTION
**Pull request by ymzayek**
- Supersedes #3116
- Closes #3110
- Closes #3116

### CODE REVIEW

**Comment by ymzayek** [comment]
A quick example showing the same cut coords with an dwithout passing func image:

```python
# %%
from nilearn.maskers import NiftiLabelsMasker
from nilearn import datasets
from nilearn.image import load_img
from nilearn._utils import data_gen
import numpy as np

data = datasets.fetch_development_fmri(n_subjects=1)
data = load_img(data["func"][0])
atlas = data_gen.generate_labeled_regions(
    (13, 11, 12), affine=np.eye(4), n_regions=5
)
masker = NiftiLabelsMasker(atlas)
masker.fit()
report = masker.generate_report()
report

#%%
masker.fit(data)
report = masker.generate_report()
report
```

image
image

**Review by bthirion — COMMENTED** [review]
LGTM, thx.

**Review by bthirion — APPROVED** [review]
LGTM.

**Review by Remi-Gau — APPROVED** [review]
good with me

**Comment by ymzayek** [comment]
Thanks merging

**Pull request merged**
