### PR TITLE
Update image.py

### PR DESCRIPTION
**Pull request by Leo-YF-Liu**
dtype issue for anlyzeImage

### CODE REVIEW

**Comment by bthirion** [comment]
The patch LGTM. Can you add a non-regression test ?

**Comment by KamalakerDadi** [comment]
This looks good so far. Could you add a tests in nilearn/image/tests/test_image.py and nilearn/tests/test_masking.py? One for function new_img_like and compute_epi_mask

A dummy image can be created like this, for instance.
```python
data = np.ones((5, 6, 7))
img = nibabel.spm2.Spm2AnalyzeImage(data, affine=np.diag((4, 3, 2, 1)))
```

**Comment by KamalakerDadi** [comment]
We might will have similar issues with nibabel.spm99.Spm99AnalyzeImage

**Comment by KamalakerDadi** [comment]
Is there any option in nibabel where we can collectively check SpmAnalyze images for both ?

**Comment by effigies** [comment]
Okay, so I'm looking at this and trying to come up with a way to do this that is general and doesn't require looking at hidden class variables.

1) Just use `np.uint8`. Bools will never be negative, and I *think* all classes permit `uint8`s.
2) A quick test (memoized):

```Python
@functools.lru_cache
def supports_dtype(klass, dtype):
    try:
        klass(np.zeros((1,1,1), dtype=dtype).set_data_dtype(dtype)
        return True
    except:
        return False
```

3) Just go ahead and access the private object:

```Python
>>> np.int8 in nb.Nifti1Image.header_class._data_type_codes
True
>>> np.int8 in nb.AnalyzeImage.header_class._data_type_codes
False
```

4) A new nibabel method/property that lists valid dtypes for the image. It does seem useful to query.

cc @thomasbazeille

**Comment by GaelVaroquaux** [comment]
If you were to modify nibabel, I'd suggest to have less private variables. That way we could just like at the relevant variable.

Solution 1 seems appealing. The only drawback is that it changes user-facing results. I don't think that it is the end of the world, and I would be in favor of doing this and clearly advertising it in the changelog.

**Comment by effigies** [comment]
I've opened a discussion about a possible API over in https://github.com/nipy/nibabel/issues/913.

**Comment by thomasbazeille** [comment]
I try to rebuild a minimal failure example, but I'm not sure I find it is. @Leo-YF-Liu, can you give pointers as there is no associated issue here.

Is it something like : 
```
import nibabel
import numpy as np
int8_data = np.ones((5, 6, 7),dtype=np.int8())

img = nibabel.spm2.Spm2AnalyzeImage(np.ones((5, 6, 7)), affine=np.diag((4, 3, 2, 1)))

from nilearn.image import new_img_like
new_img_like(img,data)
```

**Comment by effigies** [comment]
It's specifically for coercing boolean data to a saveable dtype:

```Python
import nibabel as nb
import numpy as np
from nilearn import image as nli

in_img = nb.AnalyzeImage(np.random.default_rng().random((5, 5, 5)), affine=np.eye(4))

out_img = nli.new_image_like(in_img, data=in_img.get_fdata() > 0.5)
```

**Comment by effigies** [comment]
Personally I'd be okay with 1+4. `uint8` has better compatibility across image formats and software suites than `int8`, and we can add the proposed method to nibabel. I just didn't get much feedback last time and this completely fell of my radar.

**Comment by ymzayek** [comment]
@effigies 1+4 also seem reasonable to me. I don't see any drawbacks except for what was outlined by @GaelVaroquaux about 1 changing user-facing results but I think we can live with that. And it would be specified in the changelog. If no one objects, I'll open a new PR to make the change on our side. Though not necessary in this case, I do agree that 4 would be useful to have as well in nibabel. And if someone thinks it's a bad idea to always default to `uint8` we can then use the query.

**Pull request closed without merging**
