### PR TITLE
[FIX] Use builtin functions instead of numpy's deprecated aliases

### PR DESCRIPTION
**Pull request by ymzayek**
Addresses failures: https://github.com/nilearn/nilearn/actions/runs/3547323012/jobs/5957319235

Using python builtin `float` instead of `np.float` is recommended and does not have any impact on behavior.
Using python builtin `int` instead of `np.int`; idem
See: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
LGTM so far. Deserves a "whatsnew" entry imho.

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks @ymzayek !

**Comment by ymzayek** [comment]
Merging

**Pull request merged**
