### PR TITLE
Rename dataset fetching functions.

### PR DESCRIPTION
**Pull request by AlexandreAbraham**
Following Gael suggestion: prefix all atlas fetching functions by `fetch_atlas`.

Discussion: should we choose that solution or create an atlas module?

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
We should do both: datasets should become a sub package. It should be divided in several modules, one of them with the atlases. All functions useful for users should be imported in the init. In addition, there should be a name convention.

**Comment by bthirion** [comment]
LGTM.

**Comment by AlexandreAbraham** [comment]
@GaelVaroquaux 
I suggest:

datasets
* dataset.utils (for general purpose functions)
* datasets.atlas
* datasets.study (I think a better naming is possible here)
* datasets.template

**Comment by banilo** [comment]
+1

**Pull request merged**
