### PR TITLE
[DOC] Add maskers note in examples

### LINKED ISSUE #3158: Add note for new `maskers` module in examples
In release `0.9.0` we moved all maskers from the `input_data` to the `maskers` module and updated the docs and examples accordingly. However, users with a nilearn version `< 0.9` reading the examples on the website might get confused when getting an error saying that the maskers module does not exist if they just copy paste the code.

See this [Neurostars post](https://neurostars.org/t/no-module-named-nilearn-maskers-nilearn-9-4-6/21467).

We should probably add a note in these examples saying that users should either upgrade to `>= 0.9`, or import `maskers` from `input_data`.

WDYT?

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Closes #3158

### CODE REVIEW

**Comment by NicolasGensollen** [comment]
> You haven't covered all relevant examples yes, have you ?

I think I did. Did you spot any forgotten ones?

**Comment by bthirion** [comment]
No. I expected that there would be more, but it seems not to be the case.

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Comment by ymzayek** [comment]
I checked the files containing the relevant import statement and there seems to be one more that you can include the note in. See line 143 in [manual_pipline.rst](https://github.com/nilearn/nilearn/blob/main/doc/building_blocks/manual_pipeline.rst)

**Comment by NicolasGensollen** [comment]
Thanks for the review @ymzayek !
I included the note as you suggested in [b0fcc80](https://github.com/nilearn/nilearn/pull/3214/commits/b0fcc80688b0e1583277f9264ab3b6dff29641db)

**Review by ymzayek — APPROVED** [review]
Great, looks good!

**Comment by NicolasGensollen** [comment]
Thanks for the review ! Merging...

**Pull request merged**
