### PR TITLE
Release 0.10.2

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes none

To be merged after: 

- #4012 
- #4013 
- [x] mention experimental features in highlights
- [x] renaming `doc/changes/latest.rst` to `doc/changes/0.10.2.rst`
- [x] make Zenodo sync is enabled: https://github.com/nilearn/nilearn/issues/3963

EDIT

To do after merge:

- [ ] create a new `doc/changes/latest.rst`

### CODE REVIEW

**Comment by ymzayek** [comment]
> create a new doc/changes/latest.rst

Just a note, we should do this in the post release and remove it from the include in whatsnew.rst in this PR. Once this is merged we'll tag it with the release version and build the stable docs from that and we don't want an empty dev header in that.

**Comment by ymzayek** [comment]
> make Zenodo sync is enabled: https://github.com/nilearn/nilearn/issues/3963

It should be good but let's verify together tomorrow. Can also look at how to transfer the permissions

**Comment by Remi-Gau** [comment]
> > create a new doc/changes/latest.rst
> 
> Just a note, we should do this in the post release and remove it from the include in whatsnew.rst in this PR. Once this is merged we'll tag it with the release version and build the stable docs from that and we don't want an empty dev header in that.

ah yeah will make that clear in the TODO

**Review by bthirion — COMMENTED** [review]
LGTM so far.

**Review by ymzayek — APPROVED** [review]
Good to go when the CI passes

**Comment by Remi-Gau** [comment]
> Good to go when the CI passes

I am afraid to type those words now: it may just jinx it.

**Pull request merged**
