### PR TITLE
Improve social-media links with `sphinxext-opengraph`

### PR DESCRIPTION
**Pull request by NicolasGensollen**
This PR proposes to improve social-media links by using [sphinxext-opengraph](https://github.com/wpilibsuite/sphinxext-opengraph) as suggested by @GaelVaroquaux

### CODE REVIEW

**Comment by NicolasGensollen** [comment]
Looks like there are still a few issues to solve (missing image and I realize we don't have a title in `doc/index.rst`):

title

**Comment by NicolasGensollen** [comment]
Actually, it looks like other pages render well:

sphinxext

I'm not sure what to do with the landing page. We explicitely don't set a title in `index.rst` such that the title is empty:

```html
<meta property="og:title" content="<no title>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://nilearn.github.io/index.html" />
<meta property="og:site_name" content="Nilearn" />
<meta property="og:description" content="Nilearn enables approachable and versatile analyses of brain volumes. It provides statistical and machine-learning tools, with instructive documentation & open community. It supports general linear..." />
<meta property="og:image" content="auto_examples/01_plotting/images/sphx_glr_plot_demo_glass_brain_002.png" />
<meta property="og:image:alt" content="glass_brain" />
```

Also, the image found (the first one) is `auto_examples/01_plotting/images/sphx_glr_plot_demo_glass_brain_002.png` but it looks like the path is not resolved correctly compared to a working page:

```html
<meta property="og:title" content="9.1.2. Basic nilearn example: manipulating and looking at data" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://nilearn.github.io/auto_examples/plot_nilearn_101.html" />
<meta property="og:site_name" content="Nilearn" />
<meta property="og:description" content="A simple example showing how to load an existing Nifti file and use basic nilearn functionalities.# Let us use a Nifti file that is shipped with nilearn from nilearn.datasets import MNI152_FILE_PAT..." />
<meta property="og:image" content="../_images/sphx_glr_plot_nilearn_101_001.png" />
<meta property="og:image:alt" content="plot nilearn 101" />
```

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Comment by NicolasGensollen** [comment]
>Is there a reason that this is still draft? It seems mergeable

@GaelVaroquaux If I remember correctly, it was working perfectly for all pages except the landing page where the title and image were missing from the card. I'll have another go at fixing this!

**Comment by bthirion** [comment]
indeed, the landing page deserves a fix. Thx !

**Comment by NicolasGensollen** [comment]
The card for the index page is still not showing the right image at the moment. I don't think hacking directly into the html code as I was trying before is a good solution. In addition, I would like the image of the card to be nilearn's logo rather than the first image of the index page (makes more sense to me).
I opened this [issue](https://github.com/wpilibsuite/sphinxext-opengraph/issues/45) on `sphinxext-opengraph` to ask for this kind of feature and it looks like they are working on it.

Since this PR is working perfectly for all other pages, I'd be of the opinion to merge it and improve the rendering of the index page card in a future PR (even with no image, it already looks better than a simple link anyway).
WDYT?

**Comment by thomasbazeille** [comment]
> Since this PR is working perfectly for all other pages, I'd be of the opinion to merge it and improve the rendering of the index page card in a future PR (even with no image, it already looks better than a simple link anyway).
> WDYT?

+1 as well

**Review by thomasbazeille — APPROVED** [review]

**Comment by GaelVaroquaux** [comment]
Looks good!

I resolved the conflict online (don't push, @NicolasGensollen ). I'll merge when everything is green.

**Pull request merged**
