### PR TITLE
[MRG+1] Bump nibabel

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Continuity of PR #1533

### CODE REVIEW

**Comment by KamalakerDadi** [comment]
Last commit to revert FIXing AppVeyor is only for simplification to make reviewing easier for this PR. Keeping only changes specific to bumping nibabel version.

**Comment by KamalakerDadi** [comment]
I think this one ready to merge if not any comments. Failure with AppVeyor is planned to FIX in this PR #1535

**Comment by bthirion** [comment]
Looks great, thx.

**Comment by GaelVaroquaux** [comment]
LGTM. The appveyor failure is unrelated. Merging, thank you.

**Comment by GaelVaroquaux** [comment]
I've merged. Can you do a PR with the AppVeyor fix. Thanks!

**Comment by KamalakerDadi** [comment]
>I've merged. Can you do a PR with the AppVeyor fix.

Thank you for merging. Fix for AppVeyor is already done in PR #1535 . I am waiting for opinions.

**Pull request merged**
