### PR TITLE
conda test with sklearn 0.12

### PR DESCRIPTION
**Pull request by kshmelkov**
Test of CI build

### CODE REVIEW

**Comment by lesteve** [comment]
I really liked the fact that this was testing a litte bit of our setup.py (pip installing nibabel if it wasn't already installed) . Can we still have that if the NIBABEL is not defined?

**Comment by AlexandreAbraham** [comment]
What is blocking this one?

**Comment by lesteve** [comment]
In the mist of the sprint I have to admit I didn't fully follow how it was decided to bump up required versions so a brief reminder would be greatly appreciated. In particular does scikit-learn 0.12.1 have a special meaning?

At the very least I would keep an unaldurated neurodebian (i.e. with matplotlib), because it seems like a reasonable target given our end users and move the "no matplotlib" tests to a conda based environment.

**Comment by GaelVaroquaux** [comment]
> In the mist of the sprint I have to admit I didn't fully follow how it was
> decided to bump up required versions so a brief reminder would be greatly
> appreciated.

Supporting scikit-learn 0.10 was too expensive, and neurodebian means
that even old ubuntu install can easily get more recent versions.

> In particular does scikit-learn 0.12.1 have a special meaning?

No. It's a configuration that's 2 years old, and we felt that 2 years old
was a good time.

> At the very least I would keep an unaldurated neurodebian (i.e. with
> matplotlib), because it seems like a reasonable target given our end users and
> move the "no matplotlib" tests to a conda based environment.

Agreed!

**Comment by bcipolli** [comment]
I rebased to master here:
https://github.com/bcipolli/nilearn/tree/kshmelkov-master

I need to be on the proper versions to test the `fix_warnings` PR (https://github.com/nilearn/nilearn/pull/371).  Are there any concerns with the versions used to test in this PR?

Thanks!

**Comment by lesteve** [comment]
Closed in favor of #502.

**Pull request closed without merging**
