### PR TITLE
Allow disabling auto resize of figure because of colorbar (fix issue #1596)

### PR DESCRIPTION
**Pull request by lrq3000**
Just as in the title :-) #1596

### CODE REVIEW

**Comment by lrq3000** [comment]
BTW for those curious, it seems it's possible to force resize a nilearn figure like this:

```python
resize_pct = 1.1
rect = fig.rect
fig.rect = ([x*resize_pct for x in rect])
```

**Comment by bthirion** [comment]
Thx for doing that. Would you mind documenting a bit this additional argument ?
Ideally, you probably want to showcase this in an example to let people know about it.

**Comment by lrq3000** [comment]
@bthirion you mean documenting in the docs or in the code (I did not find where in the code)?

**Comment by bthirion** [comment]
Oh, I see: `_map_show()` has no docstrings. Then I'd go for adding a small paragraph in the documentation. (Otherwise, people will keep complaining about the issue). If course, this pertains to the advances part of visualization capabilities.

**Comment by GaelVaroquaux** [comment]
The real fix of this problem would be to fix the bounds computation for contours. Right now it is suboptimal as is takes in account all the volume of the map, which leads to a resizing to a size too small. A proper computation of the bounds will have a much smaller size, and hence not force a resize.

It would be a much better fix than the proposed one, as the proposed one introduces an option that users are unlikely to see.

**Comment by bthirion** [comment]
Closing for now.

**Pull request closed without merging**
