### PR TITLE
[MRG] Renaming fREM => FREM + improving what's new

### PR DESCRIPTION
**Pull request by thomasbazeille**
Two PRs in one but everything documentation:

- Solving #2494 about FREM method case
- Adding some important things to whats new (Nistats functions in Nilearn, FREM and an example)

Ready for review

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
LGTM

**Comment by bthirion** [comment]
Can you take care of the CircleCI failure ?

**Comment by thomasbazeille** [comment]
> Can you take care of the CircleCI failure ?

Waiting for the merge of #2565 that handles it

**Comment by thomasbazeille** [comment]
CI passing, I think it's ready for merge

**Comment by bthirion** [comment]
Merged, thx !

**Pull request merged**
