### PR TITLE
[FIX] Fix memory issue on CircleCI

### PR DESCRIPTION
**Pull request by NicolasGensollen**

### CODE REVIEW

**Comment by bthirion** [comment]
Is this related to an issue ? Best,

**Comment by NicolasGensollen** [comment]
>Is this related to an issue ? 

@bthirion it's related to a sporadic memory failure on CircleCI which seem to occur when running this example (see [yesterday's nightly build](https://app.circleci.com/pipelines/github/nilearn/nilearn/3412/workflows/751ca97b-169d-4f40-ae89-821def33430f/jobs/8641) for example).

**Comment by bthirion** [comment]
All right. I guess that the hard part is to check whether this indeed solves the issue.

**Review by bthirion — APPROVED** [review]

**Comment by NicolasGensollen** [comment]
>I guess that the hard part is to check whether this indeed solves the issue.

Yes, but since most builds were failing recently, we should see if it works pretty quickly.
Merging to test it out....
Thanks!

**Pull request merged**
