### PR TITLE
[FIX] Adjust figure size to display title for functions calling `plot_surf`

### LINKED ISSUE #4119: [BUG] `nilearn.plotting.plot_sur_stat_map` does not display the provided title
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

For example one of the following:
- Linux Ubuntu 22.04
- Mac OS Version 12 "monterey"
- Windows 11

### Python version

- [ ] 3.12
- [X] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

Dev version

### Expected behavior

Image itle should be displayed on the image

### Current behavior & error messages

It is actually missing.

### Steps and code to reproduce bug

This is visible in the documentation
https://nilearn.github.io/stable/auto_examples/01_plotting/plot_3d_map_to_surface_projection.html#sphx-glr-auto-examples-01-plotting-plot-3d-map-to-surface-projection-py

### PR DESCRIPTION
**Pull request by ymzayek**
- Closes #4119

Changes proposed in this pull request:

-
-

### CODE REVIEW

**Comment by ymzayek** [comment]
Seems to have fixed the problem in all examples using the relevant surf plotting functions: https://output.circle-artifacts.com/output/job/e4d6c344-b1b0-4f0b-8923-7b56934caf53/artifacts/0/dev/modules/generated/nilearn.plotting.plot_surf_stat_map.html#examples-using-nilearn-plotting-plot-surf-stat-map

**Comment by bthirion** [comment]
Thx ! I'd dream to have a test for that, but I guess it's ill-posed in our framework.

**Review by bthirion — APPROVED** [review]
Thx for the fix.

**Comment by ymzayek** [comment]
Ok merging this one since it's a tiny fix

@bthirion the proposal in https://github.com/nilearn/nilearn/pull/4123 could maybe help a bit on this end. Other than that visually checking from time to time is necessary. It's hard to anticipate how things like this will affect rendering in the context of sphinx builds

**Pull request merged**
