### PR TITLE
Update news and add links to whats new

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Changes proposed in this pull request:

- Update news
- Add links to specific versions in `whats_new.html`

### CODE REVIEW

**Review by GaelVaroquaux — COMMENTED** [review]
Try adding named anchors in the what's new file,  on the corresponding titles

**Comment by NicolasGensollen** [comment]
I was a bit lazy and only added anchors for the last 3 versions... I can take the time to add them all if needed

**Comment by jeromedockes** [comment]
> I was a bit lazy and only added anchors for the last 3 versions... I can take the time to add them all if needed

I think adding them only for the last 3 is fine!

**Review by GaelVaroquaux — APPROVED** [review]
LGTM. Thanks!!

**Pull request merged**
