### PR TITLE
Replace pylab import by pyplot

### PR DESCRIPTION
**Pull request by AlexandreAbraham**
Replace pylab by pyplot. Also, I reraise the import exception because, in the case of people that doesn't have matplotlib installed, we want to raise a meaningful error and not crash in the middle of a script.

### CODE REVIEW

**Comment by eickenberg** [comment]
LVGTM

**Comment by lesteve** [comment]
You may as well replace all `import pylab` instances while you are at it.

```
~/dev/nilearn $ git grep -l pylab nilearn
nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_cm.py
nilearn/plotting/tests/test_displays.py
nilearn/plotting/tests/test_img_plotting.py
```

**Comment by AlexandreAbraham** [comment]
@lesteve , any remaining objection?

**Comment by lesteve** [comment]
Good stuff, thanks a lot.

**Pull request merged**
