### PR TITLE
Remove deprecated `fetch_surf_fsaverage5` 

### PR DESCRIPTION
**Pull request by jnecus**
Issue #2358

### CODE REVIEW

**Comment by jnecus** [comment]
I was hoping to raise these two commits as separate PRs. Is there a way to do so?

**Comment by bthirion** [comment]
Thx. I would not advise to issue too many PRs, because ou CI systems are under high pressure. So this PR is fine.

But in general, you can cherry pick a given commit to a new branch. Personally, I do this kind of operations with gitk that has a nice graphical interface to make interaction with the commit history very easy and intuitive.

**Comment by thomasbazeille** [comment]
The Circle CI fail seems unrelated to this PR, more related to #2436

```Warning, treated as error:
/home/circleci/project/examples/plot_first_level_model_details.py failed to execute correctly: Traceback (most recent call last):
  File "/home/circleci/miniconda3/envs/testenv/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 460, in _memory_usage
    out = func()
  File "/home/circleci/miniconda3/envs/testenv/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 442, in __call__
    exec(self.code, self.fake_main.__dict__)
  File "/home/circleci/project/examples/plot_first_level_model_details.py", line 36, in <module>
    data = func.fetch_localizer_first_level()
  File "/home/circleci/project/nilearn/datasets/func.py", line 2452, in fetch_localizer_first_level
    files = _fetch_files(data_dir, filenames, verbose=verbose)
  File "/home/circleci/project/nilearn/datasets/utils.py", line 777, in _fetch_files
    raise IOError('Fetching aborted: ' + abort)
OSError: Fetching aborted: [Uncompress] unknown archive file format: /home/circleci/nilearn_data/localizer_first_level/775984ff61321050eba8738c4176eda5/download
```

**Comment by jeromedockes** [comment]
> The Circle CI fail seems unrelated to this PR, more related to #2436

yes it seems the cached data dir that was there has expired and several
dataset downloads from osf are actually failing at the moment.
neurosynth.org is also down

**Comment by GaelVaroquaux** [comment]
The CircleCI error seems spurious to me. I am merging this.

**Pull request merged**
