### PR TITLE
[INFRA] Update docs `install` target

### PR DESCRIPTION
**Pull request by NicolasGensollen**
This PR updates the steps for the `install` target of the documentation Makefile.
This is necessary since we now deploy the development version of the documentation every time a PR is merged in main.

### CODE REVIEW

**Comment by NicolasGensollen** [comment]
FYI, I used this updated version of the Makefile to release 0.9.0, but it'b be great to have some reviews before merging for 0.9.1.

**Review by alexisthual — APPROVED** [review]
It looks good to me.
A while ago, we mentioned serving documentation for different releases of nilearn, is it still something we want to do? Should we use something like [`sphinx-multiversion`](https://holzhaus.github.io/sphinx-multiversion/master/index.html)?

**Comment by NicolasGensollen** [comment]
>is it still something we want to do?

I think this is something we should aim for. Having stable/dev versions was a first step toward this goal.

>Should we use something like [sphinx-multiversion](https://holzhaus.github.io/sphinx-multiversion/master/index.html)?

Never tried it, but definitely something to consider! I'll try to experiment a bit on toy repos.

**Comment by bthirion** [comment]
> > is it still something we want to do?
> 
> I think this is something we should aim for. Having stable/dev versions was a first step toward this goal.
> 
> > Should we use something like [sphinx-multiversion](https://holzhaus.github.io/sphinx-multiversion/master/index.html)?
> 
> Never tried it, but definitely something to consider! I'll try to experiment a bit on toy repos.

I can see the advantage, but also the burden in terms of maintenance etc. I'm not 100% convinced we should do it. To be discussed in future meetings?

**Comment by emdupre** [comment]
> I can see the advantage, but also the burden in terms of maintenance etc. I'm not 100% convinced we should do it. To be discussed in future meetings?

+1 to discuss this and try to keep the maintenance / UX relatively light -- maybe we could settle on something like only providing documentation for previous major releases. I think this is what MNE does, from a quick look at their docs !

**Review by bthirion — APPROVED** [review]

**Comment by NicolasGensollen** [comment]
Thanks for the reviews! Merging...

**Pull request merged**
