### PR TITLE
ENH: partial duecredit support for nilearn

### PR DESCRIPTION
**Pull request by mslw**
Trying to address:
Gael's complaint

Usage example:
```
(dev27) dhcp-206-12-53-73:OHBM_Hackathon michal$ python -m duecredit nilearn/examples/02_decoding/plot_haxby_searchlight.py
Anatomical nifti image (3D) is located at: /Users/michal/nilearn_data/haxby2001/mask.nii.gz
Functional nifti image (4D) is located at: /Users/michal/nilearn_data/haxby2001/subj2/bold.nii.gz
/Users/michal/Documents/OHBM_Hackathon/duecredit/venvs/dev27/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   54.0s finished

DueCredit Report:
- I/O library to access to common neuroimaging file formats / nibabel (v 2.1) [1]
- Nilearn underlying patterns article / nilearn (v 0.3.1) [2]
  - Searchlight analysis approach / nilearn.decoding.searchlight:search_light (v 0.3.1) [3]
- Scientific tools library / numpy (v 1.8.0rc1) [4]

3 packages cited
0 modules cited
1 function cited

References
----------

[1] Brett, M. et al., 2015. nibabel 2.0.1.
[2] Abraham, A. et al., 2014. Machine learning for neuroimaging with scikit-learn. Frontiers in Neuroinformatics, 8.
[3] Kriegeskorte, N., Goebel, R. & Bandettini, P., 2006. Information-based functional brain mapping. Proceedings of the National Academy of Sciences, 103(10), pp.3863–3868.
[4] Van Der Walt, S., Colbert, S.C. & Varoquaux, G., 2011. The NumPy array: a structure for efficient numerical computation. Computing in Science & Engineering, 13(2), pp.22–30.
```

For more information, see [DueCredit](https://github.com/duecredit/duecredit)

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
It's not a technical problem: these people are very much aware of the papers they should be citing. Those papers are given in the documentation. It's a social problem: they are choosing not to cite the paper.

We cannot go in this direction, as it adds a dependency to the codebase that is not justified. We have a strict minimal dependency policy in nilearn.

**Comment by GaelVaroquaux** [comment]
Sorry that you worked on this and that your work is not being merged.

It would have been better to open an issue asking whether such contribution is needed. That way we can synchronize before the code is written.

**Comment by mslw** [comment]
Not a problem, @GaelVaroquaux. Together with @yarikoptic, during OHBM Hackathon, we have been working on enhancing the DueCredit itself and while at it, we decided to annotate some of nilearn's functions as a showcase :)

**Comment by yarikoptic** [comment]
FWIW -- dependency on duecredit (if you check included in this PR `due.py`) is very very optional.  If there is no duecredit, all is good, no warning of any kind, etc.  Even if duecredit is installed, ATM you would need to explicitly enable duecredit mode (via DUECREDIT_ENABLE env var, or using `-m duecredit` option for interpreter) to get its machinery going.

But sure no problem, we could migrate those into the set of injections we maintain for such cases where upstream doesn't want to include them "properly".  In that case though it lives outside of the code base and there would be some cons (out of sync, etc)

**Comment by GaelVaroquaux** [comment]
I'll be there (at the hackathon) soon. 

⁣Sent from my phone, please excuse typos and briefness​

**Comment by yarikoptic** [comment]
ha -- see you there (well -- here).
As for social vs technical -- it is both.  In many cases users do not know what they should have cited.  E.g. do you always cite our NeuroDebian when you use it? ;-) (and I suspect that you do)

**Pull request closed without merging**
