### PR TITLE
[ENH] Refactor `surf_mask` fixture to be 1D

### PR DESCRIPTION
**Pull request by man-shu**
- Closes None but related to https://github.com/nilearn/nilearn/pull/4830#discussion_r1877787373

Changes proposed in this pull request:

- remove extra dimension in surface mask fixture

### CODE REVIEW

**Comment by Remi-Gau** [comment]
should we still have a 2D mask fixture?

**Comment by man-shu** [comment]
> should we still have a 2D mask fixture?

At least with volumes, I think we always expect 3D masks (no time points, meaning you can't pass different masks for different time points). For example, with NiftiMasker we check mask_img to be 3D:

https://github.com/nilearn/nilearn/blob/04be71faa15194e41e9455ca87d3b4427580ff42/nilearn/maskers/nifti_masker.py#L454

**Comment by man-shu** [comment]
Yes we can have it but I can't think of a use case for that

**Comment by Remi-Gau** [comment]
> I can't think of a use case for that

wait until one user provide one of those mask and you will have a use for it. 😜

**Review by bthirion — APPROVED** [review]

**Comment by man-shu** [comment]
> wait until one user provide one of those mask and you will have a use for it. 😜

🤣 ok so you mean we should have the fixture to test for the eventuality when a user passes a SurfaceImage.
* I can see a use of it in #4830 at least.
Will make one..

**Comment by Remi-Gau** [comment]
Do you think you could paramatrize some of the test to check that places that accept a 1D mask are also fine with a 2D one.

I think they should all pass, but this way we can prevent some regression.

**Review by Remi-Gau — CHANGES_REQUESTED** [review]
Do you think you could paramatrize some of the test to check that places that accept a 1D mask are also fine with a 2D one.

I think they should all pass, but this way we can prevent some regression.

**Comment by man-shu** [comment]
> Do you think you could paramatrize some of the test to check that places that accept a 1D mask are also fine with a 2D one.

Done!

**Pull request merged**
