### PR TITLE
allow array-like marker_size in view_connectome and view_markers

### PR DESCRIPTION
**Pull request by jeromedockes**
see #1897

### CODE REVIEW

**Comment by bthirion** [comment]
LGTM. The  travis issue seems unrelated.

**Comment by KamalakerDadi** [comment]
Is it a valid usage to give single size to plot for all coordinates in a list ```[20]``` ? If yes, I see some problems with it.

**Comment by jeromedockes** [comment]
> Is it a valid usage to give single size to plot for all coordinates in a list `[20]` ? If yes, I see some problems with it.

I would say no, if it is a sequence it should be the same length as the nodes

**Comment by kchawla-pi** [comment]
Sorry about the conflict.
If you push to this branch before midnight today, CIrcleCI will not rebuild from scratch, and should complete in ~10 minutes.

**Comment by kchawla-pi** [comment]
I am gonna merge this today.

**Comment by kchawla-pi** [comment]
Hey @jeromedockes this should be added to whats new.rst

**Pull request merged**
