### PR TITLE
Update windows version for azure CI runners

### PR DESCRIPTION
**Pull request by ymzayek**
For reference see: https://github.com/actions/virtual-environments/issues/5403

For `job: 'test_installing_on_windows'` changed `vmImage` from `'vs2017-win2016'` to `'windows-latest'`

Otherwise azure pipelines jobs get cancelled.

### CODE REVIEW

**Comment by bthirion** [comment]
I'm a bit confused by the many failures we still have. Rebase on main ?

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks for fixing this @ymzayek ! 👍

**Review by bthirion — APPROVED** [review]
thx @ymzayek

**Comment by bthirion** [comment]
Merging, thx.

**Pull request merged**
