### PR TITLE
Lighter circle configuration

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Trying to simplify the circleCI build to make it more stable.

### CODE REVIEW

**Comment by bthirion** [comment]
OK provided that circleci agrees

**Comment by kchawla-pi** [comment]
I was under the impression that `cython` improved speed of examples, or was required by one of the packages that does.

**Comment by GaelVaroquaux** [comment]
> I was under the impression that cython improved speed of examples,

We don't use it in nilearn

> or was required by one of the packages that does.

If all packages are shipped compiled, it shouldn't be.

Anyhow, let's just see if this builds.

**Comment by GaelVaroquaux** [comment]
This saved a few minutes of run time. It still failed, but for reasons independent of this PR. Hence, I am merging, given that it is failing in master too.

**Pull request merged**
