### PR TITLE
[DOC] reduce font size for headings

### LINKED ISSUE #3928: text overflow in documentation html rendering
See the "highlights" in the image below.

tmp

This is not mission critical but if someone feels like playing with furo's CSS:

https://pradyunsg.me/furo/customisation/#css-variables

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes #3928

Technically this does not quite solve the overflow but indirectly helps by making the headings smaller.

This was especially needed on smaller viewports.

Changes proposed in this pull request:

- reduce headings size for different view ports

### CODE REVIEW

**Comment by Remi-Gau** [comment]
I suspect there may be a way to also avoid things like this 👍🏾 

image


by removing the prefix in the `nilearn.glm` in the local table of content but I think this may require playing with jinja templating and arcane sphinx things that are not worth the effort

**Comment by Remi-Gau** [comment]
Fullwidth (1920px):

Before

image


After

image

**Comment by Remi-Gau** [comment]
Width 1300px

Before
image

After
image

**Comment by Remi-Gau** [comment]
width 390px

Before
image


After
image

**Review by ymzayek — APPROVED** [review]
LGTM

**Pull request merged**
