### PR TITLE
[MAINT] Update git protocol in CircleCI fetch step

### PR DESCRIPTION
**Pull request by NicolasGensollen**

### CODE REVIEW

**Comment by bthirion** [comment]
Seems to work ;-)

**Review by bthirion — APPROVED** [review]
Thx !

**Comment by NicolasGensollen** [comment]
@tsalo : Github made some changes to increase security, among which dropping support for unencrypted git protocols. See https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by NicolasGensollen** [comment]
Thanks, merging...

**Pull request merged**
