### PR TITLE
[MRG+1] Unvendored sphinx-gallery & numpydocs

### PR DESCRIPTION
**Pull request by kchawla-pi**
- Adjusted conf.py per new ver of them

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Have you integrated the latest junit XML support of sphinx-gallery in
circleCI?
https://sphinx-gallery.github.io/configuration.html#using-junit-xml-files

**Comment by kchawla-pi** [comment]
Not in this PR, once this is all green I'll open a new PR for issue #1965

**Comment by kchawla-pi** [comment]
Update: Once this is all green, I'll merge it.

**Comment by GaelVaroquaux** [comment]
This looks ready to merge. Do you want to merge it before or after the release? I would have thought after.

**Comment by kchawla-pi** [comment]
We can merge it now, I will make the release from it's branch, not master.

**Comment by kchawla-pi** [comment]
Just make sure the reference links in conf.py that I changed look okay. I
based them on SKLs conf.py so should be fine,but take a look anyway.

**Comment by GaelVaroquaux** [comment]
> Just make sure the reference links in conf.py that I changed look okay. I based them on SKLs conf.py so should be fine,but take a look anyway.

Do links from objects in the examples work or not?

**Comment by kchawla-pi** [comment]
The 6-7 links I clicked in Build Artifacts work correctly.

**Comment by GaelVaroquaux** [comment]
OK. Merging, then!

**Pull request merged**
