### PR TITLE
[FIX] Revert "checklist_dummy"

### PR DESCRIPTION
**Pull request by Remi-Gau**
Reverts nilearn/nilearn#3515

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Let me know if reset is preferable to a PR with a revert.

**Comment by emdupre** [comment]
Thanks, @Remi-Gau  ! 

Will let others comment on reset v revert, but this is now much more readable IMHO. We might just need additional line breaks before the new `For new features:` and `For bug fixes:` subsections.

**Comment by Remi-Gau** [comment]
Yup I have that ready in another branch.

Right now this revert just litteraly undoes my hasty pr merging (note to self : stay away from the computer after 22h).

So we could either:

A) close this PR and open another one from the branch that will give the proper format.

B) merge this PR and then I open another one from the other branch that will give the proper format

C) do a reset and then I open the PR to once again get the proper checklist format.

Just not sure what is the nilearn take on rewriting git log history.

**Comment by bthirion** [comment]
A) feels OK to me.

**Comment by Remi-Gau** [comment]
OK closing this then.

**Pull request closed without merging**
