### PR TITLE
[DOC] update doc to mention how get all the tags from upstream to get the proper version displayed

### LINKED ISSUE #3850: [DOC] Add commands to get the version tags when forking in the contributing-setting up your env doc
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

To have the proper version attached to a fork it is required to add the source repo as upstream and fetch all the tags so that they can be used to display the current version. This is done by running the following commands :

`git remote add upstream git@github.com:nilearn/nilearn.git`
`git fetch --all`

These commands could be added to the doc in the setting up your environnement section of the contributing page.

### List any pages that would be impacted.

https://nilearn.github.io/dev/development.html#setting-up-your-environment

### PR DESCRIPTION
**Pull request by Remi-Gau**
Closes #3850 

Changes proposed in this pull request:

- add instruction on how to add upstream remote and fetch all the tags

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@FrancoisPgm if you want to have a look

**Review by ymzayek — APPROVED** [review]

**Comment by bthirion** [comment]
doc build looks broken ?

**Comment by Remi-Gau** [comment]
> doc build looks broken ?

yup because I cannot rst even if my life depends on it.

should be fixed but let's wait for the CI to complete

**Comment by Remi-Gau** [comment]
All green.
Merging.

**Pull request merged**
