### PR TITLE
[wip] Harmonize datasets.fetch_atlas output attributes 

### PR DESCRIPTION
**Pull request by illdopejake**
The goal is to ensure that, once fetched, the atlas objects all have consistent attributes. These attributes would have the same name, same data type, and refer to the same or similar objects. At a minimum, that would be:
* description: utf-8 encode string, a description of the atlas
* maps: string, path to the atlas file
* labels: list, string labels corresponding to each atlas label
* labels_index: list, int labels corresponding to each unique value in the atlas (or each index along the 4th dimension)

Other attributes are permissible, as is redundancy (for backwards compatibility), as long as these attributes are present. 

This is related to issues #930 (closed), #1489  and #1635 , and PR #1608

### CODE REVIEW

**Comment by illdopejake** [comment]
@GaelVaroquaux 
For 3D atlases, atlas.labels refers to integer labels making up a 3D atlas.
For 4D atlases, atlas.labels refers to indexes along the 4th dimension.

Since these would be applied totally differently, would it make sense to give them different names? E.g. "region_labels" and "network_labels" or something like that?

**Comment by GaelVaroquaux** [comment]
I agree with the principle but I am not convinced by the names proposed. "networks" is used in some atlases to denote a group of maps.

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by illdopejake** [comment]
> I agree with the principle but I am not convinced by the names proposed.

Yes good point. What about something like:

3D: atlas.labels, atlas.labels_index
4D: atlas.maps_labels, atlas.maps_index

**Comment by bthirion** [comment]
+1 for these terms.

**Comment by jeromedockes** [comment]
> description: utf-8 encode string, a description of the atlas

shouldn't the description be decoded for the user, ie provided as a unicode string?

**Comment by illdopejake** [comment]
I have no opinions on this one ;-). Was just going with what people seemed to agree on at #1635  

I'm about to push a few commits that I did on the plane, but it would be easy to go back and change this to whatever is agreed upon :-)

**Comment by bthirion** [comment]
Has been stalled for three years. Closing.

**Pull request closed without merging**
