### PR TITLE
[MAINT] Update `standardize` deprecated strategy in example gallery

### LINKED ISSUE #3719: Update examples to use "zscore_sample" `standardize` strategy
At the moment the "zscore" `standardize` strategy deprecation warning is saturating the [doc build logs](https://pipelines.actions.githubusercontent.com/serviceHosts/4e916657-41bc-43a2-a3ed-7be699b3544e/_apis/pipelines/1/runs/32526/signedlogcontent/2?urlExpires=2023-04-21T10%3A15%3A43.4242618Z&urlSigningMethod=HMACV1&urlSignature=bz0LusrMyseqRCOWfiKc2KBhuqdUn2CO4IzZrrkgtqs%3D). The examples should be updated to use the correct "zscore_sample" strategy

### PR DESCRIPTION
**Pull request by ymzayek**
Closes #3719 .

Changes proposed in this pull request:

- Update `standardize` deprecated strategy in example gallery from default "zscore" (or equivalent `True`) to "zscore_sample"

### CODE REVIEW

**Review by Remi-Gau — APPROVED** [review]
LGTM
re-ping me if there are some more you need to add.

**Review by bthirion — APPROVED** [review]
LGTM. Just curious: what is the impact on the experimental results of the examples ?

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks !

**Comment by ymzayek** [comment]
I checked a few examples from each module and nothing stands out to me in terms of the impact of changing the parameter value. You can have a look here: https://output.circle-artifacts.com/output/job/9c7b6e74-227c-475f-a154-991bf64dba8b/artifacts/0/dev/auto_examples/index.html

Unrelated to the changes to this PR: I noticed some suboptimal outputs in some examples so I will open a separate issue to track them

**Comment by bthirion** [comment]
ALl right. Merging, then.

**Pull request merged**
