### PR TITLE
[MRG] Fix:  Nilearn raises Nose ImportError with no MatPlotLib

### LINKED ISSUE #1846: Nilearn seems to need nose in certain (non-dev) cases
I created 2 new environments to run Nilearn code from pbellec's branch https://github.com/SIMEXP/nilearn
Env1:
```
conda install python=2 cython matplotlib jupyterlab scikit-learn
pip install -e .
```
Env2:
```
conda install python=2.7 scikit-learn=0.18
 pip install nibabel==2.0.2
conda install jupyterlab
 pip install -e .
```
Then I ran this code in Jupyter lab notebooks in both environment:
```
# one motor contrast map from NeuroVault
from nilearn import datasets
from nilearn.plotting import view_stat_map
motor_images = datasets.fetch_neurovault_motor_task()
view_stat_map(motor_images.images[0], cut_coords=[-4,-7,49], draw_cross=True,dim=0, opacity=0.5,
              colorbar=True, annotate=True, title="Motor Activation", resampling_interpolation='nearest', 
              threshold=2)
```
In Env2 but not Env1, I get the error:
image

I will test this in Nilearn master as well. Nilearn should not need to install nose libraries when using (not developing) Nilearn.
Neither of the envs have nose installed, but I am getting the error in only Env2, not 1.

### PR DESCRIPTION
**Pull request by kchawla-pi**
Fixes #1846

### CODE REVIEW

**Comment by kchawla-pi** [comment]
This is ready for review

**Comment by kchawla-pi** [comment]
Nowif MPL is missing, it raises Matploitib ImportError, as it should.

**Comment by GaelVaroquaux** [comment]
Great! Super useful!!

Maybe that's the milestone that we were waiting for to release nilearn
0.6?

**Comment by kchawla-pi** [comment]
I want to merge:
 - #2195 : Have asked Jerome a couple questions about it. Your feedback on https://github.com/nilearn/nilearn/pull/2195#discussion_r352484310 will help wrap this up.
-  #2235 . The latter doesn't need much work, I will do it on Wednesday if the contributor is unable to.

I wanted to merge the MetaEstimator one as well but now it can wait for the 0.7.x release

**Pull request merged**
