### PR TITLE
[MAINT] Remove trailing spaces and empty lines

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
- Remove trailing spaces at end of lines.
- Remove trailing empty lines at end of files.

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
Thx ! 
I simply  doubt that this should apply to json files ?

**Comment by DimitriPapadopoulos** [comment]
I don't know. Are they automatically regenerated on a regular basis?

**Comment by DimitriPapadopoulos** [comment]
Ah, answering to myself: [`nilearn/plotting/glass_brain_files/generate_json.sh`](https://github.com/nilearn/nilearn/blob/main/nilearn/plotting/glass_brain_files/generate_json.sh)

**Comment by DimitriPapadopoulos** [comment]
Ah, that's the default baheviour of `json.dump`, I'll try to fix the call to that function.

**Comment by DimitriPapadopoulos** [comment]
By the way, [`nilearn/plotting/glass_brain_files/svg_to_json_converter.py`](https://github.com/nilearn/nilearn/blob/main/nilearn/plotting/glass_brain_files/svg_to_json_converter.py) is still a Python 2 script.

**Comment by DimitriPapadopoulos** [comment]
Fixed the script and regenerated the JSON files.

**Review by NicolasGensollen — COMMENTED** [review]
Thanks for fixing these @DimitriPapadopoulos !
The changes look good to me. The codecov complaint you get makes me wonder why the script `nilearn/plotting/glass_brain_files/svg_to_json_converter.py` is not in here:

https://github.com/nilearn/nilearn/blob/cc99fa76df137e9ac6010c311e15fa9ac12ce66d/.coveragerc#L4-L10

**Comment by DimitriPapadopoulos** [comment]
I have added `nilearn/plotting/glass_brain_files/svg_to_json_converter.py` to `.coveragerc`.

**Comment by NicolasGensollen** [comment]
@DimitriPapadopoulos I'm still not sure to understand why we need to apply this to the JSON files.

**Comment by DimitriPapadopoulos** [comment]
More compact. Why have useless spaces at the end of JSON files?

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks!

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Comment by tsalo** [comment]
Before this is merged could you add a prefix to the PR name and fix the typo?

**Comment by DimitriPapadopoulos** [comment]
Done. This was not an LGTM alert by the way.

**Review by tsalo — APPROVED** [review]
Thanks! Everything looks good to me as well.

**Comment by NicolasGensollen** [comment]
Thanks! Merging then...

**Pull request merged**
