### PR TITLE
[MAINT] Set nilearn version input in bug issue template to text area

### LINKED ISSUE #3818: Change setting of bug issue template to require nilearn version as text
Issue template for bugs requires nilearn version from a dropdown menu. This is already out of date and since it has to be updated manually it is easy to forget. I suggest to make it a required text area instead

https://github.com/nilearn/nilearn/blob/3b0547377429b537ab788356e391103bbb8b2767/.github/ISSUE_TEMPLATE/bug.yml?plain=1#L59-L75

### PR DESCRIPTION
**Pull request by ymzayek**
Closes #3818 .

### CODE REVIEW

**Comment by bthirion** [comment]
I'm not sure how to check that the PR is OK.

**Comment by Remi-Gau** [comment]
Someone would need to merge the branch on their main and try to then open an issue on their fork using the bug template. Only way I know how to test for real.

**Comment by Remi-Gau** [comment]
Though the rendering of the yaml file on the github GUI is not bad either as a first approach.

https://github.com/nilearn/nilearn/blob/ede16427c2d5e325bfd5dbf984ad54474da1dc4b/.github/ISSUE_TEMPLATE/bug.yml

**Review by Remi-Gau — APPROVED** [review]

**Comment by ymzayek** [comment]
@bthirion you can check it on my fork here: https://github.com/ymzayek/nilearn/issues/new?assignees=&labels=Bug&projects=&template=bug.yml&title=%5BBUG%5D+

**Review by bthirion — APPROVED** [review]
LGTM. Just note that we'll have to update this menu on a regular basis.

**Comment by ymzayek** [comment]
> LGTM. Just note that we'll have to update this menu on a regular basis.

@bthirion hm this is to replace the dropdown list that is currently in place that we have to update regularly. The example text is a placeholder and just an example so the user has to type in the actual version themselves so we don't have to update the list. If it's not clear maybe I remove the placeholder?

**Pull request merged**
