### PR TITLE
[FIX] Use `maps` key for API consistency and improve deprecation for new behavior of some atlas fetchers

### LINKED ISSUE #3983: atlas fetchers return inconsistency
Minor API detail but I ran across a user who was confused by this.

Several fetchers seem to return dictionary-like object with a `map` key instead of `maps` like our doc suggest they should: https://nilearn.github.io/stable/development.html#additional-cases

May be a good thing to keep it consistent.

- fetch_atlas_craddock_2012
- fetch_atlas_smith_2009
- fetch_atlas_basc_multiscale_2015

### PR DESCRIPTION
**Pull request by ymzayek**
- Closes #3983

### CODE REVIEW

**Review by Remi-Gau — APPROVED** [review]
Looks great!! Thanks @ymzayek for this.

**Comment by Remi-Gau** [comment]
Do you think we should update the doc (in a separate PR) to say that some functions 'fetch_coords*' return not maps but `rois`?

https://github.com/nilearn/nilearn/blob/ecf7686740f236274be94fe8a0757808e366debc/nilearn/datasets/atlas.py#L1624

Currently our doc mentions only fetch_atlas.

**Comment by bthirion** [comment]
Maybe add a brief whatsnew entry ?

**Comment by ymzayek** [comment]
> Do you think we should update the doc (in a separate PR) to say that some functions 'fetch_coords*' return not maps but `rois`?
> 
> https://github.com/nilearn/nilearn/blob/ecf7686740f236274be94fe8a0757808e366debc/nilearn/datasets/atlas.py#L1624
> 
> Currently our doc mentions only fetch_atlas.

Sure but where exactly? I might be wrong but other than the API reference we only talk about the fetch_atlas function return here: https://nilearn.github.io/stable/development.html#how-to-contribute-an-atlas

If we were to add your suggestion maybe we could think about adding a section on fetchers in https://nilearn.github.io/stable/manipulating_images/input_output.html#input-and-output-neuroimaging-data-representation or another appropriate area in the user guide.

Let me know if you had a different idea.

**Comment by Remi-Gau** [comment]
> Sure but where exactly? I might be wrong but other than the API reference we only talk about the fetch_atlas function return here: https://nilearn.github.io/stable/development.html#how-to-contribute-an-atlas

next to this section was what I had in mind

**Comment by ymzayek** [comment]
Perhaps we should open a separate issue to discuss further

> next to this section was what I had in mind

Ok the idea is to explain about contributing such fetchers? 

> Do you think we should update the doc (in a separate PR) to say that some functions 'fetch_coords*' return not maps but rois?

I agree with this but I understood it as more of a usage thing rather than relating to contributing. Sorry if I'm misunderstanding!

**Comment by Remi-Gau** [comment]
> we should open a separate issue to discuss further

yeah we were getting side tracked.

done.

**Comment by ymzayek** [comment]
Thanks merging

**Pull request merged**
