### PR TITLE
Enh/surface path globbing

### PR DESCRIPTION
**Pull request by juhuntenburg**
Enables and tests globbing in load_surf_mesh and load_surf_data (#1989)

- For load_surf_data, if several files are given they are concatenated and returned as a 2D array

- For load_surf_mesh, only one file at a time can be loaded, if globbing returns several files an error occurs

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Oh no. Conflicts :(

**Comment by juhuntenburg** [comment]
Solved, hopefully along with the test failure

**Comment by kchawla-pi** [comment]
Cancellling the other tests.

**Comment by GaelVaroquaux** [comment]
LGTM. Merging! Thanks!!

**Pull request merged**
