### PR TITLE
Bumped up the minimum versions of scikit-learn, scipy to 0.19, mpl to 2.0

### PR DESCRIPTION
**Pull request by kchawla-pi**
#2077
 - Conda default channel dropped support for these versions.
 - Updated Whats_new.rst

### CODE REVIEW

**Comment by jeromedockes** [comment]
why is it necessary to change the minimum supported version of scikit-learn scipy and matplotlib?
users who installed these libraries a while ago might still have those versions, and they can be installed with pip

**Comment by jeromedockes** [comment]
for example scikit-learn still supports scipy 0.17; why does nilearn need 0.19?

**Comment by kchawla-pi** [comment]
We will have to replace conda with pip in all our CIs. Or switch to
conda-forge channel, if it supports the older versions.

I'm fine with either of those scenarios if Gael is.

There's also the consideration that we move to even newer minimum versions
of that helps us address the warnings.

**Comment by jeromedockes** [comment]
how does scikit-learn deal with scipy 0.17?

**Comment by kchawla-pi** [comment]
Does their master branch support Scipy0.17? This change in conda happened
last week for us.

**Comment by jeromedockes** [comment]
ok thanks, I didn't realize this was so recent

**Comment by kchawla-pi** [comment]
@jeromedockes Did you merge this? :smile: 

> how does scikit-learn deal with scipy 0.17?

They pinned conda==4.6, that was also their solution for #2079 

@glemaitre What has SKL been doing for this? Are you still pinned to conda==4.6? Plans going forward?

**Comment by jeromedockes** [comment]
> @jeromedockes Did you merge this? smile

No

**Comment by kchawla-pi** [comment]
Uh, I merged this. I had forgotten. Bah.

**Comment by kchawla-pi** [comment]
@jeromedockes It seems to me scikit-learn uses apt for most of their dependency installation in most of their CI runs, or they use pip. They test conda compatibility in a couple CI runs but not with their minimum supported versions.

**Comment by jeromedockes** [comment]
could we use pip in some runs? that would be good regardless of scipy version

**Comment by kchawla-pi** [comment]
That was one of the options presented to Gael, and he didn't take it.
Personally, I think most people using Python for data analytics gravitate towards using Anaconda across platforms.

**Pull request merged**
