### PR TITLE
Revert "Fix for  Masker family reloaded: NiftiSpheresMasker silently ignores voxels"

### PR DESCRIPTION
**Pull request by kchawla-pi**
Reverts nilearn/nilearn#1906
The PR merged before (#1869( this is failing in CircleCI. I am reverting this and that one to forestall any potential (un)merge conflicts, and then will remerge this.

### CODE REVIEW

**Comment by himanshupathak21061998** [comment]
@kchawla-pi  What are cause of failure of circle-ci

**Comment by KamalakerDadi** [comment]
I don't understand the concept of reverting. As this can also be seen from circleci log.

```python
Could not load words from file /home/kamalakar/nilearn_data/neurovault/collection_2696/neurosynth_words_for_image_51643.json; error: Traceback (most recent call last):
  File "nilearn/datasets/neurovault.py", line 1251, in neurosynth_words_vectorized
    with open(file_name, 'rb') as word_file:
IOError: [Errno 2] No such file or directory: '/home/kamalakar/nilearn_data/neurovault/collection_2696/neurosynth_words_for_image_51643.json'

Could not load words from file /home/kamalakar/nilearn_data/neurovault/collection_2696/neurosynth_words_for_image_51645.json; error: Traceback (most recent call last):
  File "nilearn/datasets/neurovault.py", line 1251, in neurosynth_words_vectorized
    with open(file_name, 'rb') as word_file:
IOError: [Errno 2] No such file or directory: '/home/kamalakar/nilearn_data/neurovault/collection_2696/neurosynth_words_for_image_51645.json'

Could not load words from file /home/kamalakar/nilearn_data/neurovault/collection_2696/neurosynth_words_for_image_51647.json; error: Traceback (most recent call last):
  File "nilearn/datasets/neurovault.py", line 1251, in neurosynth_words_vectorized
    with open(file_name, 'rb') as word_file:
IOError: [Errno 2] No such file or directory: '/home/kamalakar/nilearn_data/neurovault/collection_2696/neurosynth_words_for_image_51647.json'

Could not load words from file /home/kamalakar/nilearn_data/neurovault/collection_2696/neurosynth_words_for_image_51649.json; error: Traceback (most recent call last):
  File "nilearn/datasets/neurovault.py", line 1251, in neurosynth_words_vectorized
    with open(file_name, 'rb') as word_file:
IOError: [Errno 2] No such file or directory: '/home/kamalakar/nilearn_data/neurovault/collection_2696/neurosynth_words_for_image_51649.json'

nilearn/datasets/neurovault.py:1263: UserWarning: No word weight could be loaded, vectorizing Neurosynth words failed.
  warnings.warn('No word weight could be loaded, '
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/kamalakar/Kamalakar/work/nilearn/examples/05_advanced/plot_ica_neurovault.py in <module>()
     47 
     48 # Clean and report term scores
---> 49 term_weights[term_weights < 0] = 0
     50 total_scores = np.mean(term_weights, axis=0)
     51 

TypeError: 'NoneType' object does not support item assignment

```

**Comment by kchawla-pi** [comment]
@KamalakerDadi I might have done a knee-jerk reaction to this. I originally thought the failure was introduced in the merge of #1869 . I decided to revert the last 2 PRs I merged and then re-merge this one.

**Comment by kchawla-pi** [comment]
@KamalakerDadi I was going to revert #1869 next, and then diagnose. What do you suggest?
I decided to rerun the originally green circleci build on tht one to see if the error is there as well. Should have done that to begin with. Brain fart I suppose.

**Comment by KamalakerDadi** [comment]
I would suggest to wait for Neurosynth to come back. For instance, try to open this http://neurosynth.org/

Please make an issue on neurosynth github to ask the status on this.

**Pull request closed without merging**
