### PR TITLE
Fix off by one in reorder_img

### PR DESCRIPTION
**Pull request by cancan101**
Closes https://github.com/nilearn/nilearn/issues/1589

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
I agree with the fix, thanks!

However I find that the test is a bit circular: it does not test that the image actually point to the same space. Getting the test right requires not making the error that we made. 

I suggest adding a test using nilearn.inage.coord_transform that checks that the min and max of the brain-space coordinates map to the values. 

By the way, in the test, you could make the image much smaller, to speed things up.

**Comment by cancan101** [comment]
I'm not sure I follow what's wrong with the test as it's a copy and paste of the issue ticket. Also does the size matter? I didn't test speed but I assumed numpy just creates view for operation. I suppose initial allocation will be a bit faster.

**Comment by GaelVaroquaux** [comment]
> I'm not sure I follow what's wrong with the test as it's a copy and paste of the issue ticket.

For me, what we really want to ensure is that the coordinates map to the
same points before and after. In this respect the test is a bit indirect.

> Also does the size matter?

Size matters :).

> I didn't test speed but I assumed numpy just creates view for
> operation. I suppose initial allocation will be a bit faster.

Yes, it's not going to make a huge difference, but it's good practice.

**Comment by bthirion** [comment]
I don't understand the travis failure. Should be restarted later I think.

**Comment by KamalakerDadi** [comment]
>I don't understand the travis failure. Should be restarted later I think.

Travis failure is related to doc tests failures related to NumPy 1.14. Should be fixed temporarily with this PR #1592 .

**Comment by cancan101** [comment]
so is this PR good?

**Comment by GaelVaroquaux** [comment]
Sorry, I hadn't seen the change.

Yes, the PR looks great now. Thanks a lot. I like a lot the new test logic. I am merging this.

**Pull request merged**
