### PR TITLE
[MAINT] use UV to install in CI

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes none but relates to #4628 #4663

Changes proposed in this pull request:

- use uv to run "pip install" in CI: https://docs.astral.sh/uv/
- allows to shave of precious time in CI
- unrelated: simplify the names of the tox "environments"

### CODE REVIEW

**Comment by bthirion** [comment]
What is the expected benefit of using uv ?

**Comment by Remi-Gau** [comment]
> What is the expected benefit of using uv ?

SPEEED... and saving a lot of time in CI:

try it locally

## with pip

```bash
$ time pip install --no-cache-dir -e .[dev]

...

41,50s user 5,17s system 65% cpu 1:10,94 total
```

## with uv

```bash
$ pip install uv
$ uv tool install --no-cache-dir -e '.[dev]'

...
7,80s user 5,53s system 62% cpu 21,200 total
```

It's a >30 seconds difference but given we install nilearn for every PR:
- 3 times per doc build
- 18 per test run

this starts to add up.

FYI this does not constrain in terms of build and will not make a difference for users.

**Review by man-shu — APPROVED** [review]
I'm all for speeeeeed. It's just because of Rust right?

**Comment by Remi-Gau** [comment]
> It's just because of Rust right?

yup

**Comment by bthirion** [comment]
Why doesn't the doc build ?

**Review by bthirion — APPROVED** [review]

**Comment by Remi-Gau** [comment]
> Why doesn't the doc build ?

I think that the PR deploy on circle CI will only happen if the whole Doc workflow passes (including link checks).

Given how brittle this latter one is I am more and more tempted to say that linkcheks should be run less often (just on main?).

**Comment by bthirion** [comment]
But we need to check them *because* they're brittle...

**Comment by Remi-Gau** [comment]
hmm some failures in main seem to happen on the doc build and nightly workflow after merging this one so I will revert this one and rework it

**Pull request merged**
