### PR TITLE
Adding info to fetch_haxby dataset fetcher

### PR DESCRIPTION
**Pull request by eickenberg**
Addresses #347

### CODE REVIEW

**Comment by AlexandreAbraham** [comment]
If I remember well, all scans in subject 5 are marked as "resting state" because the data is crap for this subject.

**Comment by eickenberg** [comment]
Subject 5 task labels are distributed normally as far as I can see.

**Comment by eickenberg** [comment]
Actually, no, there seems to be a slight irregularity in one of the runs or something

**Comment by eickenberg** [comment]
Yes, Subject 5, chunk 8 is fully labelled as "rest" (121 data points, instead of the usual 49 rest + 8 * 9 task)

**Pull request merged**
