### PR TITLE
[DOC] add links and edit buttons to doc

### PR DESCRIPTION
**Pull request by Remi-Gau**
closes none

- add an edit button to the doc
- add links to github repo and twitter in the footer

Screenshot from 2023-09-11 22-51-23

Screenshot from 2023-09-11 22-51-09

### CODE REVIEW

**Comment by bthirion** [comment]
Nice ! 
Looks like it broke the CI...

**Comment by ymzayek** [comment]
We can also add mastodon https://fosstodon.org/@nilearn and discord too.

The edit button will allow anyone to edit and directly commit to main? I'd prefer to always go through PRs if it's possible

**Comment by ymzayek** [comment]
Failures seem unrelated; see main. I'll open a PR to fix

**Comment by Remi-Gau** [comment]
> We can also add mastodon https://fosstodon.org/@nilearn and discord too.

Good idea. Will add those.

> The edit button will allow anyone to edit and directly commit to main? I'd prefer to always go through PRs if it's possible

Technically the edit button is always there on the github interface, so we already have this problem. This edit button makes just easier to know what doc page cooresponds to what github document.

If we set up our branch protection rules properly, this "commit to main" should be avoidable.

Here is what it looks like on the BIDS specification.

image

And on another repo where I set the rules so no direct commit to the default branch is possible.

image

On our side we get no such warning.

**Comment by ymzayek** [comment]
> Technically the edit button is always there on the github interface, so we already have this problem. This edit button makes just > easier to know what doc page cooresponds to what github document.

Ok I misunderstood the intention so thanks for clarifying.

> If we set up our branch protection rules properly, this "commit to main" should be avoidable.

Indeed

**Comment by Remi-Gau** [comment]
> We can also add mastodon https://fosstodon.org/@nilearn and discord too.

what it would look like

image

**Comment by ymzayek** [comment]
it would be checking this option then for rules on main branch?

image

**Comment by Remi-Gau** [comment]
> it would be checking this option then for rules on main branch?
> 
> image

Yes and this one if you want it to apply to people with admin access (because mistakes happen... 😉 )

image

**Comment by Remi-Gau** [comment]
by the way I think we can also have twitter, discord and mastodon badge in the top of the readme

**Comment by Remi-Gau** [comment]
> > Yes and this one if you want it to apply to people with admin access (because mistakes happen... 😉 )
> 
> Done

Confirmed by me trying to do a manual edit. 

Thanks!!

**Comment by ymzayek** [comment]
Looks good! Can you rebase on main?

**Comment by Remi-Gau** [comment]
> Looks good! Can you rebase on main?

Avec plaisir.

**Review by ymzayek — APPROVED** [review]

**Pull request merged**
