### PR TITLE
[MRG] In a py2 environment, Nilearn raises a DeprecationWarning once on import

### PR DESCRIPTION
**Pull request by kchawla-pi**
For #1696 
 - Added tests [INCOMPLETE].

### CODE REVIEW

**Comment by kchawla-pi** [comment]
@GaelVaroquaux take a look at this as well. Have commented out the second test, not sure yet why it is not working.

**Comment by kchawla-pi** [comment]
This failure is due to absence of the six library which I have used.

**Comment by GaelVaroquaux** [comment]
We don't require six. You need to use sklearn.externals.six.

**Comment by kchawla-pi** [comment]
I have used distutils.version.LooseVersion . That okay or should I switch to what you said?

**Comment by GaelVaroquaux** [comment]
> I have used distutils.version.LooseVersion

It's even better than my suggestion.

**Comment by kchawla-pi** [comment]
@GaelVaroquaux Lets merge this one before someone sneezes too hard and the test fails.

**Comment by kchawla-pi** [comment]
Can we do incorporate that in a new PR? I can submit the new one right away.
I need the fixes in this PR for my other PRs and pushing a change on this will delay them by another 2 hrs.

**Comment by GaelVaroquaux** [comment]
OK. Look forward to your other PR.

**Pull request merged**
