### PR TITLE
MultiPCA: simplify mask computation

### LINKED ISSUE #194: Spaghetti code in MultiPCA
The way the code in MultiPCA uses the given masker to compute a mask, but not to load the time series (ie not the 'transform' method of the masker) is both confusing for the user (parameters such as smoothing are not taken in account) and leads to spaghetti code. This needs to be rethought.

### PR DESCRIPTION
**Pull request by banilo**
tries to fix #194

### CODE REVIEW

**Comment by banilo** [comment]
No comments on this one?

**Comment by bthirion** [comment]
I do get an error with unittests:
======================================================================
ERROR: nilearn.decomposition.tests.test_multi_pca.test_multi_pca
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/bertrand/mygit/nilearn/nilearn/decomposition/tests/test_multi_pca.py", line 50, in test_multi_pca
    multi_pca.fit(data[:2])
  File "/home/bertrand/mygit/nilearn/nilearn/decomposition/multi_pca.py", line 224, in fit
    preset_mask_img = self.mask.mask_img_
AttributeError: 'MultiNiftiMasker' object has no attribute 'mask_img_'

**Comment by GaelVaroquaux** [comment]
Indeed, tests fail on travis.

**Comment by bcipolli** [comment]
Just a note, there's also no test case for when the mask is computed, so there's limited code coverage of this PR.  I tried making a simple one, but the mask computation was failing...

**Comment by AlexandreAbraham** [comment]
Closing this one as we don't want to silent parameter overriding.

**Pull request closed without merging**
