### PR TITLE
Download zipped version of the ICBM templates

### LINKED ISSUE #1791: Ship compressed versions of the ICBM altases
The ICM atlases that we ship are not compressed. As a result, they use a total of 136Mb on a download (eg circleCI). We should reship them using OSF, after a "gzip -9", this drops the disk usage to 61Mb.

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
They take less space on the disk. This should help CircleCI.

Fixes #1791

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Build failed, but the failure has nothing to do with this PR. Merging.

**Comment by kchawla-pi** [comment]
Feels like juggling dynamite, so many merges despite the failures. I am glad we are not doing anything until we fix the CIs and double check the generated examples.

**Comment by KamalakerDadi** [comment]
Everything is good upto now. You can view from the below link a clean build. This is what we have with master.

https://github.com/nilearn/nilearn/commits/master

**Comment by KamalakerDadi** [comment]
Kudos to @GaelVaroquaux

**Comment by kchawla-pi** [comment]
Yeah :+1:

**Pull request merged**
