### PR TITLE
Lighting surf plot

### PR DESCRIPTION
**Pull request by jeromedockes**
plotly defaults for lighting of the surface plots actually look better than those we use in my opinion; main difference is more ambient light (shadows are not so dark) and no reflection (surface is more rough, less shiny, no bright spots)

### CODE REVIEW

**Comment by jeromedockes** [comment]
newplot 1
newplot

**Comment by GaelVaroquaux** [comment]
Looks great!

Maybe a note in the whats_new? I can see users being surprised at the difference between two versions.

**Comment by GaelVaroquaux** [comment]
LGTM. Merging.

**Comment by kchawla-pi** [comment]
Cool.
I was waiting for the CircleCI run from the previous merge to complete before merging this one.

**Pull request merged**
