### PR TITLE
[FIX] Write out full signature for multi-subject maskers

### PR DESCRIPTION
**Pull request by ymzayek**
Partially addresses #3384 and resolves scikit-learn compatibility error: https://app.circleci.com/pipelines/github/nilearn/nilearn/5017/workflows/0899df21-383c-45ae-807a-f31f734907e8/jobs/10386

### CODE REVIEW

**Comment by bthirion** [comment]
LGTM so far.

**Review by jeromedockes — APPROVED** [review]
thanks!

**Comment by ymzayek** [comment]
I think this is ready to merge. CircleCI would have failed around 40m otherwise

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Pull request merged**
