### PR TITLE
[MAINT] Sequence value overwritten unconditionally

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
- From #2723.

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
There is no smoke test for these lines ?

**Comment by Remi-Gau** [comment]
> There is no smoke test for these lines ?

I think those lines should be covered: https://github.com/nilearn/nilearn/blob/d73672d41992659395c401fbc08e876708aa78ce/nilearn/datasets/tests/test_atlas.py#L204

**Review by Remi-Gau — APPROVED** [review]

**Comment by Remi-Gau** [comment]
I think this is because the data we mock do not have names that match some of the 'idiosyncrasies' of the real data.

**Comment by DimitriPapadopoulos** [comment]
I'm not very familiar with the Jülich atlas names, i'll try to find one that exposes this issue.

**Review by bthirion — APPROVED** [review]

**Pull request merged**
