### PR TITLE
[MRG] DOC: don't download NYU in examples

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Use ADHD instead. The rational is to have less different data sources, in
order to have less stress on the download when building the docs.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Let's see what circleci gives on that PR.

**Comment by bthirion** [comment]
Circle ci is green. 
Could you update l.17 in plot_rest_clustering.py and l.23 in plot_ica_resting_state.py ?
Then, it should be good to merge.

**Comment by GaelVaroquaux** [comment]
> Could you update l.17 in plot_rest_clustering.py and l.23 in
> plot_ica_resting_state.py ?

Indeed! I have updated. Thanks.

> Then, it should be good to merge.

I'll merge once CircleCI has finished running the commit with the
symlinks.

**Comment by GaelVaroquaux** [comment]
I've addressed @bthirion 's comments, but this broke the parts of the narrative documentation that was link to these comments. So I also rewrote it.

Merging now. Cheers.

**Pull request merged**
