### PR TITLE
[MAINT] update DOI and add RRID

### LINKED ISSUE #4088: [DOC] Nilearn RRID should be mentioned in the doc
did not know but Nilearn has an RRID: we should probably make it more obvious

https://scicrunch.org/resources/data/record/nlx_144509-1/SCR_001362/resolver?q=nilearn&l=nilearn&i=rrid:scr_001362

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes #4088 

Changes proposed in this pull request:

- add new DOI to citation.cff
- add DOI in readme
- update how to cite section
- mention RRID

### CODE REVIEW

**Comment by ymzayek** [comment]
This sections might also need to be updated depenging on what we decide: https://nilearn.github.io/stable/authors.html#citing-nilearn

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Review by ymzayek — APPROVED** [review]
Looks great thanks!

**Comment by Remi-Gau** [comment]
Looks like I messed up the badge in the readme, no?

**Comment by ymzayek** [comment]
Ah yup just needs svg at the end I think. Want me to take care of it?

**Comment by Remi-Gau** [comment]
Would you mind?

**Comment by Remi-Gau** [comment]
Was thinking of using **kwargs

Do we have a policy on this?

**Comment by Remi-Gau** [comment]
Was thinking of using **kwargs

Do we have a policy on this?

**Comment by ymzayek** [comment]
> Would you mind?

No problem

**Pull request merged**
