### PR TITLE
TST: Ignore tests in CodeCov config

### LINKED ISSUE #2458: Ignore test directories in codecov configuration
It looks like CodeCov is currently indexing all testing files, as well as version.py and conftest.py. I think the goal is to evaluate coverage of the functional code in the library, so including testing files is inflating coverage estimates.

I can incorporate this into #2455 if folks are happy with it.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #2458.

Changes proposed in this pull request:

- Ignore testing related folders and files in CodeCov config file.

### CODE REVIEW

**Comment by jeromedockes** [comment]
Thanks! I am thinking that this should go in `.coveragerc` ? otherwise we will have a discrepancy between reports from codecov and local tests.

**Comment by bthirion** [comment]
Travis failure is unrelated. Hence I'm going to merge.

**Comment by jeromedockes** [comment]
@bthirion my comment on adding this to .coveragerc has not been answered though

**Comment by tsalo** [comment]
@jeromedockes I can open another PR for .coveragerc?

**Comment by jeromedockes** [comment]
> @jeromedockes I can open another PR for .coveragerc?

that would be great, thank you!

**Comment by tsalo** [comment]
I just opened #2473.

**Comment by jeromedockes** [comment]
> I just opened #2473.

thank you!

**Pull request merged**
