### PR TITLE
[MAINT] Format nilearn/interfaces: apply isort and fix flake8 errors

### PR DESCRIPTION
**Pull request by Remi-Gau**
Relates to https://github.com/nilearn/nilearn/issues/2528

Changes proposed in this pull request:

- [x] run isort
- [x] run pyupgrade
- [x] run flynt
- [x] fix remaining flake8 issues
- [x] update flake8 / isort CI

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@htwangtw 

this PR aims to just sort imports and enforce pep8, so hopefully the impact on your PR #3285 should be minimal: well except for the fact that you will have to keep flake8 happy when working on `nilearn/interface` once this is merged. :-p

**Review by ymzayek — APPROVED** [review]
LGTM thx!

**Review by bthirion — APPROVED** [review]
LGTM too.

**Comment by Remi-Gau** [comment]
Will merge if CI is green after a rebase once #3649 is done.

**Comment by Remi-Gau** [comment]
merging this one too
thanks @ymzayek and @bthirion

**Pull request merged**
