### PR TITLE
Upgrade to Circleci2.0

### LINKED ISSUE #1676: Upgrading CircleCI to v2.0 before Aug 31.
See PR #1733 

Circle CI 1.0 is being EOL'd on Aug 31. Many people may not be around in Aug, indicating we should do the upgrade in July. Thoughts?

### PR DESCRIPTION
**Pull request by kchawla-pi**
Will fix #1676 

I will be closing the other PRs created to address this issue. #1679 #1687

### CODE REVIEW

**Comment by kchawla-pi** [comment]
The latest push has 2 problems:

1. At many places I get the error:
`ValueError: Found input variables with inconsistent numbers of samples: [1452, 864]`

2. The test seems to stall. The point at which it stalls has changed.
Currently stuck on:
`Executing file /home/circleci/project/examples/02_decoding/plot_haxby_space_net.py`

**Comment by kchawla-pi** [comment]
Stalls at:
```
Executing file /home/circleci/project/examples/02_decoding/plot_haxby_space_net.py
[NiftiMasker.fit] Loading data from Nifti1Image(
shape=(40, 64, 64, 126),
affine=array([[  -3.5  ,    0.   ,    0.   ,   68.25 ],
       [   0.   ,    3.75 ,    0.   , -118.125],
       [   0.   ,    0.   ,    3.75 , -118.125],
       [
[NiftiMasker.fit] Computing the mask
```
Ideas?

**Comment by kchawla-pi** [comment]
I SSH'd into the container and strangely, the environment `testenv` is empty andthe path to conda is not in the .bashrc file.
After deactivating `testenv` (packages are installed in root env, not testenv) and adding conda path to env-variable, I ran the `plot_haxby_space_net.py`

This is the message right after where the build gets stuck:
/home/circleci/miniconda3/lib/python3.5/site-packages/nilearn/_utils/cache_mixin.py:291: UserWarning: memory_level is currently set to 0 but a Memory object has been provided. Setting memory_level to 1.
  warnings.warn("memory_level is currently set to 0 but "

**Comment by bthirion** [comment]
Looks like your issues were mostly related to data access.
@lesteve any insight on these issues ?

**Comment by kchawla-pi** [comment]
> Looks like your issues were mostly related to data access.
How?

**Comment by lesteve** [comment]
I would strongly recommend you put the install logic in a single bash script and call it in your .circle/config.yml:

On top of improving readability of the config.yml files, this is more appropriate for this reason noted [here](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-step):

> Note: Since every run step is a new shell, environment variables are not shared across steps. If you need an environment variable to be accessible in more than one step, export the value using BASH_ENV

This is why for example you are seeing that packages are installed in the "base" (aka root) environment and not `testenv`.

**Comment by bthirion** [comment]
This is really weird: condition_mask is applied to both `conditions` and `fmri_masked` but in the latter case, it looks like no masking is applied. I can't reproduce it.

**Comment by kchawla-pi** [comment]
@bthirion 
I had encountered
 `ValueError: Found input variables with inconsistent numbers of samples: [1452, 216]`
earlier, during the model_selection PR. I couldn't remember the details I had used to figure it out last time.
I think I remember this problem occurring in the terminal but not a jupyter notebook. I'll investgate with that perspective.

**Comment by kchawla-pi** [comment]
Seems the stall that was being experienced has been resolved (or has moved way down in the chain of event)

**Comment by kchawla-pi** [comment]
OK this time, this is the failure point:
```
Executing file /home/circleci/project/examples/04_manipulating_images/plot_mask_computation.pyMakefile:155: recipe for target 'check' failed
make[1]: *** [check] Killed
```
(its not red here cuz the ssh session is open).

**Comment by kchawla-pi** [comment]
WHen I rebuild CircleCI it stalls at `examples/02_decoding/plot_haxby_space_net.py`.
When I rebuild CircleCI with SSH suport, it fails at `examples/04_manipulating_images/plot_mask_computation.py` with the message:
```
Makefile:155: recipe for target 'check' failed
make[1]: *** [check] Killed
```

**Comment by kchawla-pi** [comment]
Based on my observations in issue #1736, once the currently running build fails or stalls, I will test CircleCI building with py3.6

**Comment by jeromedockes** [comment]
neurosynth api seems to be down which is why plot_ica_neurovault example is failing

**Comment by KamalakerDadi** [comment]
>neurosynth api seems to be down which is why plot_ica_neurovault example is failing

I opened an issue regarding Neurosynth. See https://github.com/neurosynth/neurosynth/issues/80

**Comment by kchawla-pi** [comment]
@KamalakerDadi @jeromedockes 
Thanks.
Shouldn't that issue affect CircleCI1.0 based build as well? Why are they green?

**Comment by kchawla-pi** [comment]
@KamalakerDadi @jeromedockes 
Woot Woot! Thanks!

**Comment by kchawla-pi** [comment]
@lesteve Thanks for the info you gave. That was very helpful.

**Comment by kchawla-pi** [comment]
@KamalakerDadi I think there's a way to parallelize the testing without having to build custom docker containers. Will work on that once I return.

**Comment by kchawla-pi** [comment]
@GaelVaroquaux I believe if we want to move to CircleCI2.0, the minimum sufficient work is complete.
The build times are 1hr52min with CircleCI1.0 and 2hr22min with CircleCI2.0. I don't why the big difference.
The thumb twiddling after every push is rather wasteful and I have been looking at ways to speed this up.

I will configure 2 jobs.
 - Job 1 will run at every push on a custom docker image with all the build requirements preinstalled, and parallelized across 4 containers.
- Job 2 will run nightly and will essentially be the current config, creating a new environment once a day to ensure there are no breaks in the pipelines or package incompatibilities.

**Comment by KamalakerDadi** [comment]
+1 for merge and making advancements/improvements (in particular parallelization) in subsequent PRs.

**Comment by bthirion** [comment]
Merging, thx.

**Comment by GaelVaroquaux** [comment]
Great job Ksitish! This was important and difficult!!

**Comment by kchawla-pi** [comment]
Thanks!

**Pull request merged**
