### PR TITLE
[MAINT] Format nilearn/maskers: apply isort and fix flake8 errors

### PR DESCRIPTION
**Pull request by Remi-Gau**
Relates to https://github.com/nilearn/nilearn/issues/2528

Changes proposed in this pull request:

- [x] run isort
- [x] run pyupgrade
- [x] run flynt
- [x] fix remaining flake8 issues
- [x] update flake8 / isort CI

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
LGTM so far.

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks @Remi-Gau !

**Review by ymzayek — APPROVED** [review]
Thx @Remi-Gau !

**Comment by Remi-Gau** [comment]
merging
thanks for the review everyone

**Pull request merged**
