### PR TITLE
[INFRA] Fix typo in CI job name

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
-

### CODE REVIEW

**Review by NicolasGensollen — COMMENTED** [review]
LGTM so far.
Please undraft when it's ready.

**Comment by DimitriPapadopoulos** [comment]
I wasn't certain this name is not used elsewhere. Seem OK though.

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks! (failure on Azure isn't related)

**Review by bthirion — APPROVED** [review]
Thx !

**Comment by NicolasGensollen** [comment]
Thanks! Merging...

**Pull request merged**
