### PR TITLE
connectome-plot-bugfix

### LINKED ISSUE #479: connectome_plotter fails with nan's in adjacency matrix
returns ''ValueError: 'adjacency_matrix' should be symmetric''

### PR DESCRIPTION
**Pull request by banilo**
tries to fix #479

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Failing tests

**Comment by lesteve** [comment]
Also can you rebase on master so we get the coverage and the python 3 support?

**Comment by GaelVaroquaux** [comment]
LGTM. Thanks.

**Comment by lesteve** [comment]
Could you add a smoke test too, an adjacency_matrix like:

```
np.array([
    [1., np.nan, 0.],
    [np.nan, 1., 0.],
    [np.nan, 0., 1.]])
```

should be fine.

**Comment by banilo** [comment]
I added the nan-test. Your suggestion however would be a test for lacking symmetry :-P

**Comment by lesteve** [comment]
> Your suggestion however would be a test for lacking symmetry :-P

That was on purpose, since this is a edge case we happen to be supporting...

**Comment by banilo** [comment]
It does give a not-symmetric error. Is that intended?

2015-03-11 16:38 GMT+01:00 Loïc Estève <notifications@github.com>:

> Your suggestion however would be a test for lacking symmetry :-P
>
> That was on purpose, since this is a edge case we happen to be
> supporting...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/pull/491#issuecomment-78288309>.
>



-- 
Viele Grüße,
Danilo

**Comment by lesteve** [comment]
> It does give a not-symmetric error. Is that intended? 

:confused: I was naively expecting that the nan_to_num conversion would make the adjacency matrix symmetrix.

**Pull request merged**
