### PR TITLE
Fix: Nibabel version to 2.3.2 glitches during Six import in Py2 env

### PR DESCRIPTION
**Pull request by kchawla-pi**
For fixing the issue encountered by #1892 & tracked in #1900 .
Fixed Nibabel version to 2.3.1 in TravisCI in Py2 env

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
The nibabel is busy releasing a new version of nibabel that should fix
the problem. Maybe we should hold off a few days?

**Comment by kchawla-pi** [comment]
I'll defer to you. I pushed this cuz the PR #1892  will be stuck until the next release, and I wanted the PR's momentum to continue. Is there a release date?

**Comment by KamalakerDadi** [comment]
>The nibabel is busy releasing a new version of nibabel that should fix the problem. Maybe we should hold off a few days?

+1

**Comment by effigies** [comment]
2.3.3 is released. Can you check that it resolves your issues?

**Comment by kchawla-pi** [comment]
On it.

**Comment by kchawla-pi** [comment]
Fixed in Nibabel 2.3.3. Closing.

**Pull request closed without merging**
