### PR TITLE
restore from any miniconda3 + nilearn_data cache

### PR DESCRIPTION
**Pull request by jeromedockes**
if one that matches this week's number and the "packages-cache-timestamp" is not
available.

### CODE REVIEW

**Comment by kchawla-pi** [comment]
I'll review this tomrrow morning!

**Comment by jeromedockes** [comment]
> I'll review this tomrrow morning!

thank you!

**Comment by kchawla-pi** [comment]
Your changes are sound.
+1

**Comment by jeromedockes** [comment]
thanks for checking this! I have integrated these changes in #2436

**Pull request closed without merging**
