### PR TITLE
ENH: Glass backview

### PR DESCRIPTION
**Pull request by kingjr**
closes https://github.com/nilearn/nilearn/issues/1485.

* The cortical outskirt is identical to the front view
* I changed the sulci and cerebellum using combination of  'nilearn/plotting/glass_brain_files/plot_align.svg' and the [following 3D rendering](https://www.nature.com/articles/srep43293?ncid=txtlnkusaolp00000618)
* I ran the json converter locally
* I changed the default 'y' direction to use the back view. 

Here is how it looks:
back2
back
back3

A subsequent PR could be made to have the option of using a mirror view which would make use of the front view, but this would require additional plotting parameters, and a bottom view.

### CODE REVIEW

**Comment by bthirion** [comment]
Thx. I see 2 things in this PR:
* A fix of the inconsistency between brain anatomical projection and 'L' and 'R' tags
* A change of the default 'y' view fom front to back
While the first point is to be accepted, I am quite unsure about the second: this alters default behavior of the plotting routine. What do people think ?

**Comment by GaelVaroquaux** [comment]
@bthirion : you are understanding the diff wrong: the change in the dictionary from "front" to "back" is only to follow the change in filename, I believe. Hence the behavior is the same.

I am :+1: with the PR, however, I find that the alignment with the anatomy is not great. The values in the "direction_to_transform_params" (in glass_brain.py) should be tweaked (manually) to fix this.

**Comment by kingjr** [comment]
@bthirion The behavior is unchanged. The 'y' direction was a back projection in the first place, but the drawing was a front projection, hence the mental incongruency. 

@GaelVaroquaux Here is how it looks after manually tweaking `direction_to_transform_params`

image

**Comment by GaelVaroquaux** [comment]
LGTM. :+1: for merge.

@bthirion ?

**Comment by bthirion** [comment]
+1. Thx again !

**Comment by GaelVaroquaux** [comment]
Merged. Thanks!

**Pull request merged**
