### PR TITLE
Installation should fail on Python < 3.5

### LINKED ISSUE #2197: Pip installing Nilearn 0.6.0a0 in Py2 envs
Not sure why, installing Nilearn 06.0a0 in a Python2environment does not raise an error. This is strange, since the wheels I build this time are not universal and I removed Python 2 tags. Maybe something was overlooked? Will look at this.

### PR DESCRIPTION
**Pull request by kchawla-pi**
Fixes #2197

### CODE REVIEW

**Comment by jeromedockes** [comment]
why do we need this?

**Comment by kchawla-pi** [comment]
Because without this, Pip will not raise an error if someone tries to install Nilearn's next release in a Python2 or Python3.4 env.

**Comment by kchawla-pi** [comment]
Also, building Nilearn will build binaries compatible with both python2 and 3.

**Comment by jeromedockes** [comment]
> Also, building Nilearn will build binaries compatible with both python2 and 3.

Ok thanks

**Comment by kchawla-pi** [comment]
Now that we have the extra CI jobs from Azure pipelines which are not being used, I'll set them up to test stuff like this.

**Comment by GaelVaroquaux** [comment]
LGTM. Merging. Thank you!

+1 also for scheduling a beta soon.

**Pull request merged**
