### PR TITLE
Bugfix: Add axes on figure of received axes, not on current figure.

### PR DESCRIPTION
**Pull request by bcipolli**
See #450 for details.  @GaelVaroquaux 's suggestion seems to work well.  Note that there's also some slight whitespace tweaks for PEP8 compatibility.

I'm not familiar enough with matplotlib to understand how to add a regression test for this; any pointers / suggestions are welcome!

See #450 for code to test this fix.

### CODE REVIEW

**Comment by AlexandreAbraham** [comment]
LGTM.

Regarding the test, a bit of explanation about matplotlib.

`from matplotlib import pyplot as plt`

If you use a plotting function like `plt.plot`, the plot will be added to the current figure that you can access with `plt.gcf()`. 

So, if I take your original code and simplify it (I didn't run this code :P), we could do:

```
import matplotlib.pyplot as plt
import nibabel
import numpy as np
from nilearn.plotting import plot_glass_brain


maps_img = nibabel.Nifti1Image(np.random,random((10, 10, 10)), np.eye(4))
fh1 = plt.figure()
fh2 = plt.figure()
ax1 = fh1.add_subplot(1, 1, 1)
# Note: pl.gcf()== fh2 because it is the last figure created.
assert(pl.gcf() == fh2)
# Since we gave ax1, the figure should be plotted in fh1.
# Before your fix it was plot in fh2.
slicer = plot_glass_brain(maps_img, axes=ax1, title='test')
# Test it
assert(slicer.axes[0].get_figure() == fh1)
```

**Comment by bcipolli** [comment]
Great.  I will add a test and update.

**Comment by bcipolli** [comment]
I added a test (thanks @AlexandreAbraham for the starting point!) and did a bit of drive-by linting in the test file.

**Comment by AlexandreAbraham** [comment]
LGTM, great work!

**Pull request merged**
