### PR TITLE
[MAINT] sort changelog by labels

### LINKED ISSUE #4194: Sort entries in changelog by label (alphabetical)
Not that I mind the kandisky patchwork look of our current changelog, but I think that having them sorted may help users find what they are looking for.

image

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes #4194

Changes proposed in this pull request:

- sort changelogs by label
- make sure that each entry of older changelogs is on one line as per our contributing guidelines

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
LGTM. Should we add in the release process that  changes should be reordered ?

**Comment by Remi-Gau** [comment]
> LGTM. Should we add in the release process that changes should be reordered ?

probably a good idea

**Review by ymzayek — COMMENTED** [review]
LGTM. Why not include released 0.10 versions?

**Comment by ymzayek** [comment]
> LGTM. Why not include released 0.10 versions?

Oops ignore that. The order of the files got me

**Review by ymzayek — APPROVED** [review]

**Pull request merged**
