### PR TITLE
Add fields/sections for issue information to templates

### LINKED ISSUE #2629: Improve Issue Templates
As discussed in last meeting:

TODO:

- [x] Fix labels in current issue templates which are not added automatically
- [ ] Improve existing templates
- [x] Add new templates? (Documentation Improvement, Question, others...?)

### PR DESCRIPTION
**Pull request by tsalo**
Closes #2629.

Changes proposed in this pull request:

- Convert comments in issue templates to sections to be filled out.
- Add a couple of possible fields to the templates.

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks!

**Comment by NicolasGensollen** [comment]
@tsalo could you rebase/merge master to make the broken tests pass?

**Comment by NicolasGensollen** [comment]
Thanks! Merging...

**Pull request merged**
