### PR TITLE
[MRG] FIX: NumPy errors mostly indexing problems with float values

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Attempts to fix recent failures with recent NumPy indexing float errors.
See PR's:
https://travis-ci.org/nilearn/nilearn/jobs/201121267
https://travis-ci.org/nilearn/nilearn/jobs/200513051

Any reviews on this please ?

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
LGTM. That's a good fix, and indeed, master is failing on the latest numpy. Thanks a lot!

**Comment by GaelVaroquaux** [comment]
@KamalakerDadi : it seems that plot_oasis_vbm no longer runs with this PR merged (or with the latest numpy):
https://circleci.com/gh/nilearn/nilearn/2263

Could you have a look? Thanks!

**Comment by KamalakerDadi** [comment]
>Could you have a look? 

I saw that. I am on it.

**Comment by KamalakerDadi** [comment]
It is because of latest numpy. I missed those examples. I am fixing in a new PR.

**Pull request merged**
