### PR TITLE
[FIX] allow use of small alpha value for plot_img_on_surf

### LINKED ISSUE #4900: [BUG] plotting.plot_img_on_surf gives an error if alpha is set low
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating system

- [ ] Linux
- [ ] Mac
- [x] Windows

### Operating system version

Windows 11

### Python version

- [ ] 3.13
- [x] 3.12
- [ ] 3.11
- [ ] 3.10
- [ ] 3.9

### nilearn version

Version 0.11.0 (I just updated for this)

### Expected behavior

 `plotting.plot_img_on_surf` is supposed to make an image, but it instead errors.

### Current behavior & error messages

I was using `plotting.plot_img_on_surf`, and it produced an error when I specified the `threshold` parameter and I set `alpha` to a low value. For example:

```Python
from nilearn import datasets, plotting, image
data = datasets.fetch_abide_pcp(n_subjects=1)
fig, axs = plotting.plot_img_on_surf(
    image.index_img(data['func_preproc'][0], 0),
    threshold=2, alpha=.1, )
plt.show()
```

Produces the error:

```
  File "...\", line ..., in <module>
    fig, axs = plotting.plot_img_on_surf(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\nilearn\plotting\surf_plotting.py", line 1841, in plot_img_on_surf
    plot_surf_stat_map(
  File "...\Lib\site-packages\nilearn\plotting\surf_plotting.py", line 1517, in plot_surf_stat_map
    display = plot_surf(
              ^^^^^^^^^^
  File "...\Lib\site-packages\nilearn\plotting\surf_plotting.py", line 989, in plot_surf
    fig = _plot_surf_matplotlib(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\nilearn\plotting\surf_plotting.py", line 722, in _plot_surf_matplotlib
    p3dcollec.set_facecolors(face_colors)
  File "...\Lib\site-packages\matplotlib\_api\__init__.py", line 247, in method
    return getattr(self, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\mpl_toolkits\mplot3d\art3d.py", line 1077, in set_facecolor
    super().set_facecolor(colors)
  File "...\Lib\site-packages\matplotlib\collections.py", line 784, in set_facecolor
    self._set_facecolor(c)
  File "...\Lib\site-packages\matplotlib\collections.py", line 766, in _set_facecolor
    self._facecolors = mcolors.to_rgba_array(c, self._alpha)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\matplotlib\colors.py", line 476, in to_rgba_array
    raise ValueError("RGBA values should be within 0-1 range")
ValueError: RGBA values should be within 0-1 range
```

This error doesn't occur if threshold is undefined or `alpha` is kept as some relatively high value (e.g., over 0.5). Interestingly, when preparing this example, I also tried passing MNI152_FILE_PATH (a different dataset) to `plot_img_on_surf`, which does not produce any error (instead, it just shows the image, although I know an anatomical image won't really be meaningful for a surface plot).

It seems that the `face_colors` variable in `plotting.surf_plotting._plot_surf_matplotlib` sometimes surpasses 1.0 due to floating point stuff (1.0000000000000002), which causes this.

### Steps and code to reproduce bug

I provided an error message above. I have a simple fix for this floating point stuff. To `plotting.surf_plotting._plot_surf_matplotlib`, I have simply added one line: `face_colors[face_colors > 1] = 1.` (see line 722 in this picture: https://imgur.com/PKkNUvj)

I have a pull request ready with this one-line addition, but I figured I should post this issue here first.

### PR DESCRIPTION
**Pull request by paulcbogdan**
I am fixing the issue mentioned here: https://github.com/nilearn/nilearn/issues/4900

I also added a test. However, I admittedly am not sure how to access `img_3d_mni`, and this bug is strange where it doesn't seem to trigger for some images. Running this on the first participant of `datasets.fetch_abide_pcp` or running this on randomly generated normally distributed data, will generate an error. However, running it on `nilearn.datasets.MNI152_FILE_PATH` will not generate any error. Also, for these first two, I noticed that setting `alpha=.01` doesn't create an error whereas `alpha=.1` does.

- Closes #4900

Changes proposed in this pull request:

- Preventing values over 1 via `face_colors[face_colors > 1] = 1`
- Adding a test for this

### CODE REVIEW

**Comment by Remi-Gau** [comment]
did some clean up:
- extracted test into a single test
- updated changelog
- made sure code complies with code style

**Comment by Remi-Gau** [comment]
> I admittedly am not sure how to access `img_3d_mni`

it is a pytest fixture defined in the test config file:

https://github.com/nilearn/nilearn/blob/9bc9d49b57a3e35357564c3c1d7de887e0b81c04/nilearn/conftest.py#L256

allows us to easily reuse some values, instances across tests

**Comment by paulcbogdan** [comment]
Ah, my bad then about missing these things. Thanks, and I appreciate the explanation

**Review by bthirion — COMMENTED** [review]
Does the test fail with current Nilearn ?

**Comment by Remi-Gau** [comment]
yup I checked that the tests fails on main first

**Review by Remi-Gau — APPROVED** [review]

**Pull request merged**
