### PR TITLE
[STY] deal with private functions in nilearn.glm that do not coform to PEP8 naming

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes none
- Relates to #3319 

Changes proposed in this pull request:

- move `_check_events_file_uses_tab_separators` and `_check_run_tables` and their sub functions" from `_utils.py` to `first_level.py` closer to where there are only used.
- move tests accordingly
- rename private functions `_cosine_drift` -> `create_cosine_drift` and `_orthogonalize` -> `orthogaonalize` as they are used outside of the modules where they are defined.

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Review by ymzayek — COMMENTED** [review]
LGTM. One question: shouldn't the functions renamed to without a leading underscore be listed in the init (such as orthogonalize)?

**Comment by Remi-Gau** [comment]
> LGTM. One question: shouldn't the functions renamed to without a leading underscore be listed in the init (such as orthogonalize)?

At the the moment the `"__all__"` of public modules define whats is part of the user facing API and matches what's in the API documentation.

The leading underscores should just signal if that function is private to the module it is in or not. Given that `_orthogonalize` is used outside of the module it is defined in (for example in `design_matrix.py`), it is not private to that module so we should remove the leading underscore. But I don't think it warrants making it part of the user facing API.

**Comment by ymzayek** [comment]
@Remi-Gau yes that's right thanks for clarifying. That was the old way of doing it and I just had a little mental lapse

**Review by ymzayek — APPROVED** [review]
good to go

**Comment by bthirion** [comment]
Merging, then.

**Pull request merged**
