### PR TITLE
FIX: travis and circle with matplotlib

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Few examples and travis are failing with recent matplotlib 2.1.0.

Details about recent failures with ```imshow``` matplotlib 2.1.0 are in [here](https://github.com/matplotlib/matplotlib/issues/9280)

Examples: plot_overlay.py & plot_prob_atlas.py

I agree this is not a good FIX and I even don't know if this fixes it.
Any ideas are welcome

### CODE REVIEW

**Comment by lesteve** [comment]
Very quickly looking this seems a reasonable work-around which I expect to fix Travis and CircleCI. You can revert to `*` when matplotlib 2.1.1 is released.

**Comment by KamalakerDadi** [comment]
>You can revert to * when matplotlib 2.1.1 is released.

Yup, I will revert to * once it is released. Thanks

**Comment by lesteve** [comment]
CIs are green, merging, thanks a lot!

**Comment by GaelVaroquaux** [comment]
Thanks Loic for the help!

**Pull request merged**
