### PR TITLE
FIX: a fix for sklearn 0.20

### PR DESCRIPTION
**Pull request by GaelVaroquaux**

### CODE REVIEW

**Comment by kchawla-pi** [comment]
What's the issue this is fixing?

**Comment by GaelVaroquaux** [comment]
Indeed, I had an old scikit-learn. This was fixed in the mean time. Closing.

**Comment by kchawla-pi** [comment]
What about those with older scikit-learn? Would this have benefited them?

**Comment by GaelVaroquaux** [comment]
No. I think that this was just an unreleased version

⁣Sent from my phone. Please forgive typos and briefness.​

**Pull request closed without merging**
