### PR TITLE
[DOC] Add explanation of pre-releases to maintenance docs

### LINKED ISSUE #3518: Update maintenance docs to include new pre-release schedule
Add a few lines about monthly pre-release schedule to the maintenance docs: https://nilearn.github.io/stable/maintenance.html

### PR DESCRIPTION
**Pull request by ymzayek**
Closes #3518 .

Question: With the pre-releases should we also push a new build of the stable docs?

### CODE REVIEW

**Comment by emdupre** [comment]
> Question: With the pre-releases should we also push a new build of the stable docs?

I'd say no, personally ! I don't see this in e.g. the pandas docs, for example.

**Comment by ymzayek** [comment]
@NicolasGensollen thanks for your input. The argument was initially to do more patch releases, for example every time a bug is fixed. However, this is maybe not ideal for nilearn, where it's beneficial for users to not have to deal with frequent changes and potential breaking of the API. This pre-release schedule would allow users who rely on bugfixes to use the rc version, while the majority of users don't have to worry about it. Pinging @tsalo and @jeromedockes 

Also concerning this PR, maybe it's ok to not document it like this and keep it informal for now.

**Comment by bthirion** [comment]
We could get back to the point at a future coredev meeting: what is here represents what was discussed last time.

**Comment by ymzayek** [comment]
Closing this after recent decision in core developer meeting to abandon the prerelease plan

**Pull request closed without merging**
