### PR TITLE
[STY] fix simplify ruff errors

### LINKED ISSUE #4579: Rerformating with Ruff
- Started with https://github.com/nilearn/nilearn/pull/4574,there should be a few simple follow things todo with small PRs.

I am listing them here for more transparency and so that things are not just in my head.

- [x] apply ruff to files that were not covered yet (`nilearn/_utils/docs.py` and `nilearn/datasets/neurovault.py`) - see https://github.com/nilearn/nilearn/pull/4578
- [x] apply some doc rules that are ignored for now (notably D209: https://docs.astral.sh/ruff/rules/new-line-after-last-paragraph/) --> https://github.com/nilearn/nilearn/pull/4583
- [x] remove the PTH errors (https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth) from the ignore list and fix them - see also https://github.com/nilearn/nilearn/issues/4327

After this I think, some more rules could be removed from the ignored list and autofixed by running `pre-commit run -a` and see how many files are changed and what the changes are.

I would probably start looking into:
- [x] numpy errors: https://docs.astral.sh/ruff/rules/#numpy-specific-rules-npy
- [x] pandas errors: https://docs.astral.sh/ruff/rules/#pandas-vet-pd
- [x] performance errors: https://docs.astral.sh/ruff/rules/#perflint-perf
- [x] simplify errors: https://docs.astral.sh/ruff/rules/#flake8-simplify-sim

### List of errors

| status | number of errors | error code | autofixable | error name | 
| -  | -  |  -   | - | - | 
| - [ ] | 560  |   `N806`    | [ ] | non-lowercase-variable-in-function | 
| - [ ] | 184  |   `ERA001`  | [*] | commented-out-code | 
| - [ ] | 164  |   `PLR2004` | [ ] | magic-value-comparison | 
| - [ ] | 135  |   `B028`    | [ ] | no-explicit-stacklevel | 
| - [ ] | 115  |   `N803`    | [ ] | invalid-argument-name | 
| - [ ] |  17  |   `RUF012`  | [ ] | mutable-class-default | 
| - [ ] |  34  |   `B904`    | [ ] | raise-without-from-inside-except | 
| - [ ] |   8  |   `D105`    | [ ] | undocumented-magic-method | 
| - [ ] |   5  |   `E741`    | [ ] | ambiguous-variable-name | 
| - [ ] |   3  |   `ARG005`  | [ ] | unused-lambda-argument | 
| - [ ] |   3  |   `PERF203` | [ ] | try-except-in-loop | 

### In progress 

| status | number of errors | error code | autofixable | error name | 
| -  | -  |  -   | - | - | 

### Probably won't fix

Fixing the following ones would mess up our doc rendering.

| status | number of errors | error code | autofixable | error name | 
| -  | -  |  -   | - | - | 
| - [ ] | 309  |   `D205`    | [ ] | blank-line-after-summary | 
| - [ ] |  61  |   `D208`    | [*] | over-indentation | 
| - [ ] |   1  |   `D301`    | [*] | escape-sequence-in-docstring | 

### To fix later (maybe)

issues related to code complexity - silenced for now by adapting the threshold

| status | number of errors | error code | autofixable | error name | 
| -  | -  |  -   | - | - | 
| - [ ] | 216  |   `PLR0913` | [ ] | too-many-arguments | 
| - [ ] |  48  |   `PLR0912` | [ ] | too-many-branches | 
| - [ ] |  23  |   `PLR0915` | [ ] | too-many-statements | 
| - [ ] |   3  |   `PLR0911` | [ ] | too-many-return-statements | 

### Fixed

| status | number of errors | error code | autofixable | error name | 
| -  | -  |  -   | - | - | 
| - [x] |  41  |   `B018`    | [ ] | useless-expression | 
| - [x] |   2  |   `SIM117`  | [ ] | multiple-with-statements | 
| - [x] |  37  |   `PD011`   | [ ] | pandas-use-of-dot-values | 
| - [x] |  57  |   `N802`    | [ ] | invalid-function-name | 
| - [x] |   3  |   `PLR1704` | [ ] | redefined-argument-from-local | 
| - [x] |  14  |   `PD901`   | [ ] | pandas-df-variable-name | 
| - [x] |   5  |   `ARG003`  | [ ] | unused-class-method-argument | 
| - [x] |  41  |   `ARG001`  | [ ] | unused-function-argument | 
| - [x] |  34  |   `ARG002`  | [ ] | unused-method-argument | 
| - [x] |  81  |   `RUF005`  | [ ] | collection-literal-concatenation | 
| - [x] |   9  |   `RUF002`  | [ ] | ambiguous-unicode-character-docstring | 
| - [x] |   2  |   `RUF003`  | [ ] | ambiguous-unicode-character-comment | 
| - [x] |   2  |   `N813`    | [ ] | camelcase-imported-as-lowercase | 
| - [x] |   1  |   `N816`    | [ ] | mixed-case-variable-in-global-scope | 
| - [x] |   1  |   `N817`    | [ ] | camelcase-imported-as-acronym | 
| - [x] |   1  |   `N818`    | [ ] | error-suffix-on-exception-name | 
| - [x] |   7  |   `SIM102`  | [ ] | collapsible-if | 
| - [x] |   4  |   `SIM105`  | [ ] | suppressible-exception | 
| - [x] |   1  |   `SIM115`  | [ ] | open-file-with-context-handler | 
| - [x] |   6  |   `PERF401` | [ ] | manual-list-comprehension | 
| - [x] |   2  |   `PERF102` | [*] | incorrect-dict-iterator | 
| - [x] |   1  |   `PERF403` | [ ] | manual-dict-comprehension | 
| - [x] |   1  |   `PD003`   | [ ] | pandas-use-of-dot-is-null | 
| - [x] |   4  |   `PD002`   | [*] | pandas-use-of-inplace-argument | 
| - [x] |   2  |   `NPY002`  | [ ] | numpy-legacy-random | 
| - [x] |   1  |   `SIM103`  | [*] | needless-bool | 
| - [x] |   1  |   `SIM114`  | [*] | if-with-same-arms | 
| - [x] |   8  |   `SIM108`  | [*] | if-else-block-instead-of-if-exp | 
| - [x] |  37  |   `SIM118`  | [*] | in-dict-keys | 
| - [x] |   3  |   `SIM201`  | [*] | negate-equal-op | 
| - [x] |   8  |   `SIM300`  | [*] | yoda-conditions | 
| - [x] |   1  |   `PLR1714` | [*] | repeated-equality-comparison |
| - [x] |   2  |   `PLR1730` | [*] | if-stmt-min-max | 
| - [x] |   2  |   `PLR1736` | [*] | unnecessary-list-index-lookup | 
| - [x] |  10  |   `PLR5501` | [*] | collapsible-else-if | 
| - [x] |   2  |   `PLR0402` | [*] | manual-from-import | 
| - [x] |   1  |   `C419`    | [*] | unnecessary-comprehension-in-call | 
| - [x] |   8  |   `C414`    | [*] | unnecessary-double-cast-or-process | 
| - [x] |   7  |   `C416`    | [*] | unnecessary-comprehension | 
| - [x] |  87  |   `C408`    | [*] | unnecessary-collection-call | 
| - [x] | 135  |   `D209`    | [*] | new-line-after-last-paragraph | 
| - [x] |  15  |   `RUF100`  | [*] | unused-noqa | 
| - [x] |  20  |   `RUF010`  | [*] | explicit-f-string-type-conversion | 
| - [x] |   7  |   `RUF015`  | [*] | unnecessary-iterable-allocation-for-first-element | 
| - [x] |   1  |   `FLY002`  | [*] | static-join-to-f-string | 
| - [x] |  10  |   `UP031`   | [*] | printf-string-formatting |

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Relates #4579

Changes proposed in this pull request:

- apply autofixes error for simplify errors from ruff
  - https://docs.astral.sh/ruff/rules/#flake8-simplify-sim

### CODE REVIEW

**Comment by Remi-Gau** [comment]
I tried to commit each error fixed in a separate commit to make reviewing easier

**Review by man-shu — APPROVED** [review]
LGTM!

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Comment by Remi-Gau** [comment]
thanks for the reviews @bthirion @man-shu

**Pull request merged**
