### PR TITLE
Update image.py

### PR DESCRIPTION
**Pull request by Leo-YF-Liu**
change int8 to int16 to avoid dtype error in compute_epi_mask()

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Can you please add a test that demonstrates the error: I do not understand the problem.

Thanks!

**Comment by Leo-YF-Liu** [comment]
data is a list of Spm2AnalyzeImages, i.e.,
[<nibabel.spm2analyze.Spm2AnalyzeImage at 0x1e4b2ca6eb8>,
 <nibabel.spm2analyze.Spm2AnalyzeImage at 0x1e4b2caf278>,
 <nibabel.spm2analyze.Spm2AnalyzeImage at 0x1e4b2caf438>,
 <nibabel.spm2analyze.Spm2AnalyzeImage at 0x1e4b2caf710>,
...
]

Then I ran this:
mask = compute_epi_mask(data)
got the following error, but with the change of int8 to int16, I can get rid of the error.

---------------------------------------------------------------------------
HeaderDataError                           Traceback (most recent call last)
<ipython-input-9-57b7ebb2d10a> in <module>()
----> 1 mask = compute_epi_mask(data)

C:\Users\LYF\Anaconda3\lib\site-packages\nilearn\masking.py in compute_epi_mask(epi_img, lower_cutoff, upper_cutoff, connected, opening, exclude_zeros, ensure_finite, target_affine, target_shape, memory, verbose)
    287         connected=connected, warning_msg="Are you sure that input "
    288             "data are EPI images not detrended. ")
--> 289     return new_img_like(epi_img, mask, affine)
    290 
    291 

C:\Users\LYF\Anaconda3\lib\site-packages\nilearn\image\image.py in new_img_like(ref_niimg, data, affine, copy_header)
    628         header['cal_max'] = np.max(data) if data.size > 0 else 0.
    629         header['cal_min'] = np.min(data) if data.size > 0 else 0.
--> 630     return ref_niimg.__class__(data, affine, header=header)
    631 
    632 

C:\Users\LYF\Anaconda3\lib\site-packages\nibabel\analyze.py in __init__(self, dataobj, affine, header, extra, file_map)
    921                  extra=None, file_map=None):
    922         super(AnalyzeImage, self).__init__(
--> 923             dataobj, affine, header, extra, file_map)
    924         # Reset consumable values
    925         self._header.set_data_offset(0)

C:\Users\LYF\Anaconda3\lib\site-packages\nibabel\spatialimages.py in __init__(self, dataobj, affine, header, extra, file_map)
    368         if header is None:
    369             if hasattr(dataobj, 'dtype'):
--> 370                 self._header.set_data_dtype(dataobj.dtype)
    371         # make header correspond with image and affine
    372         self.update_header()

C:\Users\LYF\Anaconda3\lib\site-packages\nibabel\analyze.py in set_data_dtype(self, datatype)
    576             if dt not in self._data_type_codes:
    577                 raise HeaderDataError(
--> 578                     'data dtype "{0}" not supported'.format(datatype))
    579         code = self._data_type_codes[dt]
    580         dtype = self._data_type_codes.dtype[code]

HeaderDataError: data dtype "int8" not supported

**Comment by GaelVaroquaux** [comment]
OK, so it seems that this is for analyze only, and not for nifti (I've
never experienced the problem, and I work with nifti).

Could you please:

1. Adjust the code to do use int16 only for analyze

2. Write a unit test

Thanks

**Comment by Leo-YF-Liu** [comment]
Probably we can change line 156 in analyze.py to 
_dtdefs = (  # code, conversion function, equivalent dtype, aliases
    (0, 'none', np.void),
    (1, 'binary', np.void),  # 1 bit per voxel, needs thought
    (2, 'int8', np.int8),
    (4, 'int16', np.int16),
    (8, 'int32', np.int32),
    (16, 'float32', np.float32),
    (32, 'complex64', np.complex64),  # numpy complex format?
    (64, 'float64', np.float64),
    (128, 'RGB', np.dtype([('R', 'u1'),
                           ('G', 'u1'),
                           ('B', 'u1')])),
    (255, 'all', np.void))

**Comment by Leo-YF-Liu** [comment]
Just change uint8 to int8

**Comment by Leo-YF-Liu** [comment]
You define default dtype for boolean in image.py as int8, but for the analyzeImage, the default dtype list does not inlcude that. I am not sure which part should be changed.

**Comment by GaelVaroquaux** [comment]
> You define default dtype for boolean in image.py as int8, but for the
> analyzeImage, the default dtype list does not inlcude that. I am not
> sure which part should be changed.

One is in nilearn, the other in nibabel (different package, with
different set of contributors), so it's a very different fix.

I cannot speak for nibabel.

**Comment by Leo-YF-Liu** [comment]
I tried this fix, it works on my side.
Change line 156 in analyze.py to
_dtdefs = ( # code, conversion function, equivalent dtype, aliases
(0, 'none', np.void),
(1, 'binary', np.void), # 1 bit per voxel, needs thought
(2, 'int8', np.int8),
(4, 'int16', np.int16),
(8, 'int32', np.int32),
(16, 'float32', np.float32),
(32, 'complex64', np.complex64), # numpy complex format?
(64, 'float64', np.float64),
(128, 'RGB', np.dtype([('R', 'u1'),
('G', 'u1'),
('B', 'u1')])),
(255, 'all', np.void))

**Comment by Leo-YF-Liu** [comment]
Do you want me to push a fix for that?

**Comment by GaelVaroquaux** [comment]
> Do you want me to push a fix for that?

I don't believe that this is in the nilearn codebase, but in the nibabel
codebase. And I cannot assess it's correctness, as I don't know nibabel
well enough.

**Comment by Leo-YF-Liu** [comment]
Opps, I didn't realize that. I see what you mean. I can make the change in nilearn accordingly.

**Comment by kchawla-pi** [comment]
Is this alive? If not, please close it by this weekend.

**Comment by thomasbazeille** [comment]
It seems that this change didn't concern nilearn directly. Closing, don't hesitate to reopen if needed

**Pull request closed without merging**
