### PR TITLE
MAINT: control SpaceNet convergence

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Avoid too long loops when spacenet does not converge

Inspired by #1977, by @KamalakerDadi 

This PR should be "safe", in the sense that the change should be harmless. Iterating 1000 time is too much anyhow.

### CODE REVIEW

**Comment by kchawla-pi** [comment]
Azure Pipelines fail has nothing to do with your PR.

**Comment by GaelVaroquaux** [comment]
SpaceNet is still very slow, but at least things converge.

Maybe with a warm cache thing won't be a problem?

I suggest we merge, and keep thinking about this problem.

**Comment by kchawla-pi** [comment]
Running make HTML strict locally should be okay.

**Comment by kchawla-pi** [comment]
Maybe we can ssh and pdb into the example, see what's what, somehow...

**Comment by kchawla-pi** [comment]
> Running make HTML strict locally should be okay.

I mean for this Sprint

**Comment by GaelVaroquaux** [comment]
Merging.

**Pull request merged**
