### PR TITLE
[MAINT] Format datasets data and description

### PR DESCRIPTION
**Pull request by Remi-Gau**
Relates https://github.com/nilearn/nilearn/issues/2528

Splinter of #3624

Changes proposed in this pull request:

- apply isort, black and precommit hooks
- fix flake8 issues

### CODE REVIEW

**Comment by Remi-Gau** [comment]
will update CI checks, pre-commit and pyproject.toml only in the last PR  for the dataset folder.

**Review by ymzayek — APPROVED** [review]
Thanks for breakig these down! This one LGTM!

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks a lot for splitting this massive PR @Remi-Gau !

**Pull request merged**
