### PR TITLE
[MRG] Use capital letters + other small changes related to PEP8

### PR DESCRIPTION
**Pull request by aabadie**
This is the PR related to #792.

### CODE REVIEW

**Comment by lesteve** [comment]
Failing tests in case you missed it.

**Comment by aabadie** [comment]
> Failing tests in case you missed it.

@lesteve  I forgot one replacement in the tests. It's all ok now. (Circle CI is temporarily broken apparently).

**Comment by GaelVaroquaux** [comment]
All tests are green, and the change look good to me. Merging. Thanks

**Comment by aabadie** [comment]
I guess I can close #792: Fix#792

**Comment by aabadie** [comment]
Fix #792

**Comment by GaelVaroquaux** [comment]
You need to write this in a commit message for the issue to be closed (it can be anywhere in the commit message).

**Comment by aabadie** [comment]
> You need to write this in a commit message for the issue to be closed (it can be anywhere in the commit message).

Yes I misunderstood one of @lesteve tips about how to achieve this. Need to read more about these useful features.

**Comment by lesteve** [comment]
>> You need to write this in a commit message for the issue to be closed (it can be anywhere in the commit message).

> Yes I misunderstood one of @lesteve tips about how to achieve this. Need to read more about these useful features.

You need to put it in the description of the PR (and IIRC you have to do it when you create the PR you can not edit the PR description later to add it).

The github [doc](https://github.com/blog/1506-closing-issues-via-pull-requests) about closing issue from PR and the list of [magical keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) you can use.

**Pull request merged**
