### PR TITLE
[FIX] Fixed two-sided threshold

### LINKED ISSUE #4497: [BUG] threshold_img yields negative cut-off even when two-sided is set to True
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [X] Mac
- [ ] Windows

### Operating system version

Mac OS Version 14.5 "sonoma"

### Python version

- [X] 3.12
- [ ] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

0.10.4  

### Expected behavior

When thresholding an image with both negative and positive values and setting the argument `two_sided = True`, the variable `cutoff_threshold` should be a positive number otherwise no voxels will be thresholded in the following snipped code from the function:
```python
if two_sided:
        img_data[np.abs(img_data) < cutoff_threshold] = 0.0
```

### Current behavior & error messages

Thresholding with argument `two-sided = True` is implemented wrong. The `cutoff_threshold`should be calculated on the absolute values of img_data:

```python
if two_sided:
    cutoff_threshold = check_threshold(
            threshold,
            np.abs(img_data),
            percentile_func=scoreatpercentile,
            name="threshold",
        )
else:
    cutoff_threshold = check_threshold(
            threshold,
            img_data,
            percentile_func=scoreatpercentile,
            name="threshold",
        )
```

### Steps and code to reproduce bug

```python
import numpy as np
from nilearn import image, datasets

# generate random 3x3x3 image with negative and postive values
img = image.new_img_like(datasets.load_mni152_template(), np.random.normal(size=(3,3,3)))
# threshold image at 1%
img_thresholded = image.threshold_img(img, threshold="1%", two_sided=True)
# see if threshold did anything
assert np.all(img.get_fdata() == img_thresholded.get_fdata()) == False
```

### PR DESCRIPTION
**Pull request by gurraburra**
- Closes #4497

Changes proposed in this pull request:

- Changed how cutoff_threshold is calculated when two-sided threshold is requested.

### CODE REVIEW

**Review by Remi-Gau — CHANGES_REQUESTED** [review]
Thanks for the PR @gurraburra 

do you think you could add a test to the PR so that we make sure we keep track of this behavior?

You have a starter of a test in the issue you opened: https://github.com/nilearn/nilearn/issues/4497#issue-2434996674

it could be added in this file near here: https://github.com/nilearn/nilearn/blob/796f101439c6ff72434a7adb3ab1fecf2cf87e21/nilearn/image/tests/test_image.py#L854

**Comment by gurraburra** [comment]
> Thanks for the PR @gurraburra
> 
> do you think you could add a test to the PR so that we make sure we keep track of this behavior?
> 
> You have a starter of a test in the issue you opened: [#4497 (comment)](https://github.com/nilearn/nilearn/issues/4497#issue-2434996674)
> 
> it could be added in this file near here:
> 
> https://github.com/nilearn/nilearn/blob/796f101439c6ff72434a7adb3ab1fecf2cf87e21/nilearn/image/tests/test_image.py#L854

Unfortunately I have no past experience of setting up tests, I tried but had problems with dependencies not being installed.

**Comment by Remi-Gau** [comment]
@gurraburra I will take over the rest of the PR to add the tests, update changelog...

**Comment by hndgzkn** [comment]
@Remi-Gau  Before merging this one, I thought we might consider this case https://github.com/nilearn/nilearn/issues/4497#issuecomment-2299849891 and fix excluding mask points while taking percentile (https://github.com/nilearn/nilearn/issues/4497#issuecomment-2303080063)  in `nilearn._utils.param_validation.check_threshold`.

Doing this first and also taking into account the below comments (if they make sense) might shape this PR differently. 

There are some issues which are not clear to me with the implementation of `nilearn._utils.param_validation.check_threshold`, these might also help identify the points to document in the function spec.

1. `two_sided` can be a parameter to this function depending on the answers of the following questions.
2. Is negative threshold value possible/meaningful?
3. When specified `threshold is float` or `threshold is str` and `two_sided=False`, shall we consider negative points while setting `cutoff_threshold` ? Currently we consider them.
4. When specified `threshold is float` and `two_sided=True`, do we really want the behavior proposed in this PR ? Is there a preference between the positive and negative side of the data to determine the threshold depending on the percentile specified? Could we think of some other way of processing to obtain a threshold value that would give us the ideal thresholded image data shown in https://github.com/nilearn/nilearn/issues/4497#issuecomment-2256692575 ?

**Comment by bthirion** [comment]
If the threshold is a percentile, the thresholding is a priori one-sided. 
Maybe it is simpler to keep it one-sided-only.

**Comment by hndgzkn** [comment]
> If the threshold is a percentile, the thresholding is a priori one-sided. Maybe it is simpler to keep it one-sided-only.

If we say that, then there will be no way to get negative values using a percentile value. In that case actually `two_sided` parameter becomes meaningless and having the possibility to set it to `True` might be misleading.

Instead I'd propose :

- to add `two_sided` as a parameter to `check_threshold`. 
  (Also `img_mask` to be a parameter to `check_threshold` to be able to exclude out-of mask values while calculating threshold as proposed [ici](https://github.com/nilearn/nilearn/issues/4497#issuecomment-2303080063))

- If `two_sided=False`, consider only positive points for float or percentile type for threshold.

- If `two_sided=True`:
   - when threshold is float, take the max of absolute value of the negative and positive values to determine max threshold possible.

  - when threshold is str, we can select among the below possibilities:

    * it can take absolute value of all data and calculate threshold for required percentile.
    * it can take only positive values to calculate threshold for specified percentile on positive values, but also return the negative values for the calculated threshold 
    
and in either case, document the the behavior.

Finally, if negative threshold is not meaningful, it could be good to check if specified threshold value >= 0.

**Comment by bthirion** [comment]
> when threshold is str, we can select among the below possibilities:
> 
>     * it can take absolute value of all data and calculate threshold for required percentile.
> 
>     * it can take only positive values to calculate threshold for specified percentile on positive values, but also return the negative values for the calculated threshold

I think I would consider the second possibility only. People can always do the first one with `math_img`

**Comment by hndgzkn** [comment]
@Remi-Gau Can I work on this one?

**Comment by Remi-Gau** [comment]
> Can I work on this one?

yes go for it!!!

**Comment by hndgzkn** [comment]
> I think I would consider the second possibility only. People can always do the first one with `math_img`

What should be the behavior for `threshold <=  0`? 

I've seen [this discussion](https://github.com/nilearn/nilearn/issues/4340) . I assume the desired behavior should be the same. 

I plan to implement the behavior as follows, if you agree so @Remi-Gau @bthirion :

- If `threshold > 0` and `two_sided=False`, consider only positive points for float or percentile type for threshold.

- If `threshold > 0` and `two_sided=True`:
   - when threshold is float, take the max of absolute value of the negative and positive values to determine max threshold possible.

  - when threshold is str, take only positive values to calculate threshold for specified percentile on positive values, but also return the negative values for the calculated threshold 
    
- If `threshold =< 0` and `two_sided=False`, consider all values greater than the specified threshold. 
- If `threshold =< 0` and `two_sided=True` raise error.

**Comment by hndgzkn** [comment]
I move discussion to https://github.com/nilearn/nilearn/pull/4951.

**Pull request closed without merging**
