### PR TITLE
Fix cache mixin

### PR DESCRIPTION
**Pull request by AlexandreAbraham**
Addresses #385.

Fix semantic problems in cache_mixin that led to misuse of the functions. Shorten the code.

Roadmap:
- [X] In `_utils/cache_mixin.py`, put all the code into the function `cache` (remove duplicate). The code in `CacheMixin` should be a wrapper around `cache`
- [X] Rename `ref_memory_level` to `func_memory_level` to avoid ambiguity.
- [X] Put `None` as default for both parameters
- [x] Check all occurences of caching in the code
- [X] Add a test on memory level

### CODE REVIEW

**Comment by bcipolli** [comment]
Looks like one file may have been included unintentionally? `nilearn/decomposition/dict_learning.py`

**Comment by bcipolli** [comment]
Quick note: I tried this with #371, in place of the change I had made, and it solved all of the memory warnings.

**Comment by lesteve** [comment]
> Looks like one file may have been included unintentionally? nilearn/decomposition/dict_learning.py

Yep good catch!

**Comment by bcipolli** [comment]
Two suggestions from the test side: 
* Could you add tests to test the cache invalidation code?  There are two different warnings, a test to trigger each pathway seems appropriate.
*Could you add `verbose=0` to your `Memory` object to avoid output in the test?

**Comment by AlexandreAbraham** [comment]
File removed.

**Comment by AlexandreAbraham** [comment]
I added a verbose option for function cache and put verbose to 0 in test. A test already exists for cache invalidation.

**Comment by lesteve** [comment]
LGTM, once the neurodebian travis passes.

**Comment by AlexandreAbraham** [comment]
@bcipolli we merged it because we are in a sprint. If you have further comments, please put them here or better, open a new issue.

**Comment by bcipolli** [comment]
Awesome re: invalidation test.  Glad this is in, got to learn `nilearn` a bit more today through reading all the activity!  Hope I can participate in a future sprint :)

**Pull request merged**
