### PR TITLE
[DOC] use higher contrast pygment style for dark mode

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes none

Changes proposed in this pull request:

- use the monokai theme for rendering code in dark mode (higher contrast, comments more visible, better people with suboptimal vision)

### CODE REVIEW

**Comment by Remi-Gau** [comment]
| mode | before | after |
| -- | -- | -- |
| light | image | |

**Review by bthirion — COMMENTED** [review]
To be checked also on white bg.

**Comment by Remi-Gau** [comment]
> To be checked also on white bg.

it will not be affected by this change: see first row of table [here](https://github.com/nilearn/nilearn/pull/4847#issuecomment-2509757654)

**Comment by man-shu** [comment]
I like monokai too!

**Pull request merged**
