### PR TITLE
[MAINT] Pin kaleido version to `0.1.0.post1` for windows

### LINKED ISSUE #3925: flaky `test_plotly_savefig` time-out on GHA workflow for tests on windows
Some examples:

- Windows 3.11: timing out on `nilearn/plotting/tests/test_surf_plotting.py::test_plotly_savefig` 
  - https://github.com/nilearn/nilearn/actions/runs/5957291727/job/16159723334

- Windows 3.9: timing out on `nilearn/plotting/tests/test_surf_plotting.py::test_plotly_savefig` 
  - https://github.com/nilearn/nilearn/actions/runs/5940176071/job/16108183249

- Windows 3.8: timing out on `nilearn/plotting/tests/test_surf_plotting.py::test_plotly_savefig` 
  - https://github.com/nilearn/nilearn/actions/runs/5927574875/job/16071361730

### PR DESCRIPTION
**Pull request by ymzayek**
- Hopefully closes #3925

### CODE REVIEW

**Comment by ymzayek** [comment]
The pyproject.toml configuration works well for installing a specific version of kaleido for windows. Other systems will continue to install the most recent release. Now I'll see about launching the windows tests a number of times to see if we get any failures.

**Comment by Remi-Gau** [comment]
> The pyproject.toml configuration works well for installing a specific version of kaleido for windows. Other systems will continue to install the most recent release.

Thanks for testing this. Glad to know my suggestion was not completely useless.

I think another thing we can do it this first salvo of tests pass is to then run the problematic test a large number of times to increase our chances of triggering at least one failure.

**Comment by ymzayek** [comment]
> I think another thing we can do it this first salvo of tests pass is to then run the problematic test a large number of times to increase our chances of triggering at least one failure.

With commit [31c1f27](https://github.com/nilearn/nilearn/pull/4101/commits/31c1f2727c820bacd47907b7c45f926caf334078) it should run 100 times for each python version on the 2 supported Actions windows runners

**Comment by ymzayek** [comment]
Everything passed! I'll revert the changes made for testing and mark this PR as ready

**Review by Remi-Gau — APPROVED** [review]
Good with me.
We will have enough runs of the test suite before the next release to catch any eventual fail. So let's have this one in and see if those flaky fails are gone for good.

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Pull request merged**
