### PR TITLE
[MAINT] Update config black and pre-commit

### PR DESCRIPTION
**Pull request by Remi-Gau**
Relates to https://github.com/nilearn/nilearn/issues/2528

Changes proposed in this pull request:

- update pre-commit and black config to run on all files except:
  - those involved in PRs
  - or those in part of the codebase that yet have to reformatted by black.

This results in very long "exclude" sections but brings us closer to the end goal of running black and pre-commit on everything: now we are at the stage of run on "everything minus those 100 files".

- run `pre-commit run -a` to apply all hooks and check that no further change is done by running `black .`

following PRs will just gradually remove files from those exclude sections and re-apply black.

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
LGTM so far.

**Comment by Remi-Gau** [comment]
Note that all CI jobs are finished but the UI shows them as still running.

Not sure what happened on the azure python 3.11.

**Comment by Remi-Gau** [comment]
> LGTM so far.

FYI @bthirion 
I do not intend to reformat more files in this PR to avoid inflicting yet another 1000 lines long PR and y'all.

**Comment by bthirion** [comment]
Sure. Do you undertsand the CI failures ?

**Review by ymzayek — APPROVED** [review]
LGTM

**Comment by Remi-Gau** [comment]
> Sure. Do you undertsand the CI failures ?

nope: trying to move to GH action only in #3780

**Review by bthirion — APPROVED** [review]
LGTM.

**Comment by Remi-Gau** [comment]
OK I will merge this as I think it is pretty clear by now that the CI fails are not related to the content of the PR

**Pull request merged**
