### PR TITLE
[INFRA] Add Python `3.11` to GitHub Actions testing workflow

### LINKED ISSUE #3522: Running pytest with Python `3.11` in testing CI
Should we add latest Python to our testing workflows in https://github.com/nilearn/nilearn/blob/main/.github/workflows/testing.yml?

### PR DESCRIPTION
**Pull request by ymzayek**
Closes #3522 .

Add Python 3.11 to testing matrix and use with pre-release job

### CODE REVIEW

**Comment by bthirion** [comment]
I guess it has to be merged with #3529 right ?

**Review by Remi-Gau — APPROVED** [review]
Good with me. 
thanks @ymzayek

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks @ymzayek !

**Comment by bthirion** [comment]
Merging then.

**Pull request merged**
