### PR TITLE
Remove inplace modification in signal.clean

### PR DESCRIPTION
**Pull request by AlexandreAbraham**
PR #1271 introduces this regression where ensure_finite=True modifies the data inplace instead of copying it (nan_to_num does an implicit copy). I preferred to get back to nan_to_num instead of just doing a copy because I believe that relying on numpy functions is safer and more future proof.

Note: I have set float defaults as it done by default for the nan value.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Good catch. It would need a unit test.

Maybe @kchawla-pi can add one and we merge?

**Comment by kchawla-pi** [comment]
Curious: Why is replacing the original `signals` with a modified copy better than an in-place modification?

**Comment by kchawla-pi** [comment]
We should add the problem faced due to the regression in the original comment, or file an issue elaborating this.

**Comment by kchawla-pi** [comment]
@GaelVaroquaux I'm not sure I an add a unit test that will bring more value than existing test suite. The existing tests are passing, I think that may be sufficient confirmation for the change. Thoughts?

**Comment by jeromedockes** [comment]
> @GaelVaroquaux I'm not sure I an add a unit test that will bring more value than existing test suite. The existing tests are passing, I think that may be sufficient confirmation for the change. Thoughts?

ideally there should be a test that passes on this branch and fails on master

**Comment by kchawla-pi** [comment]
Yeah I have an idea that might work.
Not sure if it adds value to the test suite though.
Kshitij

------------------------------------------------------------
"Those who never wander might be lost."

Working to be kind, aware, equanimous, and skilled at python.

**Comment by kchawla-pi** [comment]
Okay, I have come up with a test that is currently failing on master and passing on this branch. Should I'll push it here and we can subject it to the usual review. I'll incorporate any feedback and follow up.
@AlexandreAbraham This is your PR, if you wish to take over at any point, let me know.

**Comment by kchawla-pi** [comment]
This PR is based off a 3 year old Nilearn master. Hopefully it won't mess up the git history for this PR.

**Comment by kchawla-pi** [comment]
In the current Nilearn 'master', there are 2 `nilearn.tests.test_signal.test_clean_frequencies tests` . Which is wrong, means the first test is never run. How did that happen. Will fix it here or maybe another PR.

**Comment by kchawla-pi** [comment]
The test is ready for review.

**Comment by kchawla-pi** [comment]
I think this is ready as well. Will do one final check of test failing on master and passing here, then merge tomorrow.

**Pull request merged**
