### PR TITLE
Honor `simple` in plot_haxby_simple

### PR DESCRIPTION
**Pull request by fabianp**
The manual iteration on the cross validation loop seems overly complicated and error prone to me. Am I missing something ?

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
For many users this is easier to understand than "cross_val_score": cross_val_score seems magic to them.

**Comment by fabianp** [comment]
I think that manually iterating on the cross-validation is very error prone ... so not a good example ... but well if this was meant on purpose then nevermind.

**Comment by fabianp** [comment]
and btw cross_val_score is extensively used in other examples, so not very consistent either

**Comment by GaelVaroquaux** [comment]
> and btw cross_val_score is extensively used in other examples, so not very
> consistent either

This one is the simple :)

**Pull request closed without merging**
