### PR TITLE
[MRG] Maint: Replace nose with Pytest - 1 (Asserts, warns, raises)

### PR DESCRIPTION
**Pull request by kchawla-pi**
Partially addresses #2106 
This PR will focus on replacing nose tests calls for asserts, warns & raises.
The second PR will change the setup & teardown methods.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Any reason that this is still WIP?

**Comment by kchawla-pi** [comment]
I haven't yet replaced the current setup & teardown methods for mocking & temporary path. They depend on Nose.
This is not a release blocker.
I am thinking we should merge this in it's current form and tackle that in a separate PR. The changes in this PR are pretty rote but subsequent changes one will require some more tinkering. Might be too many things to review.
After the next version in released, I will merge this and open a Part Deux of this issue.

**Comment by kchawla-pi** [comment]
Once Nilearn 0.6.0 is released, I will resolve the conflicts in this one and merge it as part one of removing Nose.
In part two, I'll remove the setup & teardown methods.

**Comment by bthirion** [comment]
OK, sounds good.

**Comment by kchawla-pi** [comment]
This is ready for review @emdupre

**Pull request merged**
