### PR TITLE
[DOC] Fix doc building

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Fix doc build on main.

### CODE REVIEW

**Comment by NicolasGensollen** [comment]
@tsalo This is because the documentation doesn't build in strict mode in the PRs, but does on main.

**Review by bthirion — APPROVED** [review]
LGTM. At least the doc builds...

**Comment by tsalo** [comment]
>@tsalo This is because the documentation doesn't build in strict mode in the PRs, but does on main.

Thank you for the clarification! Should we switch to using strict mode on PRs then? It might reduce mistakes in PRs (at least in mine).

**Comment by bthirion** [comment]
The problem is that we're going to explode our CircleCI budget. I think that the problem is not too frequent.

**Comment by tsalo** [comment]
Oh, good point! I forgot about that issue.

**Comment by NicolasGensollen** [comment]
Thanks! Merging...

**Pull request merged**
