### PR TITLE
BF: Better error msg for empty mask

### PR DESCRIPTION
**Pull request by dohmatob**
Fixes issue #874

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
I thought that my proposed formulation was better :).

You didn't like it?

**Comment by AlexandreAbraham** [comment]
+1 for Gael's proposition

**Comment by dohmatob** [comment]
On Wed, Dec 2, 2015 at 4:54 PM, Gael Varoquaux <notifications@github.com>
wrote:

> I thought that my proposed formulation was better :).
>
> You didn't like it?
>
Oops! Sorry, I thought I copy pasted it :). Repairing...

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/pull/878#issuecomment-161342443>.
>



-- 
Elvis Dohmatob,
*sent from my  potato...*
http://dohmatob.blogspot.fr/, https://team.inria.fr/parietal/elvis/,
https://github.com/dohmatob

**Comment by GaelVaroquaux** [comment]
Merging. Thank you!

**Pull request merged**
