### PR TITLE
[DOC] Fix typos found by codespell

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
- A couple typos.

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Review by emdupre — APPROVED** [review]
Thank you, @DimitriPapadopoulos  !

**Comment by Remi-Gau** [comment]
sweet!!!

now I need to figure out why our codespell set up missed those!

**Comment by Remi-Gau** [comment]
OK no idea how you detected those changes but does not matter.

will add one commit to tweak the codespell config to ignore some temp files that may get generated

**Comment by DimitriPapadopoulos** [comment]
Yes, but I am always using the `master` branch locally, ahead of releases.

**Comment by Remi-Gau** [comment]
> Yes, but I am always using the `master` branch locally, ahead of releases.

ha ok makes more sense

**Pull request merged**
