### PR TITLE
move list of contributors from readme to authors.rst

### LINKED ISSUE #2601: list of developers in readme is outdated
also it would be easier to have only one such list (eg make sure authors.rst is complete and remove the list from readme)

### PR DESCRIPTION
**Pull request by jeromedockes**
Closes #2601  .

I have moved names listed in the README but not AUTHORS in a section "other contributors"; WDYT?

### CODE REVIEW

**Review by NicolasGensollen — CHANGES_REQUESTED** [review]
I think the list of other contributors is not rendered properly in the doc: [link](https://6361-1235740-gh.circle-artifacts.com/0/doc/_build/html/authors.html). 
I suppose that the name's first letter got interpreted as a list item marker.

**Comment by jeromedockes** [comment]
> I think the list of other contributors is not rendered properly in the doc: [link](https://6361-1235740-gh.circle-artifacts.com/0/doc/_build/html/authors.html). 
> I suppose that the name's first letter got interpreted as a list item marker.

Thanks!

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks!

_Note: If we want to include contributors explicitely in the README, we could use something like [this](https://github.com/all-contributors/all-contributors). Not sure this is what we want but it's worth mentioning it._

**Comment by bthirion** [comment]
See #1511

**Comment by jeromedockes** [comment]
> Note: If we want to include contributors explicitely in the README, we could use something like this. Not sure this is what we want but it's worth mentioning it.

that can be a good option. IMHO all the relevant information re authors is easily available in the git log and github issues and pr discussions so I don't really know what information we want explicitly in the readme and authors.rst ; the goal of this pr was just to have all in one place without changing the content

**Review by bthirion — APPROVED** [review]

**Comment by bthirion** [comment]
Indeed, we can merge that one, and see later for better ways to link to individual infrmation

**Comment by NicolasGensollen** [comment]
Merging... Thanks!

**Pull request merged**
