### PR TITLE
[FIX] LGTM.com recommendations

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Fix some LGTM.com recommendations:
https://lgtm.com/projects/g/nilearn/nilearn/?severity=recommendation

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
I'm not familiar with the `except Exception`
The result does not sound wrong...

**Comment by DimitriPapadopoulos** [comment]
[`Exception`](https://docs.python.org/3/library/exceptions.html#Exception) is the base class of the exceptions we want to catch:
> All built-in, non-system-exiting exceptions are derived from this class. All user-defined exceptions should also be derived from this class.

See rationale in [Except block handles '`BaseException`'](https://lgtm.com/rules/6780080/):
> All exception classes in Python derive from `BaseException`. `BaseException` has three important subclasses, `Exception` from which all errors and normal exceptions derive, `KeyboardInterrupt` which is raised when the user interrupts the program from the keyboard and `SystemExit` which is raised by the `sys.exit()` function to terminate the program.
> 
> Since `KeyboardInterrupt` and `SystemExit` are special they should not be grouped together with other `Exception` classes.
> 
> Catching `BaseException`, rather than its subclasses may prevent proper handling of `KeyboardInterrupt` or `SystemExit`. It is easy to catch `BaseException` accidentally as it is caught implicitly by an empty `except:` statement.

See also [PEP 0352](https://www.python.org/dev/peps/pep-0352/#exception-hierarchy-changes):
>With the exception hierarchy now even more important since it has a basic root, a change to the existing hierarchy is called for. As it stands now, if one wants to catch all exceptions that signal an error and do not mean the interpreter should be allowed to exit, you must specify all but two exceptions specifically in an `except` clause or catch the two exceptions separately and then re-raise them and have all other exceptions fall through to a bare `except` clause:
> ```python
> except (KeyboardInterrupt, SystemExit):
>     raise
> except:
>     ...
> ```
> That is needlessly explicit. This PEP proposes moving KeyboardInterrupt and SystemExit to inherit directly from BaseException.
> ```
> - BaseException
>   |- KeyboardInterrupt
>   |- SystemExit
>   |- Exception
>      |- (all other current built-in exceptions)
> ```

**Review by bthirion — APPROVED** [review]
Thx for the explanations.

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks!

**Comment by NicolasGensollen** [comment]
Merging, thanks!

**Pull request merged**
