### PR TITLE
still fixing issue #658

### PR DESCRIPTION
**Pull request by dohmatob**
See comments on issue #658

### CODE REVIEW

**Comment by AlexandreAbraham** [comment]
I passed a patch to fix the general issue of having 4 different lists so I don't think that your patch is necessary.

**Comment by lesteve** [comment]
For reference Alex's fix was here: https://github.com/nilearn/nilearn/commit/da17372b4f4947615bcf34d7e20c3335dd3326b0

Actually I think the problem is that the asarray doesn't have an explicit dtype. @AlexandreAbraham can you add it ?

**Comment by lesteve** [comment]
Oh and I forgot using 'i8' for the dtype is better than 'int' since it is more explicit. 'int' depends on the platform.

**Comment by AlexandreAbraham** [comment]
Honestly, these values are not even check. We could replace the whole think by range(40). Is it worth spending time on this issue?

**Comment by lesteve** [comment]
Good enough for now, thanks. Closing.

**Comment by dohmatob** [comment]
On Wed, Jul 15, 2015 at 2:09 PM, Alexandre Abraham <notifications@github.com
> wrote:

> Honestly, these values are not even check. We could replace the whole
> think by range(40).
>


> Is it worth spending time on this issue?
>
NO. I already told you guys we shouldn't spend more time on this but you
seemed to be having fun :p

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/pull/674#issuecomment-121595935>.
>



-- 
DED

**Comment by AlexandreAbraham** [comment]
OK so let's close it.

**Pull request closed without merging**
