### PR TITLE
[MRG] Broken link to MSDL atlas

### PR DESCRIPTION
**Pull request by megh1241**
Fixes issue #1483

### CODE REVIEW

**Comment by KamalakerDadi** [comment]
Could you please also fix the link in examples/03_connectivity/plot_probabilistic_atlas_extraction.py ?
Thanks

**Comment by KamalakerDadi** [comment]
I am waiting for circleci to green to check if there are any other links broken.

**Comment by KamalakerDadi** [comment]
Just a last comment. There are still few links which needs to fixed related to MSDL. Can you please address them also ?

What I have done is
git grep https://team.inria.fr/parietal/research/spatial_patterns/spatial-patterns-in-resting-state/

- doc/connectivity/functional_connectomes.rst: Fixed

- examples/01_plotting/plot_overlay.py: Needs to be fixed

- examples/03_connectivity/plot_inverse_covariance_connectome.py: Needs to be fixed

- examples/03_connectivity/plot_probabilistic_atlas_extraction.py: Fixed

- nilearn/datasets/description/msdl_atlas.rst: Needs to be fixed

**Comment by KamalakerDadi** [comment]
Thanks. LGTM.

**Comment by GaelVaroquaux** [comment]
LGTM. Merging

**Pull request merged**
