### PR TITLE
Replace NaNs with zeros in NiftiLabelsMasker

### LINKED ISSUE #2711: Ensure finite data (replace NaNs with zeros) in NiftiLabelsMasker
`NiftiMapsMasker` handles NaNs implicitly, while `NiftiLabelsMasker` does not. I think it just comes down to the following line:

https://github.com/nilearn/nilearn/blob/02e915accc1dd29ee8af0e92004eabb4f0393958/nilearn/regions/signal_extraction.py#L118

### Benefits to the change

I think the main benefit would be ensuring consistent behavior across Maskers, but it would also be helpful to retain signal from regions with some NaNs in the data.

### Pseudocode for the new behavior, if applicable

```python
import nibabel as nib
import numpy as np
from nilearn import datasets, input_data

img = datasets.load_mni152_brain_mask()
data = img.get_fdata()
# add NaN for test
data[52, 53, 71] = np.nan
# make 4d
data = data[..., None]
img_nan = nib.Nifti1Image(data, img.affine, img.header)

labels_atlas = datasets.fetch_atlas_aal()["maps"]

# Apply masker and check voxel of interest
labels_masker = input_data.NiftiLabelsMasker(labels_atlas)
labels_values = labels_masker.fit_transform(img_nan)
print(labels_values[0, :5])
```

> [0.94469654 0.90653653 0.95470964 0.96079882 0.99480789]

Instead of 

> [       nan 0.90653653 0.95470964 0.96079882 0.99480789]

### PR DESCRIPTION
**Pull request by tsalo**
Closes #2711.

Changes proposed in this pull request:

- Use `_safe_get_data`'s `ensure_finite` parameter to replace NaNs with zeros in the `NiftiLabelsMasker`. This matches the behavior of the `NiftiMapsMasker` and, most likely, the others as well.
- Add a warning to `_safe_get_data` when `ensure_finite` is used and non-finite values are detected in the data.

### CODE REVIEW

**Review by NicolasGensollen — APPROVED** [review]
This looks good to me!
Thanks! :+1:

**Review by bthirion — COMMENTED** [review]
LGTM. Deserves a whatsnew entry I think.

**Comment by tsalo** [comment]
Done! Thanks!

**Review by bthirion — APPROVED** [review]
Thx !

**Pull request merged**
