### PR TITLE
[WIP] Immigrate nistats as nilearn.stats

### LINKED ISSUE #2149: Incorporate GLM analysis functionality via Nistats
I am starting work on incorporating Nistats into Nilearn. 
There are some PRs open in Nisatts, but they are chugging along slowly & it is not prudent to wait for them. New issues & PRs keep adding to Nistats.

I will start the process of adding Nistats to Nilearn as `nilearn.stats` and update it with any merged PRs.

### PR DESCRIPTION
**Pull request by kchawla-pi**
Fixes #2149 

 - Remove Python 2, 3.4 compatibility.
 - Make it Pytest compatible.
 - Remove redundant components (sphinx_reporter).
 - Merge similar modules/packages (ex: datasets, reporting)

### CODE REVIEW

**Comment by kchawla-pi** [comment]
@GaelVaroquaux Nistats needs `patsy` as a dependency. I will add that to the CI to continue with the PR. If you have contrary thoughts, share them here.

**Comment by jeromedockes** [comment]
> Hum, this requires thoughts. I can see this being problematic.

Note that only the linear_constraint of patsy's DesignInfo is used, to
parse contrast specifications such as "face - house".
maybe what we need can be implemented reasonably easily using pandas'
eval or the helpers on which it relies.

**Comment by bthirion** [comment]
Indeed. I'm not aware about pandas-absed solutions but the need for patsy is indeed fairly limited.
B

**Comment by jeromedockes** [comment]
maybe something as simple as the following would be a start?

```python
>>> import numpy as np 
... import pandas as pd 
...  
... columns = list("abcde") 
... df = pd.DataFrame(np.eye(5), columns=columns, index=columns) 
... df.eval("b + 3 * (a - d / 10)").values 
...                                                                                                                                      
array([ 3. ,  1. ,  0. , -0.3,  0. ])
```

**Comment by bthirion** [comment]
> maybe something as simple as the following would be a start?
> 
> ```python
> >>> import numpy as np 
> ... import pandas as pd 
> ...  
> ... columns = list("abcde") 
> ... df = pd.DataFrame(np.eye(5), columns=columns, index=columns) 
> ... df.eval("b + 3 * (a - d / 10)").values 
> ...                                                                                                                                      
> array([ 3. ,  1. ,  0. , -0.3,  0. ])
> ```

Should we do that in Nistats ?

**Comment by jeromedockes** [comment]
> Should we do that in Nistats ?

I opened a PR in https://github.com/nistats/nistats/pull/399

**Comment by jeromedockes** [comment]
https://github.com/nistats/nistats/issues/398#issuecomment-567010272

**Pull request closed without merging**
