### PR TITLE
[DOC] add youtube channel in the doc footer

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes none

Changes proposed in this pull request:

- make sure the Nilearn youtube channel is listed in the doc

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
I don't see youube in the footer of the artefacts. Maybe we should first trigger a doc rebuild.

**Comment by Remi-Gau** [comment]
Not super obvious... But it is there.

Screenshot from 2024-10-02 16-39-59

Let me check if I can add color to the icons.

**Comment by bthirion** [comment]
My bad, I did not identify the logo.

**Review by bthirion — APPROVED** [review]

**Comment by Remi-Gau** [comment]
OK this one is small enough and has very low impact so a single review should be enough

**Pull request merged**
