### PR TITLE
Remove deprecated function `fetch_nyu_rest`

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Function `fetch_nyu_rest` is deprecated since release 0.6.2 and scheduled to be removed in 0.8.

### CODE REVIEW

**Comment by bthirion** [comment]
CI errors are unrelated ?

**Comment by NicolasGensollen** [comment]
>CI errors are unrelated ?

Yes, everything is running fine now.

**Review by bthirion — APPROVED** [review]
I love removing code :-)

**Review by jeromedockes — APPROVED** [review]
great, thanks!

**Pull request merged**
