### PR TITLE
Updates to Travis & Anaconda links; TravisCI failure fix

### PR DESCRIPTION
**Pull request by kchawla-pi**
- Added test to TravisCI for py3.7
 - setup.py now lists support for python 3.6, 3.7
 - Anaconda download link updated

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
LGTM. I'll wait for the tests to pass, but it is fine for me.

After the release we should remove at least one of the test runner on 2.7, to decrease wait times on having the tests running the CI.

**Comment by KamalakerDadi** [comment]
>After the release we should remove at least one of the test runner on 2.7,

+1

**Comment by kchawla-pi** [comment]
Concur. I am waiting for the release as well.

**Comment by GaelVaroquaux** [comment]
We're making good progress toward the release currently!!

**Comment by GaelVaroquaux** [comment]
CircleCI failed because of the localizer download. I am merging this guy anyhow.

**Comment by kchawla-pi** [comment]
> CircleCI failed

:-/

**Pull request merged**
