### PR TITLE
[EHN] Implement signal.clean to SurfaceMasker

### PR DESCRIPTION
**Pull request by htwangtw**
- Closes #

Changes proposed in this pull request:

This is an initial attempt to implement signal.clean to SurfaceMasker.
Concerns (generalisable to niftimaskers):
 - clean_kwargs - should filter out confounds and sample mask to prevent
user adding those parameters upon creating the masker
 - all the cleaning related parameters - what do we want to choose to
expose?

If we set on the solution I will expand this to `SurfaceLabelsMasker`

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
Looks good so far.

**Comment by bthirion** [comment]
You probably want to add tests ?

**Comment by htwangtw** [comment]
> You probably want to add tests ?
When I look at the `NiftiMasker` objects, it seems that they deliberately did not test out all the signal cleaning part and just assumed all the parameters are passed to `signal.clean` correctly. 
I am not sure what's the best thing to do.

**Review by ymzayek — APPROVED** [review]
LGTM!

**Review by bthirion — APPROVED** [review]
Thx !

**Comment by htwangtw** [comment]
merging...

**Comment by ymzayek** [comment]
linking to #4027 to keep track

**Pull request merged**
