### PR TITLE
FIX expand user path in glob

### LINKED ISSUE #811: Globbing should expand user.
Globbing is good but we should also expand `~` to user home directory.

### PR DESCRIPTION
**Pull request by aabadie**
This should fix #811.

### CODE REVIEW

**Comment by AlexandreAbraham** [comment]
LGTM.

**Comment by GaelVaroquaux** [comment]
LGTM, but it needs a documentation.

**Comment by aabadie** [comment]
> LGTM, but it needs a documentation.

will add it asap

**Comment by GaelVaroquaux** [comment]
One more thing:

http://nilearn.github.io/introduction.html#your-first-steps-with-nilearn

Could you add a sidebar (restructured text directive 'sidebar') next to
the plot that says:

'The filename could be given as "~/t_map000.nii' as nilearn expands "~"
to the home directory. See more on file name matchings.'

Last sentence being a link to the relevant part of the documentation.

**Comment by aabadie** [comment]
> One more thing

Done !

**Comment by GaelVaroquaux** [comment]
Thanks! Merging.

**Pull request merged**
