### PR TITLE
[STY] Multiple imports for an import name

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Not sure about the reimports under [`examples`](https://github.com/nilearn/nilearn/tree/main/examples). Were they added for didactic purposes?

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Comment by Remi-Gau** [comment]
> Were they added for didactic purposes?

I doubt it: I think they are the result of multiple rewrites and churn.
I'd prefer to have all imports at the top of the example (in a typical script like fashion) rather than right before first usage (in jupyter notebook fashion) to avoid such problems but that's a discussion for another issue.

BTW how did you catch those? I don't doubt your eagle-eye superpowers 🦅 👁️ but if you have some tips I would not mind.

**Review by Remi-Gau — APPROVED** [review]

**Comment by DimitriPapadopoulos** [comment]
I have been using https://app.deepsource.com/gh/DimitriPapadopoulos/nilearn.

This linter mostly reuses opensource linters as far as I can tell. Many issues translate into ruff rules, but strangely this repository has lots of issues that have not been implemented in ruff yet. For example, this `PYL-W0404` issue is the Pylint warning [reimported / W0404](https://pylint.readthedocs.io/en/stable/user_guide/messages/warning/reimported.html), which has not been implemented in ruff as a [PLW](https://docs.astral.sh/ruff/rules/#warning-w_1) rule yet.

**Comment by Remi-Gau** [comment]
nice!
thanks for the tip!

I have been meaning to implement some of the refactoring suggested by sourcery but have not had the time yet: https://sourcery.ai/

**Pull request merged**
