### PR TITLE
[MAINT] numpy types deprecations

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Update some of the numpy types as to remove part of the deprecation warnings.

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
LGTM, Thx !  There seem to be a Codecov complaint ...

**Comment by NicolasGensollen** [comment]
Not sure why codecov was complaining since this line wasn't tested before... 
Although this is unrelated to this PR, I added a small test in a0b14c7 to have this covered.

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Comment by NicolasGensollen** [comment]
Thanks! Merging...

**Pull request merged**
