### PR TITLE
DOC: Switch to napoleon

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
To have better rendering of attributes

Napoleon is a docstring-formatter maintained by sphinx, which is quite robust.

### CODE REVIEW

**Comment by bthirion** [comment]
Will merge tomorrow unless I hear otherwise.

**Comment by GaelVaroquaux** [comment]
Yes. This is finally right. It was a bit of a struggle.

I couldn't use napoleon (it emits too many warnings, and I couldn't fix them), but I still was able to fix some rendering problems of the docstrings.

However, some of the rendering problems have been introduced by the recent releases of numpydoc. I added CSS to work around them. A cleaner fix would require us to rewrite all our docstrings to follow the evolution of the standard :(.

**Comment by bthirion** [comment]
> A cleaner fix would require us to rewrite all our docstrings to follow the evolution of the standard :(.

Which we'll have to do eventually... Thx ! 
I'm OK for merging. No afterthought ?

**Comment by GaelVaroquaux** [comment]
> I'm OK for merging. No afterthought ?

Nope, go ahead!

**Comment by bthirion** [comment]
Thx, merged !

**Pull request merged**
