### PR TITLE
embellished CanICA example

### PR DESCRIPTION
**Pull request by banilo**
Show all components in a single 20-item subplot, rather than a series of component plot.

### CODE REVIEW

**Comment by lesteve** [comment]
In general I am not 100 % convinced by cosmetic changes like this in the examples. IMHO it obfuscates them slightly by adding some boiler-plate plotting code that is not directly relevant to the functionality that the example is supposed to demonstrate.

Also something we need to remember each time we change an example is to make sure this doesn't affect the documentation. In this particular case one of the ICA plot is in the website home page carousel. It is also used in other places, for example try `git grep 'plot_canica.*\.png'` for the complete list.

**Comment by GaelVaroquaux** [comment]
I have the same feeling as @lesteve, though it is not a strong opinion.

**Comment by banilo** [comment]
hmm... I see your points

**Comment by lesteve** [comment]
closing this one.

**Pull request closed without merging**
