### PR TITLE
FIX: Travis failures with recent NumPy release 1.13.0

### PR DESCRIPTION
**Pull request by KamalakerDadi**
- Fixes are related to numpy boolean type operations. Where recommended
 solutions are to use numpy functions on arrays.

See for instance in PR #1462 with this link
https://travis-ci.org/nilearn/nilearn/jobs/241458725

Can I have reviews on this please ?

### CODE REVIEW

**Comment by KamalakerDadi** [comment]
Recent commit should FIX failure in CircleCI with sphinx version 1.6.2

**Comment by bthirion** [comment]
Nothing to say about he updates, but circleci fails ?

**Comment by KamalakerDadi** [comment]
>Nothing to say about he updates, but circleci fails ?

Still there are some documentation build failures. I will address them as well. Below is the one with failure (decoding).
```sphinx.errors.SphinxWarning: /home/ubuntu/nilearn/doc/decoding/decoding_intro.rst:423:end-before pattern not found:```

**Comment by bthirion** [comment]
Nothing to argue about he updates, but circleci fails ?

**Comment by KamalakerDadi** [comment]
> but circleci fails ?

No, it is fixed now.

**Comment by KamalakerDadi** [comment]
Summarizing altogether, this PR attempts to FIX:

- Fixes are related to numpy boolean type operations. Where recommended
  solutions are to use numpy functions on arrays.
  See for instance in PR #1462 with this link https://travis-ci.org/nilearn/nilearn/jobs/241458725
- Should also FIX failure in CircleCI with sphinx updated to version 1.6.2.
   See for instance in https://circleci.com/gh/nilearn/nilearn/2514?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
- Few fixes with documentation build errors. ```region_extraction.rst```, ```decoding_intro.rst```, ```manipulating_images.rst```

Can I have reviews on this please ?

**Comment by GaelVaroquaux** [comment]
LGTM. Thank you. Merging.

**Pull request merged**
