### PR TITLE
[MRG] DOC : removing duplicated documentation files for datasets

### PR DESCRIPTION
**Pull request by aabadie**
I found that datasets rst files where duplicated in 2 different places in nilearn code base : nilearn/description and nilearn/datasets/description. I kept the latter as it's used in the get datasets function docstring.

### CODE REVIEW

**Comment by lesteve** [comment]
oasis1 should probably be called oasis1.rst. Double check by using nilearn.dataset.fetch_oasis_vbm() and checking that the returned bunch has a non empty .description field.

**Comment by aabadie** [comment]
@lesteve the description was indeed empty. Renaming to oasis.rst fixed the issue.

**Comment by lesteve** [comment]
Can you add a test for oasis similary to what @AlexandreAbraham has done in #802?

**Comment by lesteve** [comment]
I'll add the test myself directly in master.

**Comment by KamalakerDadi** [comment]
I will add it anyway I am adding to megatrawls

**Comment by lesteve** [comment]
> I will add it anyway I am adding to megatrawls

No need to worry about that, I have already done it in 8270851.

**Pull request merged**
