### PR TITLE
[ENH] Move FSL- and BIDS-related functions to interfaces module

### LINKED ISSUE #3118: Move BIDS- and FSL-related functions from `_utils` to `interfaces` module
There are three functions in `nilearn._utils.glm` that I think could be moved to the new `nilearn.interfaces` module:

- [`nilearn._utils.glm.get_bids_files()`](https://github.com/nilearn/nilearn/blob/276959dd98d8ec6d2997680c0a5a9669e5c4d124/nilearn/_utils/glm.py#L338)
- [`nilearn._utils.glm.parse_bids_filename()`](https://github.com/nilearn/nilearn/blob/276959dd98d8ec6d2997680c0a5a9669e5c4d124/nilearn/_utils/glm.py#L434)
- [`nilearn._utils.glm.get_design_from_fslmat()`](https://github.com/nilearn/nilearn/blob/276959dd98d8ec6d2997680c0a5a9669e5c4d124/nilearn/_utils/glm.py#L479)

All three are user-facing functions, but since they're in the `_utils` module I believe the consensus is that they can be moved without issue.

This is related to #3014.

### Benefits to the change

Moving these functions would help fill out the new `interfaces` module, and would ensure that they stay relatively stable for users.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #3118.

Changes proposed in this pull request:

- Create new `nilearn.interfaces.bids` submodule.
- Create new `nilearn.interfaces.fsl` submodule.
- Move `nilearn._utils.glm.get_bids_files()` to `nilearn.interfaces.bids.get_bids_files()`.
- Move `nilearn._utils.glm.parse_bids_filename()` to `nilearn.interfaces.bids.parse_bids_filename()`.
- Move `nilearn._utils.glm.get_design_from_fslmat()` to `nilearn.interfaces.fsl.get_design_from_fslmat()`.
- Add a whatsnew entry about the addition of the new functions. Technically they're not being "added", but they were originally stored in a private module, so I'm not sure if it counts as a reorganization from the user's perspective.
- Add the new functions to the reference page.

### CODE REVIEW

**Comment by bthirion** [comment]
LGTM so far, thx.

**Review by NicolasGensollen — COMMENTED** [review]
LGTM so far, thanks @tsalo !
The CircleCI failure is unrelated. We should merge fix #3124 
Also, I think we should make sure we are OK with current names (for the functions but also their parameters and so on...). As @jeromedockes said, once these are public, it'll be much more difficult to modify them.

**Comment by bthirion** [comment]
Shouldn't we maintain the previous functions, for the sake of bw compatibility ?
The PR looks great otherwise.

**Comment by jeromedockes** [comment]
> Shouldn't we maintain the previous functions, for the sake of bw compatibility ?

As they were in the "private" `_utils` module, I don't think we need to.

> The PR looks great otherwise.

Agreed!

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks @tsalo !

**Comment by NicolasGensollen** [comment]
Thanks @tsalo !
Merging...

**Pull request merged**
