### PR TITLE
[REF] refactor nibabel import

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes none but relates to https://github.com/nilearn/nilearn/pull/4446#discussion_r1721349617

Changes proposed in this pull request:

- replace `import nibabel` by `import nibabel as nib` or by loading only the required modules, classes or functions
- where possible replace the `nibabel.save` with the relevant `to_filename()` method

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Comment by Remi-Gau** [comment]
@man-shu
Let me know if this one looks good to you.

It should not be too controversial.

**Review by man-shu — APPROVED** [review]
Looks good!

**Comment by Remi-Gau** [comment]
ok this broke one of the dataset fetcher that gets SPM data in analyze format rather than nifti.

actually the SPM team has BIDS version of this dataset so it may be better to fetch this version in the future

**Comment by bthirion** [comment]
Sorry, but can you fix the SPM data handling meanwhile ?

**Comment by Remi-Gau** [comment]
> Sorry, but can you fix the SPM data handling meanwhile ?

yup #4508 should revert the problematic change for now

**Pull request merged**
