### PR TITLE
regression test for colorbar

### PR DESCRIPTION
**Pull request by banilo**
Related to #510

Has the works-on-my-machine certificate, but perhaps makes Travis break?

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Maybe I diagnosed the problem wrong (I was in a rush). Maybe the problem is that the colorbar breaks when the map is only made of zeros.

**Comment by GaelVaroquaux** [comment]
> Maybe I diagnosed the problem wrong (I was in a rush). Maybe the problem is
> that the colorbar breaks when the map is only made of zeros.

Confirmed: I had a better look at the image on which I am getting this
problem, and its complete span (min and max) is zero.

**Comment by banilo** [comment]
This avoids the crash, but the underlying question is: Doe sit make sense to show a colorbar in the first place, if the image data contains only a single value, such as zero?

**Comment by GaelVaroquaux** [comment]
I think it's fine. We absolutely want to avoid the crash, for the user's comfort.

**Comment by banilo** [comment]
> I think it's fine.

Ok, cleaned up.

**Pull request merged**
