### PR TITLE
PR trying to address removing deprecated functions of atlas fetcher

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Removing deprecated function names according to latest release:

``` python
* fetch_msdl_atlas
* fetch_craddock_2012_atlas
* fetch_harvard_oxford
* fetch_smith_2009
* fetch_yeo_2011_atlas
* fetch_atlas_aal_spm_12
```

### CODE REVIEW

**Comment by lesteve** [comment]
You may want to add an entry in whats_new.rst.

In scikit-learn IIRC, they have a policy of two releases with DeprecationWarning before removal. Maybe we want to do the same in nilearn.

**Comment by KamalakerDadi** [comment]
> In scikit-learn IIRC, they have a policy of two releases with DeprecationWarning before removal. Maybe we want to do the same in nilearn

I will add in 0.2.1 section saying that functions are deprecated and removed. ?

**Comment by GaelVaroquaux** [comment]
> In scikit-learn IIRC, they have a policy of two releases with
> DeprecationWarning before removal. Maybe we want to do the same in nilearn.

Indeed, I am afraid that this is a bit fast.

**Comment by KamalakerDadi** [comment]
I have acted according to the deprecated warning ```'will be removed in nilearn 0.1.5'``` ? We are in 0.2.1 version which means we already crossed the version according to the message.

**Comment by lesteve** [comment]
Looking at https://github.com/nilearn/nilearn/blob/0.1.4/nilearn/datasets.py, the deprecation was added in 0.1.4, which means that the DeprecationWarning has been in 0.1.4 and 0.2. It's fine to remove it then.

**Comment by lesteve** [comment]
LGTM, merging thanks !

**Pull request merged**
