### PR TITLE
Import ABC from collections.abc instead of collections for Python 3.9 compatibility.

### PR DESCRIPTION
**Pull request by tirkarthi**

### CODE REVIEW

**Comment by tirkarthi** [comment]
This unblocks https://bugzilla.redhat.com/show_bug.cgi?id=1799941

**Comment by tirkarthi** [comment]
Yes, this is compatible from 3.4 and above.

**Comment by GaelVaroquaux** [comment]
@bthirion : we have Python 3.5 in our tests (the good old rule is: "if it ain't test, it's broken")

**Comment by tirkarthi** [comment]
Thank you for review and merge.

**Pull request merged**
