### PR TITLE
Update html_surface.py

### LINKED ISSUE #3500: Renaming plotting.html_surface.one_mesh_info() and plotting.html_surface.full_brain_info()
This is a follow-up issue from #3173.

`plotting.html_surface.one_mesh_info()` and `plotting.html_surface.full_brain_info()` should be renamed to `plotting.html_surface._one_mesh_info()` and `plotting.html_surface._full_brain_info()` respectively so that it becomes explicit that they're not in the public API.

### PR DESCRIPTION
**Pull request by mehrdadbn9**
closes #3500 
please check it

### CODE REVIEW

**Comment by alexisthual** [comment]
Thanks for opening this @mehrdadbn9!

Here is some kind feedback:
* it's better if you open this PR with a message saying "Closes #3500" or something similar suggested by Github ; this way, when this PR gets merged, the linked issue will automatically be closed.
* as you can see, due to the changes you made in this PR, some tests of the codebase now fail, so we won't merge your PR as is.

You should have a look at the failing tests to see what should be fixed. If you need some help, you can have a peak at the following hint, but I think it's worth trying without it.
<details>
<summary>See hint</summary>
<p>

Several tests fail with `AttributeError: module 'nilearn.plotting.html_surface' has no attribute 'one_mesh_info'`.
This is because the functions you renamed are used elsewhere in the codebase, and therefore you should rename them there as well.

</p>
</details>

**Review by mehrdadbn9 — COMMENTED** [review]
tried to fix code coverage

**Comment by mehrdadbn9** [comment]
@ymzayek  i think it didn't work

**Comment by ymzayek** [comment]
Hi @mehrdadbn9 sorry if I wasn't clear. You should leave the original function untouched except for changing it's name by adding the underscore. Then under this you will define a new function which is basically what I wrote in code block in the comment above. What I'm doing there is defining a new function called `one_mesh_info` that calls the renamed function `_one_mesh_info`.

**Comment by mehrdadbn9** [comment]
@ymzayek 
oh you are right so as i understood i should firstly define a private def and another definition without underscore that re turn private def when it is called.

**Comment by ymzayek** [comment]
> oh you are right so as i understood i should firstly define a private def and another definition without underscore that re turn private def when it is called.

@mehrdadbn9 yes exactly. The original function can just be renamed to make it private by adding the underscore and nothing else should change under that function. Then a new function named without the underscore will spit a warning and call the private function.

**Pull request closed without merging**
