### PR TITLE
[MAINT] Update config for formatting of nilearn/datasets

### PR DESCRIPTION
**Pull request by Remi-Gau**
Relates https://github.com/nilearn/nilearn/issues/2528

Splinter of https://github.com/nilearn/nilearn/pull/3624

Changes proposed in this pull request:

Changes proposed in this pull request:

- [x] update files include in pre-commit config
- [x] update files excluding in pre-commit
- [x] update flake8 / isort CI

to be merged after:
- #3689
- #3690
- #3691
- #3692 
- #3693
- #3694 
- #3695 
- #3696

### CODE REVIEW

**Comment by Remi-Gau** [comment]
closes #3624 as this is the last PR that it was split into.

**Comment by Remi-Gau** [comment]
will fix remaining flake8 issues in this PR: probably style regressions from other PR.

**Review by bthirion — APPROVED** [review]
LGTM, but beware the MacOS failure.

**Comment by Remi-Gau** [comment]
Thanks for catching this @bthirion

Ok this seems to be the second occurrence of
this flaky test. 

https://github.com/nilearn/nilearn/issues/3573

Will reopen the issue but I still have no idea what could be causing this.

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks @Remi-Gau !

**Comment by Remi-Gau** [comment]
> LGTM, but beware the MacOS failure.

Thanks for catching this one. @bthirion.
Seems unrelated. Need to check if this is not related to this flaky test I noticed a couple of months ago.

**Pull request merged**
