### PR TITLE
[INFRA] Remove CI workflow to error on DeprecationWarnings of dependencies

### PR DESCRIPTION
**Pull request by ymzayek**
- Closes None

Changes proposed in this pull request:

- Remove monthly CI to error on external DeprecationWarnings

This job doesn't work very well. I think there might be a better way to manage this with tox. I suggest to remove for now. Also, we are pretty up-to-date on handling deprecations

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
I have no personal opinion on this. What is the motivation for removing it ?

**Comment by ymzayek** [comment]
At the moment it's failing on a deprecation warning that would need to be handled by an external library. It's purpose was to notify us about deprecation warnings that we actually need to handle ourselves before they even fail on new releases or even pre releases of our dependencies. In any case removing it is not risky for us and we still have the python 3.12 job with pre releases that will fail if we have deprecated code associated with a pre release of one of our dependencies and that's usually handled quickly enough

**Comment by Remi-Gau** [comment]
Definitely low risk to remove. 

Chekcing the latest runs:
https://github.com/nilearn/nilearn/actions/workflows/check_deprecations.yml

Last one could not even start and the one before that did catch a few things though.

Would it be worth thinking of better ways to replace it (as part of this PR or another?)

**Comment by ymzayek** [comment]
Yes let's do it in another PR I would say. I can reopen the original issue.

> Last one could not even start and the one before that did catch a few things though.

The one before seems to only have caught internal deprecation warnings (the _LEGACY_FORMAT_MSG) which is also not the purpose of this workflow

**Comment by Remi-Gau** [comment]
Ok let's merge this and reopen the old issue then.

**Review by bthirion — APPROVED** [review]
Thx for the explanations.

**Review by Remi-Gau — APPROVED** [review]

**Pull request merged**
