### PR TITLE
[MRG] forward session to _fetch_file in _fetch_files

### LINKED ISSUE #2863: Datasets file fetcher does not respect `requests.Session` instance
When providing a `requests.Session` instance to the `session` argument of `nilearn.datasets.utils._fetch_files()` the session instance is not passed through to the calls to `nilearn.datasets.utils._fetch_file()` so any e.g., header information that should be sent with the requests is lost. While these functions accept `username` and `password` arguments for basic authentication, it's unclear how to provide e.g., token-based authentication without the ability to directly pass a session instance.

Nilearn version: 0.7.1

### Expected behavior

Passing a `requests.Session` instance to the `session` keyword of `nilearn.datasets.utils._fetch_files()` should cause any header information stored in the session instance to be used when fetching the requested files.

### Actual behavior

The `session` argument of `nilearn.datasets.utils._fetch_files()` is entirely ignored.

### Steps and code to reproduce bug

Since the issue I'm running into is in providing token-based authentication via the session header this isn't a functional MWE but should hopefully highlight the issue:

```python
>>> import requests
>>> from nilearn.datasets.utils import _fetch_files
>>> session = requests.Session()
>>> session.headers['Authentication'] = 'Bearer TOKEN'
>>> _fetch_files('/tmp', files=('filename.txt', 'https://authenticationrequired.com/filename.txt', {}), session=session) 
```

The last line will raise the error:

```python-traceback
~/lib/python3.8/site-packages/nilearn/datasets/utils.py in _fetch_files(data_dir, files, resume, verbose, session)
    776             md5sum = opts.get('md5sum', None)
    777 
--> 778             dl_file = _fetch_file(url, temp_dir, resume=resume,
    779                                   verbose=verbose, md5sum=md5sum,
    780                                   username=opts.get('username', None),

~/lib/python3.8/site-packages/nilearn/datasets/utils.py in _fetch_file(url, data_dir, resume, overwrite, md5sum, username, password, verbose, session)
    614             with session.send(
    615                     prepped, stream=True, timeout=_REQUESTS_TIMEOUT) as resp:
--> 616                 resp.raise_for_status()
    617                 with open(temp_full_name, "wb") as fh:
    618                     _chunk_read_(resp, fh, report_hook=(verbose > 0),

~/lib/python3.8/site-packages/requests/models.py in raise_for_status(self)
    941 
    942         if http_error_msg:
--> 943             raise HTTPError(http_error_msg, response=self)
    944 
    945     def close(self):

HTTPError: 401 Client Error: Unauthorized for url: https://authenticationrequired.com/filename.txt
```

### Potential fix

Adding `session=session` to the following call in `nilearn.datasets.utils._fetch_files()` should remedy the issue:

https://github.com/nilearn/nilearn/blob/dbbd221e3633c97464034c5366faa548728c9999/nilearn/datasets/utils.py#L778-L782

I recognize this isn't a user-facing function but given the keyword parameter is in the function signature and you [make a point of re-calling the function with a `requests.Session` instance if one isn't provided](https://github.com/nilearn/nilearn/blob/dbbd221e3633c97464034c5366faa548728c9999/nilearn/datasets/utils.py#L726-L731) makes it seem like it should be respected.

---

Let me know if you have any questions about this and, as always, thanks for the great package! :sparkles:

### PR DESCRIPTION
**Pull request by jeromedockes**
closes #2863

### CODE REVIEW

**Comment by jeromedockes** [comment]
the linalg error : singular matrix is unrelated to this change

**Review by bthirion — APPROVED** [review]
LGTM

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks!

**Comment by jeromedockes** [comment]
thanks, merging

**Pull request merged**
