### PR TITLE
[STY] Apply ruff/flake8-implicit-str-concat rules (ISC)

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Review by Remi-Gau — CHANGES_REQUESTED** [review]
I like this especially that I have had to fix things that manually before.

Can you update the pyproject.toml to add the rule to the ruff config?

**Comment by DimitriPapadopoulos** [comment]
In theory, `ISC1001` and `ISC002` rules are part of the [conflicting lint rules](https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules) to avoid when using Ruff as a formatter. More details in https://github.com/astral-sh/ruff/issues/8272. In practice, I've never seen conflicts.

That's why I haven't enforced `ISC` rules.

**Comment by DimitriPapadopoulos** [comment]
See #4753.

**Review by Remi-Gau — APPROVED** [review]

**Comment by Remi-Gau** [comment]
> In theory, `ISC1001` and `ISC002` rules are part of the [conflicting lint rules](https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules) to avoid when using Ruff as a formatter. More details in [astral-sh/ruff#8272](https://github.com/astral-sh/ruff/issues/8272). In practice, I've never seen conflicts.
> 
> That's why I haven't enforced `ISC` rules.

ah I see
I did not know that: thanks for the explanation!!! 🙏🏽 

will merge as is as the changes are small and uncontroversial

**Pull request merged**
