### PR TITLE
FIX: plot_brain_schematics bug with black background

### PR DESCRIPTION
**Pull request by robbisg**
#1094

### CODE REVIEW

**Comment by lesteve** [comment]
Thanks a lot for your PR!

Your fix is not compatible with previous matplotlib versions since `ax.get_axis_bgcolor()` is going to return 'k' and not a rgba tuple. Maybe there is a more robust way to compare colours in matplotlib, not sure.

**Comment by AlexandreAbraham** [comment]
Why not `colors.colorConverter.to_rgba(ax.get_axis_bgcolor()) == colors.colorConverter.to_rgba('k')` ?

**Comment by lesteve** [comment]
> Why not colors.colorConverter.to_rgba(ax.get_axis_bgcolor()) == colors.colorConverter.to_rgba('k') ?

That will probably work, but maybe matplotlib provides a slightly more elegant way to compare colors?

**Comment by robbisg** [comment]
I suppose it was a matplotlib problem! 
I don't know if there is a more robust fix, it fixed my problem.
Furthermore as stated by matplotlib `MatplotlibDeprecationWarning: The get_axis_bgcolor function was deprecated in version 2.0. Use get_facecolor instead.` but also `get_facecolor` gives the rgba tuple!

**Comment by AlexandreAbraham** [comment]
>  maybe matplotlib provides a slightly more elegant way to compare colors

Not that I know of.

> MatplotlibDeprecationWarning: The get_axis_bgcolor function was deprecated in version 2.0. Use get_facecolor instead.

Nilearn is compatible with older versions than 2.0. We should probably make two codepaths depending on the version.

**Comment by lesteve** [comment]
> Not that I know of.

OK then using `to_rgba` on both sides of the `==` sign seems good enough. Can you do that @robbisg ?

**Comment by robbisg** [comment]
So the line @AlexandreAbraham suggests `colors.colorConverter.to_rgba(ax.get_axis_bgcolor()) == colors.colorConverter.to_rgba('k')`?

**Comment by lesteve** [comment]
The Travis error is spurious (still the memory usage thing misbehaving from time to time @aabadie FYI).

Merging this one, thanks !

**Pull request merged**
