### PR TITLE
[MRG+1] Change the downloader test to rely on craddock instead of haxby

### PR DESCRIPTION
**Pull request by AlexandreAbraham**
Fixes the downloader test as discussed in #1141.

I also added extra documentation to detail what is tests and how.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
This seems overall good. Thanks a lot. However, the test is failing on the CI.

**Comment by AlexandreAbraham** [comment]
Oops, the essential file was git ignored, fixed !

**Comment by GaelVaroquaux** [comment]
LGTM!

+1 for merge.

**Comment by AlexandreAbraham** [comment]
Given that this is a very specific test and that nobody will probably comment it, merging too.

**Pull request merged**
