### PR TITLE
[MAINT] Update jquery version

### PR DESCRIPTION
**Pull request by NicolasGensollen**
This PR proposes to update the version for `jquery.min.js` from 3.3.1 to 3.6.0.
See this [alert](https://github.com/nilearn/nilearn/security/dependabot/nilearn/plotting/data/js/jquery.min.js/jquery/open) where the suggested fix is to update to 3.5.0 or later.

### CODE REVIEW

**Comment by KamalakerDadi** [comment]
Great!

I guess we need to do each time whenever we receive this warning?

**Comment by NicolasGensollen** [comment]
>I guess we need to do each time whenever we receive this warning?

Once we update the jquery version, we shouldn't get this exact warning anymore since the vulnerability issues were patched in 3.5.0.

**Comment by KamalakerDadi** [comment]
I guess we need to do each time whenever we receive this warning?

>Once we update the jquery version, we shouldn't get this exact warning anymore since the vulnerability issues were patched in 3.5.0.

Also, I would do simple visualization checks that are linked to this jsscript. Just to be sure. As CircleCI full cannot show this interactively.

**Comment by NicolasGensollen** [comment]
>Also, I would do simple visualization checks that are linked to this jsscript. Just to be sure. As CircleCI full cannot show this interactively.

Yes, I didn't notice any difference. 

I'm gonna go ahead and merge this, thanks for the reviews!

**Pull request merged**
