### PR TITLE
[MRG+1] fixing plot_mixed_gambles_space_net.py decoding example

### LINKED ISSUE #999: plot_mixed_gambles_space_net if broken on Python 3
Simple Python 3 glitch:
```
Traceback (most recent call last):
  File "/home/arthur/work/repos/nilearn/examples/02_decoding/plot_mixed_gambles_space_net.py", line 16, in <module>
    data = fetch_mixed_gambles(n_subjects=16)
  File "/home/arthur/work/repos/nilearn/nilearn/datasets/func.py", line 1285, in fetch_mixed_gambles
    X, y, mask_img = _load_mixed_gambles(map(nibabel.load, data.zmaps))
  File "/home/arthur/work/repos/nilearn/nilearn/datasets/func.py", line 1209, in _load_mixed_gambles
    mask = np.sum(mask, axis=0) > .5 * len(zmap_imgs)
TypeError: object of type 'map' has no len()
```

### PR DESCRIPTION
**Pull request by aabadie**
While working on #1000, I encountered this reported issue. This fix #999.

### CODE REVIEW

**Comment by aabadie** [comment]
For the record, the issue is that `zmap_imgs` is a `map` and len(map) is not allowed in py3. But looking at the code above this change, mask has the same length.

**Comment by lesteve** [comment]
The Python2/Python3 inconsistency comes from this [line](https://github.com/nilearn/nilearn/blob/418b646aa6689f94d9aed7b20f9f976fa78ec2d9/nilearn/datasets/func.py#L1294):

```python
X, y, mask_img = _load_mixed_gambles(map(nibabel.load, data.zmaps))
```

A simple fix would be to useuse a list comprehension.

```python
X, y, mask_img = _load_mixed_gambles([nibabel.load(each) for each in data.zmaps])
```

Maybe there is one of the check_niimg_ helper we can use too, not sure.

**Comment by aabadie** [comment]
Indeed @lesteve, your proposition looks better than mine. Will change that.

**Comment by aabadie** [comment]
I pushed a new commit using `check_niimg` to return an iterator as you suggested @lesteve and keeping my previous change (using len(mask)). Let's wait for CI's

**Comment by GaelVaroquaux** [comment]
LGTM. Thanks!

**Pull request merged**
