### PR TITLE
[DOC] Fix documentation links

### LINKED ISSUE #3163: Links direct to the old version of documentation
I am not sure how many cases are there, but I encounter some links are pointing to the old doc instead of the stable release doc.

### Affected pages
The one place I can think of is the [glossory](https://nilearn.github.io/stable/glossary.html#term-functional-connectome)
Not sure if there are pages that were systematically populated and share the same problem.

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Closes #3163

### CODE REVIEW

**Comment by ymzayek** [comment]
@NicolasGensollen I went through the corrections and particularly relevant CircleCI build_docs outputs (e.g. `dev/glossary.html`) to check if all the relevant links were changed and it looks good to me. 

Correct me if I'm wrong, but I presume that the repo `nilearn.github.io` has been cleaned already since #3163 opened because in the release the links are now broken instead of linking to old versions of the documentation. 

I'm also wondering is the workflow already checking for broken links?

**Comment by NicolasGensollen** [comment]
Thanks for the review @ymzayek ! 👍 

>Correct me if I'm wrong, but I presume that the repo nilearn.github.io has been cleaned already since https://github.com/nilearn/nilearn/issues/3163 opened because in the release the links are now broken instead of linking to old versions of the documentation.

No, it hasn't been cleaned yet. The broken links are probably related to this commit:

https://github.com/nilearn/nilearn.github.io/commit/6f34c2924224ceba232f316f9c9f2d5a357f16cb

where I deleted one of the old folders for testing. I haven't had the time to clean the rest since then.

>I'm also wondering is the workflow already checking for broken links?

No, but this would be a good addition indeed !

**Review by ymzayek — APPROVED** [review]

**Comment by bthirion** [comment]
Can you take care of the pep8 failures ?
Best,

**Review by bthirion — APPROVED** [review]

**Comment by NicolasGensollen** [comment]
Thanks, merging...

**Pull request merged**
