### PR TITLE
change dataset description from bytes to str

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Only targets the description. 
Related to #1635 and #1489

### CODE REVIEW

**Comment by jeromedockes** [comment]
maybe add a whatsnew entry? this is a breaking change

**Review by jeromedockes — APPROVED** [review]
thanks!

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Review by bthirion — APPROVED** [review]
Good t merge I think. Thx !

**Comment by NicolasGensollen** [comment]
Thanks! Merging...

**Pull request merged**
