### PR TITLE
[DOC] Adding Himanshu to authors

### LINKED ISSUE #4321: [DOC] Add Himanshu to authors
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

Adding myself to authors

### List any pages that would be impacted.

`AUTHORS.rst`

### PR DESCRIPTION
**Pull request by man-shu**
- Closes #4321

Changes proposed in this pull request:

- adding myself to authors list
- removing Yasmin (?)

### CODE REVIEW

**Review by Remi-Gau — CHANGES_REQUESTED** [review]
make sure you also add yourself to the citation.cff file otherwise the sphinx reference for you (see below) won't be created.
```
`Himanshu Aggarwal`_
```

**Comment by man-shu** [comment]
Turns out I was already in it! Co-authored a contribution a few years ago.

**Comment by Remi-Gau** [comment]
For context:
The citation.cff is the place where we keep all our information about contributors.

If it is modified, a CI workflow will run `maint_tools/citation_cff_maint.py` and update some files automatically.
https://github.com/nilearn/nilearn/blob/main/.github/workflows/README.md#update-authors

This script is also run before any build of the doc in CI.

If the why or how is not clear, let me know so that we can improve the dev-facing doc.

**Comment by Remi-Gau** [comment]
> Turns out I was already in it! Co-authored a contribution a few years ago.

hahaha: silly me!!!! 🙈 

OK this should be good to go then.

**Review by Remi-Gau — APPROVED** [review]

**Review by Remi-Gau — COMMENTED** [review]
something must have gone wrong on the merge with upstream because some line changes should not appear here

assuming that the central of nilearn is a remote called `upstream` on your local set up can you run

```bash
git fetch --all
git merge upstream/main
git push
```

**Comment by man-shu** [comment]
Ok so now we only have the needed changes. I'll make sure to checkout to `main` before creating a new branch :) Sorry for the inconvenience!

**Comment by Remi-Gau** [comment]
> Ok so now we only have the needed changes. I'll make sure to checkout to `main` next time, before creating a new branch :) Sorry for the inconvenience!

no worries at all, it still happens to me all the time!!! 😉

**Review by bthirion — APPROVED** [review]

**Pull request merged**
