### PR TITLE
[MAINT] Use prettier to format HTML and CSS

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes none but related to https://github.com/nilearn/nilearn/pull/4295#issuecomment-1971863445

Changes proposed in this pull request:

- add prettier hook to pre-commit config
- run the hook on the code and doc base
- add github action to check formating

### CODE REVIEW

**Comment by Remi-Gau** [comment]
This is just a preview to see how much auto-formatting of the HTML and CSS can be done.

This would have to wait and be adapted once #4295 is in.

**Comment by Remi-Gau** [comment]
If we agree this is a good idea to have:
- [ ] mention it in the doc style guide section
- [ ] update README description CI actions

**Comment by Remi-Gau** [comment]
numpy2 issue is unrelated: see https://github.com/nilearn/nilearn/issues/4309

other tests should be fixed by #4306

**Comment by bthirion** [comment]
I'd be in favor of merging #4306 and #4309 first.
But, again, I'd like to see the reports generated...

**Comment by Remi-Gau** [comment]
> I'd be in favor of merging #4306 and #4309 first. But, again, I'd like to see the reports generated...

- Will work on #4309 and ask for a full build once #4295 is merged

**Comment by Remi-Gau** [comment]
# For review

### Before (current dev doc)

- GLM reports: https://nilearn.github.io/dev/modules/generated_reports/glm_reports_examples.html
- maskers reports: https://nilearn.github.io/dev/modules/generated_reports/masker_reports_examples.html

### After

- GLM reports: https://output.circle-artifacts.com/output/job/cfcee469-6141-46e7-a4f7-72e0ba71f6af/artifacts/0/dev/modules/generated_reports/glm_reports_examples.html
- maskers reports: https://output.circle-artifacts.com/output/job/cfcee469-6141-46e7-a4f7-72e0ba71f6af/artifacts/0/dev/modules/generated_reports/masker_reports_examples.html

**Review by bthirion — APPROVED** [review]
LGTM. Certainly deserves a whatwnew entry.

**Comment by Remi-Gau** [comment]
> LGTM. Certainly deserves a whatwnew entry.

That's fair.

Will fix the merge conflicts and update the changelog.

**Pull request merged**
