### PR TITLE
[INFRA] Adopt sphinx-copybutton

### PR DESCRIPTION
**Pull request by emdupre**
Related #2837 .

Changes proposed in this pull request:

- Adds sphinx_copybutton as a dependency
- Removes copybutton.js from the library

### CODE REVIEW

**Comment by jeromedockes** [comment]
thanks! weirdly enough `circleci_dependencies.sh` doesn't seem to rely on `requirements-build-doc.txt` -- see [here](https://github.com/nilearn/nilearn/blob/86b12ee8f81198932e11d2f4d6d4c2ee3173696c/tools/circleci_dependencies.sh#L7)

so you would probably need to add `sphinx-copybutton` there as well, then we could open a separate pr to make sure these dependencies are specified in one place only

**Review by jeromedockes — APPROVED** [review]
thanks @emdupre ! AFAICT it is ready to be merged?

**Comment by emdupre** [comment]
I don't know that I'd merge this yet .... It looks like `sphinx-copybutton` overrides `copybutton.js`, at least [here](https://7216-1235740-gh.circle-artifacts.com/0/dev/connectivity/functional_connectomes.html). I could try triggering a full build to confirm this behavior.

But I can open a separate PR to just patch the one `app.add_js_file` line ?

**Comment by tsalo** [comment]
Per this week's call, it sounds like `copybutton.js` can just be removed. Is that correct?

**Comment by emdupre** [comment]
Yes, I just need to revert 524a4de50ea101fe42867aa9d4ec1e3ae3fbe78f and look through the artifacts one more time !

**Comment by emdupre** [comment]
I think this is ready for (re)review !

**Review by bthirion — APPROVED** [review]
Thx !

**Comment by emdupre** [comment]
@NicolasGensollen are you OK if I merge this ?

**Review by NicolasGensollen — APPROVED** [review]
>@NicolasGensollen are you OK if I merge this ?

Yes, looks good to me, thanks a lot @emdupre !

**Pull request merged**
