### PR TITLE
[FIX] Use `figure_to_svg_base64` instead of `figure_to_png_base64`

### LINKED ISSUE #4886: [DOC] [BUG] No plots in reports for surface maskers on Chromium browsers
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe your proposed suggestion in detail.

The plots in the reports of SurfaceMasker and SurfaceLabelsMasker are not visible on Chromium browsers:

Image

They do show up on Firefox, apparently.

### List any pages that would be impacted.

_No response_

### PR DESCRIPTION
**Pull request by man-shu**
- Closes #4886

Changes proposed in this pull request:

- Use `figure_to_svg_base64` instead of `figure_to_png_base64`
- in surface_labels_masker and surface_masker

### CODE REVIEW

**Comment by man-shu** [comment]
Before on https://nilearn.github.io/stable/modules/generated_reports/masker_reports_examples.html#surface-maskers:
Screenshot 2024-12-23 at 4 55 46 PM

Will update the After once doc build is done.

**Comment by man-shu** [comment]
> Will update the After once doc build is done.

Oops looks like the doc build doesn't generate the report previews, but here's a screenshot from local on a Chromium browser:
Screenshot 2024-12-23 at 6 04 03 PM

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Comment by Remi-Gau** [comment]
> looks like the doc build doesn't generate the report previews

they do when asking [full doc]

**Review by Remi-Gau — APPROVED** [review]
Can you ask for a full build so we can all check the reports?

**Comment by man-shu** [comment]
Working!

https://github.com/nilearn/nilearn/actions/runs/12470757539/artifacts/2357309626

Screenshot 2024-12-24 at 9 34 13 AM

**Pull request merged**
