### PR TITLE
[FIX] update scikit-learn decoder tags

### LINKED ISSUE #4533: Update decoder tags for scikitlearn > 1.5.1
The run `10734049496` of the workflow testing Nilearn with the nightly build of its dependencies failed on `refs/heads/main`.

You can view the report here: https://github.com/nilearn/nilearn/actions/runs/10734049496

Pinging @nilearn/core

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes #4533 

Changes proposed in this pull request:

- adapt "_more_tags" methods and tests
- add TODOs to switch to the new `__sklearn_tags__` when dropping sklearn 1.5.1

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
LGTM. This only affects RENA  and Decoder ?

**Comment by Remi-Gau** [comment]
> LGTM. This only affects RENA and Decoder ?

So far yes.

I wanted to stick to a minimal PR to make sure things would function as they are now.

- But this lead to realize the issue I raised: https://github.com/nilearn/nilearn/issues/4538

So we may have to put something similar in place in the near future for all decoders.

**Comment by Remi-Gau** [comment]
Am going to merge this one as to solve the failure we are seeing on main.

**Comment by Remi-Gau** [comment]
hmm... that triggered failures on main beacause there has been a 1.5.2 release of scikit learn since this PR was created... 

# 🤦🏾

**Pull request merged**
