### PR TITLE
[FIX] Error when using plot_connectome(...) and edge_vmax < 0

### LINKED ISSUE #3389: Error when using plot_connectome to plot negative connectivity (and setting edge_vmax < 0)
For `plotting.plot_connectome(...)`, I was interested in plotting a matrix with only negative edges. However, when you set the `edge_vmin` parameter to be less than zero, it raises an error. I propose PR #3390.

For example, the code below raises the error further below. 

```Python
import numpy as np
from nilearn import plotting

if __name__ == '__main__':
    plotting.plot_connectome(np.array([[0, -2.5], [-2.5, 0]]),
                             node_coords=np.array([[0, 0, 0], [50, 50, 50]]),
                             edge_vmin=-3,
                             edge_vmax=-1,
                             colorbar=True)
    plotting.show()
```

```Python
Traceback (most recent call last):
  File "E:/Users/paulc/PycharmProjects/ConnSearch/test_nilearn.py", line 5, in <module>
    plotting.plot_connectome(np.array([[0, -2.5], [-2.5, 0]]),
  File "C:\Users\paulc\Anaconda3\lib\site-packages\nilearn\plotting\img_plotting.py", line 1208, in plot_connectome
    display.add_graph(adjacency_matrix, node_coords,
  File "C:\Users\paulc\Anaconda3\lib\site-packages\nilearn\plotting\displays\_projectors.py", line 212, in add_graph
    ax._add_lines(line_coords, adjacency_matrix_values, edge_cmap,
  File "C:\Users\paulc\Anaconda3\lib\site-packages\nilearn\plotting\displays\_axes.py", line 555, in _add_lines
    linewidth = 1 + 2 * abs_norm(abs_line_value)
  File "C:\Users\paulc\AppData\Roaming\Python\Python38\site-packages\matplotlib\colors.py", line 1193, in __call__
    raise ValueError("minvalue must be less than or equal to maxvalue")
ValueError: minvalue must be less than or equal to maxvalue
```

The error comes `_axes.py`. The issue arises earlier than the actual error on line 555. I think this earlier line is the problem:

``` Python
abs_norm = Normalize(vmin=0, vmax=vmax)
```

Because `vmax < 0`, then `vmax < vmin` when defining `abs_norm` above. This causes `linewidth = 1 + 2 * abs_norm(abs_line_value)` to error.

Currently, `abs_norm` takes some x (a connectivity edge weight) and returns `(abs_line_value - 0)/vmax`, except when it errors. From what I can tell, `abs_norm(abs_line_value)` is meant to essentially represent the magnitude of abs_line_value relative to the highest magnitude specified by the user.  My updated code does while accounting for cases where `vmax < 0` and `abs(vmin) > abs(vmax)`. Here is my updated code, which fixes the bug:

```Python
abs_norm = Normalize(vmin=0, vmax=max(abs(vmax), abs(vmin)))
```

After this fix, the error disappears. This image shows the new output of my initial example above, and the output is as expected: https://imgur.com/jrPKbep

Nilearn version: 0.9.0

### Expected behavior

It should plot the connectivity matrix of negative edges.

### Actual behavior

It errors.

### Steps and code to reproduce bug

I provide example code above.

### PR DESCRIPTION
**Pull request by paulcbogdan**
For `plotting.plot_connectome(...)`, I was interested in plotting a matrix with only negative edges. However, when you set the `edge_vmin` parameter to be less than zero, it raises an error. My PR is a fix. I provide details in #3389.

Closes #3389.

Changes proposed in this pull request:

I changed one line:

```Python
abs_norm = Normalize(vmin=0, vmax=vmax)
```

to

```Python
abs_norm = Normalize(vmin=0, vmax=max(abs(vmax), abs(vmin)))
```

From what I can tell, `abs_norm` is meant to essentially represent the magnitude of x relative to the highest magnitude specified by the user.  `abs_norm`  takes some x (a connectivity edge weight) and returns `(x - 0)/vmax` . 

My updated code does while accounting for cases where ` vmax < 0`  and ` abs(vmin) > abs(vmax)`, where you would likely be more interested in the magnitude of ` vmin` .

### CODE REVIEW

**Review by NicolasGensollen — COMMENTED** [review]
Thanks for contributing @paulcbogdan !
The fix LGTM. I'm just wondering whether we could add a non regression test. Probably here:

https://github.com/nilearn/nilearn/blob/5a00323f28a356c89e68662eed95d1901d16d78a/nilearn/plotting/tests/test_displays.py#L65-L69

Also, could you add an entry in `doc/changes/latest.rst` as well as your name in `doc/changes/names.rst` since this is your first contribution to Nilearn?

**Comment by NicolasGensollen** [comment]
@paulcbogdan I think changing the hemisphere in the test is a good option indeed.

**Comment by paulcbogdan** [comment]
I updated `test_glass_brain_axes()`, `doc/changes/latest.rst`, and `doc/changes/names.rst`. Thanks for these quick replies by the way.

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks @paulcbogdan ! 👍

**Review by bthirion — APPROVED** [review]
LGM, thx !

**Comment by ymzayek** [comment]
Thx all! Merging.

**Pull request merged**
