### PR TITLE
DOC: Update changelog

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Update doc/whats_new.rst for release of Nilearn 0.4.2 and moved the changelog additions in 0.4.1 to 0.4.2.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Great. Can you also update the index.html (remove the 0.3.0 from the list)

**Comment by KamalakerDadi** [comment]
>Can you also update the index.html (remove the 0.3.0 from the list)

Done

**Comment by GaelVaroquaux** [comment]
OK, merging!

**Comment by GaelVaroquaux** [comment]
Waiting for #1659 to be merged, and then we can release

**Pull request merged**
