### PR TITLE
DOC: Fixing the order of the linked displays while demoing plotting in user guide

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Closes # .

Changes proposed in this pull request:

- FIX the order of the plotting figures demonstration in plotting user guide.
That was probably because of me while working on this PR #2684

### CODE REVIEW

**Review by NicolasGensollen — COMMENTED** [review]
Thanks @KamalakerDadi ! 
Could you trigger a full build to better see the changes (put "[circle full]" in the commit message)?

**Comment by NicolasGensollen** [comment]
@KamalakerDadi could you merge master to get fix #2908 ?

**Comment by KamalakerDadi** [comment]
Thanks @NicolasGensollen for fixing the sphinx issue. Now the documentation looks like this when compared to stable one.
doc

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks @KamalakerDadi !

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Comment by bthirion** [comment]
Merging now.

**Pull request merged**
