### PR TITLE
[MRG+1] Fixing some minor SpaceNet issues (post-merge era)

### LINKED ISSUE #724: SpaceNet: Smooth-lasso vs graph-net
I remembered a comment about graph-net / smooth-lasso. I can see both in the doc. Is there something to do about that?

### PR DESCRIPTION
**Pull request by dohmatob**
Fix #724.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
LGTM. Let's wait for travis to be green before the merge (as a good practice).

**Comment by lesteve** [comment]
Travis was green on the first commit but then you added a second one ... you have a typo in your commit message BTW skelarn -> sklearn.

**Comment by GaelVaroquaux** [comment]
Travis is unhappy on that last commit

**Comment by dohmatob** [comment]
OK, seems "from sklearn.linear_model.coordinate_descent import _alpha_grid"
faults on skelarn 0.13. This provides a -ve answer to an earlier question
asked by @eic. Resetting.

On Wed, Jul 29, 2015 at 9:46 AM, Gael Varoquaux <notifications@github.com>
wrote:

> Travis is unhappy on that last commit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/pull/734#issuecomment-125871994>.
>



-- 
DED

**Comment by lesteve** [comment]
OK Travis is green, merging this one.

**Pull request merged**
