### PR TITLE
[MRG+1] Update to sphinx-gallery v0.1.1

### LINKED ISSUE #953: building docs takes so long
Each time I switch branch (even not changing any file) it takes me 1hour to rebuild the docs.
I don't know if this is an expected behaviour.

### PR DESCRIPTION
**Pull request by Titan-C**
This includes the IPython notebook rendering
Closes #953 as examples are now build only if script file md5sum changes and not timestamp

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Link to the rendered docs on CircleCI: https://circle-artifacts.com/gh/nilearn/nilearn/1055/artifacts/0/home/ubuntu/nilearn/doc/_build/html/index.html

**Comment by GaelVaroquaux** [comment]
Something broke in the CSS:
https://circle-artifacts.com/gh/nilearn/nilearn/1055/artifacts/0/home/ubuntu/nilearn/doc/_build/html/auto_examples/index.html

**Comment by Titan-C** [comment]
> Something broke in the CSS:

It is actually part of Nilearn theme. The nested image in the container, for some reason needs to be `div.sphx-glr-thumbcontainer img` with the `div` prefixed. I have done it as a local change. To the gallery CSS. I'm not sure if I should incorporate this as a CSS override in nilearn or put it as default in sphinx-gallery. Neither Sphinx-Gallery in default and read the docs themes nor scikit-learn need this.
The other option is to search the Nilearn CSS to find what is forcing us to use `div.sphx-glr-thumbcontainer img`

**Comment by AlexandreAbraham** [comment]
I tried to see how to fix this problem but I don't understand what you are talking about exactly. How far are you from a patch? Is there a way to fix nilearn theme?

**Comment by lesteve** [comment]
> I tried to see how to fix this problem but I don't understand what you are talking about exactly. How far are you from a patch? Is there a way to fix nilearn theme?

From what I gathered when I talked with @Titan-C the problem comes from a clash between nature.css which nilearn uses and the sphinx-gallery CSS, the former winning over the latter.

We agreed that using `div.sphx-glr-thumbcontainer img` in the sphinx-gallery CSS is probably the way to go.

**Comment by GaelVaroquaux** [comment]
The change to the CSS needs to be propagated upstream, and then we can resync sphinx-gallery in nilearn, to have a fix for https://github.com/sphinx-gallery/sphinx-gallery/issues/92 and then this is good to go.

**Comment by Titan-C** [comment]
Sorry for my downtime.
Since last time I talked with @lesteve my best assumption for the bad CSS was that the nature.css clashing the gallery.css, and I was going to propagate the extra CSS specification to upstream. To make it complete, I was testing what other default sphinx themes clash with the gallery and it turns out nature.css does not. (In fact only tranditional.css does horrible things to the links hovers and I'm pushing a patch to that in the gallery, the rest of the themes look good)
Regarding nilearn the clash comes from nilearn's own version of nature.css_t specifically from this block https://github.com/nilearn/nilearn/blob/master/doc/themes/nilearn/static/nature.css_t#L134-L137 my idea would be to remove it and rely only in this other block 
https://github.com/nilearn/nilearn/blob/master/doc/themes/nilearn/static/nature.css_t#L1052-L1055
The only thing this block does is avoid images to overflow from the main content block and appears to mostly be uses for images called
which is the only one that scikit learn uses, and the reason it does not clash with the gallery styling. 

The other option is to set in sphinx-gallery the default thumbnail with to 140px and not to 280px. This would imply that scikit-learn will have to use the gallery images and not its thumbnails, just as nilearn, for its carousel.(Maybe a future feature of Sphinx-Gallery to create the carrousel)

**Comment by GaelVaroquaux** [comment]
Ok, I have now understood the CSS problem. Let me detail it.

The images in the gallery are larger than the div that is encompassing them, which is 160px (line 32 of gallery.css). We are limiting their width using the "max-width" property, set to "100%", which means that they are not allowed to overflow that div (line 37 of gallery.css).

Now nilearn's theme has decided that the maximum width of images should be 805px (line 135 of nature.css_t).

Because it comes after, it overrides the decisions of gallery.css. I haven't seen an option to narrow the scope of nilearn's rule: the images that we are controlling are not in any way different than those controlled by sphinx-gallery.

I hate to say, but changing nilearn's theme is a bit awkward. It would be a pity if it's necessary to change a downstream theme to use sphinx-gallery.

One solution is simply to impose the width of the sphinx-gallery thumbnails. This value will not be overriden by the downstream CSS, as this width isn't set in the nilearn CSS (indeed, it would amount to imposing a strong constraints to all images, and themes are unlikely to do that).

I've done that in #973. The docs are still compiling, so it's not possible to see if the problem is fixed, but I  reckon it will be.

**Comment by Titan-C** [comment]
>One solution is simply to impose the width of the sphinx-gallery thumbnails. This value will not be overriden by the downstream CSS, as this width isn't set in the nilearn CSS (indeed, it would amount to imposing a strong constraints to all images, and themes are unlikely to do that).

I do like setting directly the width in the thumbnail images as done in #973 it's simple and clearer. `max-width: 100%` becomes irrelevant and shall be deleted. Nilearns `div.body img{ max-width: 805px;}` is still on top but it does not ruin the theme anymore as the thumbnail image size is already fixed.

**Comment by GaelVaroquaux** [comment]
> max-width: 100% becomes irrelevant and shall be deleted.

Agreed. I'll let you implement these changes in sphinx-gallery and maybe
(open a new PR). CircleCI has not finished running on this PR, so we
cannot check online that it renders well.

**Comment by lesteve** [comment]
> CircleCI has not finished running on this PR, so we
cannot check online that it renders well.

Just for the record, it actually failed and I restarted the build manually.

**Comment by GaelVaroquaux** [comment]
> Just for the record, it actually failed and I restarted the build manually.

Thanks

**Comment by Titan-C** [comment]
Rebased to bugfix release of Sphinx-Gallery v0.1.1
It includes the html-noplot fix and the CSS.

**Comment by GaelVaroquaux** [comment]
Looks great to me! +1 for merge. Thanks.

For the record, the rendered HTML is visible here:
https://circle-artifacts.com/gh/nilearn/nilearn/1108/artifacts/0/home/ubuntu/nilearn/doc/_build/html/auto_examples/index.html

**Comment by lesteve** [comment]
LGTM, merging, thanks a lot for your work on this !

**Comment by AlexandreAbraham** [comment]
Woohoo!

**Comment by GaelVaroquaux** [comment]
> Woohoo!

Yeah! I'm pretty happy

**Pull request merged**
