### PR TITLE
[MRG] Fixes #1313 and #1314

### LINKED ISSUE #1313: Unexpected behavior from 'subject' argument on haxby fetcher
The docstring says the `subjects` argument in `fetch_haxby` is a list containing the subjects to be fetched, but it actually also accepts an int as argument, in which case it behaves as the deprecated `n_subjects`. This is problematic because in this case an unaware user can pass an int n as the argument and run  `haxby_dataset.func[0]`, which will return data for subject 1 instead of subject n. It seems to me that we should either:
- Make this use case explicit in the docstring or;
- Throw an error when `subjects` is an int.

### PR DESCRIPTION
**Pull request by Joaoloula**
Updates `fetch_haxby` documentation to include the case when `subjects` parameter is an int and corrects `fetch_abide_pcp` for the new download link.

### CODE REVIEW

**Comment by AlexandreAbraham** [comment]
Small question: are we sure that there is no difference between fcp-indi and fcp-indi-new?

**Comment by KamalakerDadi** [comment]
>Small question: are we sure that there is no difference between fcp-indi and fcp-indi-new?

May be not. Both seems to work now.

**Comment by KamalakerDadi** [comment]
I think we should go with "fcp-indi-new" since the main project has the same name. https://github.com/preprocessed-connectomes-project/abide/blob/master/download_abide_preproc.py

**Comment by AlexandreAbraham** [comment]
> I think we should go with "fcp-indi-new" since the main project has the same name.

I know that it is the new URL but what is the difference with the previous one? Maybe the used an update version of CPAC for the preproc? I just would like to be sure that we are still fetching the same data.

**Comment by KamalakerDadi** [comment]
>Maybe the used an update version of CPAC for the preproc? I just would like to be sure that we are still fetching the same data.

Good point. Yes, needed to check that.

**Comment by AlexandreAbraham** [comment]
I think that taking the md5 hash of a bucnh of random files should be enough. Or maybe @Joaoloula can grab Cameron at brainhack and ask him ? :P

**Comment by Joaoloula** [comment]
Cameron's not here :/ In the middle of testing, I actually overwrote the dataset coming from the old download link, so I can't compare the checksums, can someone who still has the 'old' data take care of that?

**Comment by Joaoloula** [comment]
So @AlexandreAbraham got in touch with the Child Mind Institute people and, long story short, the fcp-indi-new does have exactly the same data as fcp-indi, but it was just a temporary switch they made. The old link is now up and running again, and so I reverted this part of the PR.

**Comment by AlexandreAbraham** [comment]
So, let's go merging this one when all is green.

**Comment by AlexandreAbraham** [comment]
Merging as it makes doc better (independently of the subjects / n_subjects debate).

**Pull request merged**
