### PR TITLE
[DOC] Advertise for office hours in README

### PR DESCRIPTION
**Pull request by NicolasGensollen**
This PR proposes to add a few lines in the README to advertise for the Nilearn office hours with the next date and discord link, as suggested by @RaphaelMeudec as a way to increase the visibility of these events.

### CODE REVIEW

**Comment by bthirion** [comment]
Maybe link to Nilearn's twitter or to some website location where the next date will be displayed ?

**Comment by NicolasGensollen** [comment]
> I don't know if it might become painful to update the date each time? Not sure how it's done on the website.

I'm doing these "manually" so far (website, twitter, neurostars...)., but there is probably a way to automate this to some extent, I will have a closer look.

>Maybe link to Nilearn's twitter or to some website location where the next date will be displayed ?

You mean remove the next date from the readme and link the website instead?

**Comment by bthirion** [comment]
> De: "Devon Hjelm" ***@***.***>
> À: "nilearn" ***@***.***>
> Cc: "Bertrand Thirion" ***@***.***>, "Comment"
> ***@***.***>
> Envoyé: Mercredi 30 Juin 2021 09:00:17
> Objet: Re: [nilearn/nilearn] [DOC] Advertise for office hours in README (#2893)

>> I don't know if it might become painful to update the date each time? Not sure
>> how it's done on the website.
> I'm doing these "manually" so far (website, twitter, neurostars...)., but there
> is probably a way to automate this to some extent, I will have a closer look.
>> Maybe link to Nilearn's twitter or to some website location where the next date
>> will be displayed ?
> You mean remove the next date from the readme and link the website instead?

Yes.

**Comment by NicolasGensollen** [comment]
Merging! :tada:

**Pull request merged**
