### PR TITLE
[MRG+1] Make memory profiling tests more robust

### LINKED ISSUE #986: Memory profiling test function fails from time to time
The memory profiling test function fails sporadically : sometimes the measured memory consumption is equal to 0.0, thus the  ̀test_memory_usage` fails.
The issue is related to `memory_profiler` measures accuracy, maybe it could be fixed by performing several measures and returning the max.

### PR DESCRIPTION
**Pull request by aabadie**
This should fix #986 by performing 3 measures and return the max value.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Another option would be to have the function that we are benching do it's operations three times. Indeed, I suspect that the reason that we are witnessing zero memory usage is that the function is too fast and memory is cleared before. Thus the strategy of running the function 3 times inside the memory_usage might be more reliable.

**Comment by aabadie** [comment]
> Thus the strategy of running the function 3 times inside the memory_usage might be more reliable.

Yes, but this would require to apply the change upstream.

**Comment by GaelVaroquaux** [comment]
> Yes, but this would require to apply the change upstream.

Or just to do:

<pre>
def func_3_times(args, **kwargs):
   for _ in range(3):
        func(args, **kwargs)
</pre>

and to bench func_3_times instead of func. No?

**Comment by aabadie** [comment]
> Or just to do:
> 
> <pre>
> def func_3_times(args, **kwargs):
>    for _ in range(3):
>         func(args, **kwargs)
> </pre>
> 
> and to bench func_3_times instead of func. No?

Nice suggestion which makes sense and works as well. I pushed a commit with it.

**Comment by aabadie** [comment]
@GaelVaroquaux, are you fine with this PR ?

**Comment by GaelVaroquaux** [comment]
LGTM. +1 for merge

**Pull request merged**
