### PR TITLE
Fix invalid escape sequences in strings

### LINKED ISSUE #2315: Deprecation warning due to invalid escape sequences in Python 3.7
For the Bug Report, 
Include this information:
-------------------------
What version of Nilearn are you using? master

Deprecation warning are generated over invalid escape sequences. This can be fixed by using raw strings or escaping the literals again. There are also syntax warnings in Python 3.8 that need to be fixed.

List the steps you performed that revealed the bug to you.
Include any code samples. Enclose them in triple back-ticks (```)
Like this:

```
find . -iname '*.py'  | xargs -P 4 -I{} python3.8 -Walways -m py_compile {}     
                 
./examples/05_advanced/plot_localizer_simple_analysis.py:72: DeprecationWarning: invalid escape sequence \l
  title = ('Negative $\log_{10}$ p-values'
./examples/05_advanced/plot_localizer_mass_univariate_methods.py:98: DeprecationWarning: invalid escape sequence \l
  title = ('Negative $\log_{10}$ p-values'
./examples/05_advanced/plot_localizer_mass_univariate_methods.py:114: DeprecationWarning: invalid escape sequence \l
  title = ('Negative $\log_{10}$ p-values'
./examples/05_advanced/plot_haxby_mass_univariate.py:142: DeprecationWarning: invalid escape sequence \l
  title = ('Negative $\log_{10}$ p-values'
./examples/05_advanced/plot_haxby_mass_univariate.py:156: DeprecationWarning: invalid escape sequence \l
  title = ('Negative $\log_{10}$ p-values'
./examples/02_decoding/plot_oasis_vbm.py:185: DeprecationWarning: invalid escape sequence \l
  title = ('Negative $\log_{10}$ p-values'
./examples/02_decoding/plot_simulated_data.py:1: DeprecationWarning: invalid escape sequence \m
  """
./nilearn/image/tests/test_resampling.py:332: DeprecationWarning: invalid escape sequence \(
  "vector: Affine shape should be \(4, 4\) and "
./nilearn/image/tests/test_resampling.py:333: DeprecationWarning: invalid escape sequence \(
  "not \(3, 3\)")
./nilearn/decoding/objective_functions.py:43: DeprecationWarning: invalid escape sequence \s
  """Compute the Lipschitz constant (upper bound) for the gradient of the
./nilearn/input_data/tests/test_nifti_masker.py:215: DeprecationWarning: invalid escape sequence \(
  "a list of 4D images \(5D\)."):
./nilearn/plotting/find_cuts.py:417: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if label_hemisphere is 'left':
./nilearn/plotting/find_cuts.py:419: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif label_hemisphere is 'right':
./nilearn/plotting/surf_plotting.py:230: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(surf_map_data.shape) is not 1:
./nilearn/plotting/surf_plotting.py:524: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(roi.shape) is not 1:
./nilearn/tests/test_niimg_conversions.py:115: DeprecationWarning: invalid escape sequence \(
  "of 3D images \(4D\)."):
./nilearn/tests/test_niimg_conversions.py:210: DeprecationWarning: invalid escape sequence \(
  "a list of list of list of 3D images \(6D\)"
./nilearn/tests/test_niimg_conversions.py:217: DeprecationWarning: invalid escape sequence \(
  "a list of list of 4D images \(6D\)"
./nilearn/tests/test_niimg_conversions.py:435: DeprecationWarning: invalid escape sequence \(
  "a list of 4D images \(5D\)")
```

### PR DESCRIPTION
**Pull request by kchawla-pi**
Fixes #2315

### CODE REVIEW

**Comment by jeromedockes** [comment]
why not use raw strings?

**Comment by kchawla-pi** [comment]
That's another way to solve it.

**Comment by kchawla-pi** [comment]
> why not use raw strings?

@jeromedockes I had tried raw strings but they fail the tests, for reasons not readily apparent.

**Comment by kchawla-pi** [comment]
I can hold off on merging this if you wanna take a quick look.

**Comment by jeromedockes** [comment]
> I can hold off on merging this if you wanna take a quick look.

No that's fine

**Pull request merged**
