### PR TITLE
add a sentence to warn about coregistration issue

### PR DESCRIPTION
**Pull request by salma1601**
I was not aware of the plotting machinery so I was expecting mismatch between non-coregistered images of the same subject to be huge, and actually it may not.
Don't know if people agree on that addition.

### CODE REVIEW

**Comment by AlexandreAbraham** [comment]
Honestly, I'm not sure about this remark. I mean, all other softwares I've used so far do the same thing, I don't see what is peculiar in the way nilearn works.

**Comment by KamalakerDadi** [comment]
>Honestly, I'm not sure about this remark.

Mee too.

**Comment by GaelVaroquaux** [comment]
I agree with @AlexandreAbraham. Maybe a better phrasing can be found.

**Comment by KamalakerDadi** [comment]
What's the status on this ?

>Maybe a better phrasing can be found.

Are you up for better phrasing ?

**Comment by kchawla-pi** [comment]
Is this alive? If not, please close it by this weekend.

**Pull request closed without merging**
