### PR TITLE
[ENH]  rename `nilearn.datasets._utils.fetch_file` to `nilearn.datasets._utils.fetch_single_file`

### LINKED ISSUE #4155: rename either `nilearn.datasets._utils._fetch_file` or `nilearn.datasets._utils._fetch_files`
rename either `nilearn.datasets.utils._fetch_file` or `nilearn.datasets.utils._fetch_files`

but having both of them differing by a single letter is just not OK

_Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/issues/4086#issuecomment-1783156630_

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes #4155

Changes proposed in this pull request:

- rename `nilearn.datasets._utils.fetch_file` to `nilearn.datasets._utils.fetch_single_file`

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
LGTM. The codecov complaints are wrong, aren't they ?

**Comment by Remi-Gau** [comment]
> The codecov complaints are wrong, aren't they ?

I would assume but those "false positives" make me unhappy.

**Comment by ymzayek** [comment]
They could be correct. I haven't checked the tests closely but when changing code that wasn't fully tested previously these will be picked up. Same happens in the black PRs. I think ok not to address in this PR though

**Review by ymzayek — APPROVED** [review]
LGTM!

**Comment by Remi-Gau** [comment]
> I haven't checked the tests closely but when changing code that wasn't fully tested previously these will be picked up.

OK let me recheck.

If we can increase coverage why not, but given that those are called by the fetchers my assumption was that the tests should hit those lines.

**Comment by Remi-Gau** [comment]
OK had a look at the test and from my understanding the tests that "could" hit those lines, actually create mock dataset and hence the fetching never runs.

If we think this should be changed, I think it would probably be done in a separate PR.

https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/tests/test_func.py#L954

https://github.com/nilearn/nilearn/blob/98ad01944dfb1b3fff0fc4306d852509cc1f225b/nilearn/datasets/tests/test_func.py#L982

https://github.com/nilearn/nilearn/blob/98ad01944dfb1b3fff0fc4306d852509cc1f225b/nilearn/datasets/tests/test_func.py#L1019

**Pull request merged**
