### PR TITLE
[DOC] Making easibility in reading of ICBM 152 description

### LINKED ISSUE #1166: nilearn.datasets.fetch_icbm152_2009 docstring isn't great
The description of the return argument in nilearn.datasets.fetch_icbm152_2009 is hard to read.

Also, we should add a seealso block to point to nilearn.datasets.load_mni152_template and fetch_icbm152_brain_gm_mask

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Attempts to Fix #1166

### CODE REVIEW

**Comment by KamalakerDadi** [comment]
Any opinions on this PR ?

**Comment by GaelVaroquaux** [comment]
The see also addition is awesome! 

Why is the splitlines needed?

**Comment by KamalakerDadi** [comment]
>Why is the splitlines needed? 

To make description a bit easy to read. Without splitlines it looks a bit occupied.

**Comment by GaelVaroquaux** [comment]
> To make description a bit easy to read. Without splitlines it looks a bit occupied.

But splitlines is returning a list of strings, instead of a string, so
there is a change in type, and I don't understand why we should be
printing lists of strings instead of strings.

**Comment by KamalakerDadi** [comment]
>But splitlines is returning a list of strings, instead of a string, so there is a change in type, and I don't understand why we should be printing lists of strings instead of strings.

Ok. I will find some other alternative.

**Comment by kchawla-pi** [comment]
Is this alive? If not, please close it by this weekend.

**Comment by thomasbazeille** [comment]
As it doesn't seem to be making progress I'm closing for now. Don't hesitate to reopen if needed

**Pull request closed without merging**
