### PR TITLE
ARM arch testing

### LINKED ISSUE #2840: Tests on ARM architecture
We should consider adding ARM support to the CI. This would help us catch related issues (see #2832 for example).
For the moment, I think travis is still the best option for this. 
Since we have limited credits, I think we should only run ARM tests (this is what scikit-learn is doing currently for instance).

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Fixes #2840 

This PR proposes to add ARM testing in the CI pipeline. 
Since it relies on travis to run the tests and we have limited credits, the workflow is only triggered whenever a commit message contains the tag "[arm64]". 
Since it is running in about 15-20min, I'm wondering whether we could afford running it systematically on master though... :thinking: 

NOTE: It looks like the only test failing is `test_resample_img_segmentation_fault`:

https://github.com/nilearn/nilearn/blob/7142c5c9199e13c67111e7a44c58c9169259908b/nilearn/image/tests/test_resampling.py#L793-L815

I'm not sure what is happening since the worker just dies at the resampling step. I tried changing the fourth dimension value to very small values (in which case the test passes) and to 1024 (in which case it still fails...). 
For now, I added a skip condition for this test when running under travis with ARM64 architecture, but I'm open to suggestions.

### CODE REVIEW

**Comment by bthirion** [comment]
The error does not seem to be related to Python 3.5...

**Comment by NicolasGensollen** [comment]
>The error does not seem to be related to Python 3.5...

No it's not, it is a PEP8 violation but it is running as part of the python 3.5 workflow. 
I realized today that some of the changes I made in #2848 result in confusing outputs in the Github actions board. I'm working on fixing/improving this in #2856

**Comment by jeromedockes** [comment]
@NicolasGensollen can we merge this one?

**Comment by NicolasGensollen** [comment]
@jeromedockes I believe we can merge it. For now, you have to explicitly request ARM tests but putting "[arm64]" in your commit message. 
Not sure whether we want to have them run systematically on master because of credit concerns..

**Comment by jeromedockes** [comment]
> @jeromedockes I believe we can merge it. For now, you have to explicitly request ARM tests but putting "[arm64]" in your commit message. 
> Not sure whether we want to have them run systematically on master because of credit concerns..

that makes sense, and the need for it doesn't arise that often. I say
let's merge it as it is, and if we ever want to start running it with
every push that will be easy to change. does that make sense?

**Comment by NicolasGensollen** [comment]
>does that make sense?

Absolutely!

**Comment by bthirion** [comment]
Thx !

**Pull request merged**
