### PR TITLE
[NO MRG] Replace GraphLassoCV (deprecated since skl0.20) with GraphicalLassoCV

### PR DESCRIPTION
**Pull request by kchawla-pi**
For issue #2069 

Since the usage is in examples & documentation, it is improbable that users will run it in the oldest support Scikitlearn version. CIrcleCI uses the latest versions. Hence not including the older version immediately. Will reasses based on feedback.

### CODE REVIEW

**Comment by bthirion** [comment]
Let us know whenever we should review the PR. prepending MRG/WIP prefix to PR name  is useful !

**Comment by jeromedockes** [comment]
many commits come from merging the branch of #2076?

**Comment by kchawla-pi** [comment]
I don't understand what they are doing here, that branch has not been merged into master...

**Comment by kchawla-pi** [comment]
Okay I will either open a new PR or wait for the pytest merge to happen first, until then no one merge this!

**Comment by jeromedockes** [comment]
> I don't understand what they are doing here, that branch has not been merged into master...

maybe you created this branch from you `pytest-switch` branch instead of master?

**Comment by kchawla-pi** [comment]
That would explain it. Will deal with it.

**Pull request closed without merging**
