### PR TITLE
[MRG] Updated the link to Anaconda installation page

### PR DESCRIPTION
**Pull request by kchawla-pi**
For issue #1776

### CODE REVIEW

**Comment by kchawla-pi** [comment]
@GaelVaroquaux The tests seem to be failing for other reasons. Not sure what's happening here.

**Comment by KamalakerDadi** [comment]
Is your branch even with master ?

**Comment by kchawla-pi** [comment]
Yes

**Comment by KamalakerDadi** [comment]
Ok. I am looking into it.

**Comment by kchawla-pi** [comment]
THanks Kalamaker.

**Comment by KamalakerDadi** [comment]
I don't understand why is this WIP ?

In your PR #1785 yeo atlas is causing failures which you are trying to address here.

It would be great if you could click rebuild

**Comment by kchawla-pi** [comment]
I fixed the URL and rebuilt this PR. WHy is this failing?

**Comment by KamalakerDadi** [comment]
>WHy is this failing?

I am on it.

**Comment by KamalakerDadi** [comment]
This fails at example: plot_ica_neurovault. The reason is some not all of the collected images from neurovault are bad. Hence cannot be used ```get_data()``` after loaded using nibabel.

My suggestion:

Either move the already existing ```try``` block above to this line of code
```image = smooth_img(image_path, fwhm=None)``` in the example, examples/05_advanced/plot_ica_neurovault.py

or We can filter the collections specifying using ```collection_terms``` not to pick this collection. But this cause more time to pick some other collection which has neurosynth ids. This will indeed increase the build time of what we have. 

I would prefer to move try block one line above though its ugly.

@GaelVaroquaux what do you prefer ?

**Comment by kchawla-pi** [comment]
The build is working locally (except for a Latex warning I am getting).
We could merge the locally successful PRs, and then deal with this?
@GaelVaroquaux ?

**Comment by kchawla-pi** [comment]
@ Kamalaker Thanks Man!

**Comment by KamalakerDadi** [comment]
>The build is working locally (except for a Latex warning I am getting).

Did you run build after flushing the data folder neurovault in nilearn_data directory ?
Or simply run examples/05_advanced/plot_ica_neurovault.py after flushing

**Comment by kchawla-pi** [comment]
No, I used the existing data set, I am testing if my PR broke something, not if Neurovault is okay or not. The local builds are passing with non-corrupted datasets, so I am reassured I didn't break anything. 

I can move the dataset out of the nilearn_data folder and run the example file, and post the outcome here, then move the data back.

**Comment by kchawla-pi** [comment]
@GaelVaroquaux @bthirion 
We can merge all these PRs into a not-master branch and then that not-master into the master once the CCI is behaving again.

**Comment by kchawla-pi** [comment]
It might be worth it to retest with those new neurosynth ids temporarily at least for this release and thn switch them back. What say?

**Comment by kchawla-pi** [comment]
@KamalakerDadi Yup, flushing the neurovault directory and running that example  gives the 
`EOFError: Compressed file ended before the end-of-stream marker was reached`

**Comment by kchawla-pi** [comment]
Putting `image = smooth_img(image_path, fwhm=None)` in the `try` block cause failure further down.
```
Traceback (most recent call last):
  File "/home/kshitij/workspace/nilearn-org/nilearn-repo/kchawla-pi/nilearn/examples/05_advanced/plot_ica_neurovault.py", line 118, in <module>
    term_weights_for_components = np.dot(fast_ica.components_, term_weights)
ValueError: shapes (16,79) and (80,1301) not aligned: 79 (dim 1) != 80 (dim 0)
```

**Comment by KamalakerDadi** [comment]
>Putting image = smooth_img(image_path, fwhm=None) in the try block cause failure further down.

Not for me atleast.

**Comment by bthirion** [comment]
>  OR as suggested earlier, merge them, then release a new b2 once CCI is fixed.

+1

**Pull request merged**
