### PR TITLE
Update Schaefer parcelation to v0.14.3

### PR DESCRIPTION
**Pull request by danjgale**
Addresses #2137. `base_url=None` in `fetch_atlas_schaefer_2018` downloads the most recent Schaefer parcelation version, v0.14.3. Previously this downloaded v0.8.1. Using v0.14.3 ensures that users will get the correct atlas label names by default. I added a note to the docstring as well. 

When I was going through [the updates](https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal#updates), I also noticed that 700 and 900 region parcelations have been available since v0.10.2. Although this was not discussed in #2137,  I've updated `fetch_atlas_schaefer_2018` to include these as options for the `n_rois` parameter; `n_rois` now takes values 100-1000 in increments of 100.

### CODE REVIEW

**Comment by danjgale** [comment]
The travis failure seems similar to others (e.g., #2107); looks to be an unrelated issue?

**Comment by kchawla-pi** [comment]
@danjgale  Pull from master to update the PR.

**Comment by kchawla-pi** [comment]
We still need to diagnose the failure, can't merge with failing CI. The error in @2107 is in a different test AFAICT . Once we pull from master, we can investigate.

**Comment by emdupre** [comment]
Once #2140 is merged, pulling from master *should* fix this. [In the Travis logs](https://travis-ci.org/nilearn/nilearn/jobs/587845022), it looks like you're seeing the same SIGBART error:

<details>
 joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGABRT(-6)}
</details>

**Comment by danjgale** [comment]
@emdupre thanks for pointing that out, I was pretty lost on what was causing it!

**Comment by danjgale** [comment]
@kchawla-pi just pulled from master, let me know if there's anything else I need to do or am missing!

**Comment by jeromedockes** [comment]
> @kchawla-pi just pulled from master, let me know if there's anything else I need to do or am missing!

#2140 has not been merged yet, so you will need to pull again once it is merged.

**Comment by jeromedockes** [comment]
>> @kchawla-pi just pulled from master, let me know if there's anything else I need to do or am missing!
>
> #2140 has not been merged yet, so you will need to pull again once it is merged.

sorry, it has -- ignore this comment

**Comment by GaelVaroquaux** [comment]
LGTM. Merging.

Thanks a lot!!

**Pull request merged**
