### PR TITLE
Fix image labels

### LINKED ISSUE #3154: Image labels don't correspond to images
The images for the Haxby 2001 experiment show cats and chairs, but are labeled as faces and cats, respectively. 

This could be fixed by changing the image labels to correspond to what is shown, or by selecting different images to correspond to the labels. I'm submitting a PR that changes the image labels.

### Affected pages
https://nilearn.github.io/stable/decoding/decoding_intro.html

### PR DESCRIPTION
**Pull request by ctw**
Changed image labels to correspond with the images (could alternatively show images of faces and cats to match the original labels).

Closes #3154

### CODE REVIEW

**Review by NicolasGensollen — COMMENTED** [review]
Thanks @ctw !
I think the right fix would be to change the images rather than the captions such that the rest of the tutorial makes sense. WDYT?

**Comment by ctw** [comment]
Good point @NicolasGensollen -- I've now reverted the labels and updated the images as you suggested!

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks @ctw !

**Comment by NicolasGensollen** [comment]
Thanks! Merging...

**Pull request merged**
