### PR TITLE
[DOC] Fix typos doc

### PR DESCRIPTION
**Pull request by florian6973**
- Closes none

Changes proposed in this pull request:

- Fix typo of the word "mutli" for the definition of MVPA in the glossary
- Fix typo footcite Thirion2014

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
Thx for cleaning this ! this is very appreciated.

**Review by emdupre — APPROVED** [review]
Thank you, @florian6973 !

**Comment by Remi-Gau** [comment]
@florian6973 
thanks for those fixes.

Unless I am mistaken you are not listed as one of our contributors.

If you want you can add yourself to the list but updating the changelog and the citation.cff:
https://nilearn.github.io/stable/development.html#changelog

**Comment by florian6973** [comment]
Yes you are right, thank you very much for noticing!

I edited the changelog and `citations.cff` as a result, I hope I will contribute more in the future :)

**Review by Remi-Gau — APPROVED** [review]

**Comment by Remi-Gau** [comment]
Definitely looking forward to see you contribute in the future. 🚀

**Comment by bthirion** [comment]
I think that the CI failures are unrelated. Merging.

**Pull request merged**
