### PR TITLE
MAINT: Update to Sphinx-Gallery v0.1.11

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Upgrade is made upon release v0.1.11.

Please have a look at the change log in this link for recent updates and improvements for robust documentation build.
http://sphinx-gallery.readthedocs.io/en/latest/changes.html

CircleCI build should be finished to review this PR. Hope, it goes through.

### CODE REVIEW

**Comment by KamalakerDadi** [comment]
@GaelVaroquaux I am not sure why CircleCI if failing ? Also, the same in other recent PRs too.
Do you have any idea ? Should I go through in detail about error or is the error on CircleCI side ?

**Comment by KamalakerDadi** [comment]
I can build doc locally.

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux I am not sure why CircleCI if failing ? Also, the same in other recent PRs too.

Maybe a fluke in the nipy.org website. I've restarted, and it seems to be
doing good so far.

**Comment by KamalakerDadi** [comment]
>I've restarted, and it seems to be doing good so far.

Thanks

**Comment by GaelVaroquaux** [comment]
OK, that fixed it.

**Comment by KamalakerDadi** [comment]
As we discussed last time. Now, fetch_megatrawls references are fixed now.
https://2618-1235740-gh.circle-artifacts.com/0/home/ubuntu/nilearn/doc/_build/html/auto_examples/01_plotting/plot_visualize_megatrawls_netmats.html#sphx-glr-auto-examples-01-plotting-plot-visualize-megatrawls-netmats-py

**Comment by GaelVaroquaux** [comment]
LGTM. Thanks a lot @KamalakerDadi

**Pull request merged**
