### PR TITLE
Fix glitches in doctest and disable dataset fetching.

### PR DESCRIPTION
**Pull request by AlexandreAbraham**

### CODE REVIEW

**Comment by lesteve** [comment]
Still some test failing:

```
======================================================================
FAIL: Doctest: decoding_tutorial.rst
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lesteve/miniconda3/lib/python3.4/doctest.py", line 2187, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
nose.proxy.AssertionError: Failed doctest test for decoding_tutorial.rst
  File "/home/lesteve/dev/nilearn/doc/decoding/decoding_tutorial.rst", line 0

----------------------------------------------------------------------
File "/home/lesteve/dev/nilearn/doc/decoding/decoding_tutorial.rst", line 465, in decoding_tutorial.rst
Failed example:
    cv_scores = cross_val_score(anova_lda, X, y, cv=cv, verbose=1)
Exception raised:
    Traceback (most recent call last):
      File "/home/lesteve/miniconda3/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest decoding_tutorial.rst[36]>", line 1, in <module>
        cv_scores = cross_val_score(anova_lda, X, y, cv=cv, verbose=1)
    NameError: name 'X' is not defined
----------------------------------------------------------------------
File "/home/lesteve/dev/nilearn/doc/decoding/decoding_tutorial.rst", line 466, in decoding_tutorial.rst
Failed example:
    classification_accuracy = np.mean(cv_scores)
Exception raised:
    Traceback (most recent call last):
      File "/home/lesteve/miniconda3/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest decoding_tutorial.rst[37]>", line 1, in <module>
        classification_accuracy = np.mean(cv_scores)
    NameError: name 'cv_scores' is not defined

>>  raise self.failureException(self.format_failure(<_io.StringIO object at 0x7f3bdd4d2708>.getvalue()))
    

----------------------------------------------------------------------
```

**Comment by GaelVaroquaux** [comment]
You should probably merge my PR in this one.

**Comment by GaelVaroquaux** [comment]
OK. Let's talk about this when you come in.

**Comment by lesteve** [comment]
Merging even if some problems may still remain.

**Comment by AlexandreAbraham** [comment]
I don't know if this PR was supposed to be merged actually. @GaelVaroquaux is taking care of the problem now.

**Comment by GaelVaroquaux** [comment]
Oh, I am not taking care of this :$

I think that it's still good to have merged this guy. It's an improvement.

**Comment by AlexandreAbraham** [comment]
> Oh, I am not taking care of this :$

I thought you were.

I skipped all the doctests that were based on data fetching. I know that some of them still fail but that's because the fix is not trivial.

**Comment by lesteve** [comment]
By merging both of your PRs and pushing a fix in upstream for the remaining problems I think we are good now.

**Comment by lesteve** [comment]
That was the fix 295eaf16aeb3eb220e2b526e5601d81422f73862. I just skipped all the remaining doctests, not sure whether there was a better way to do it ...

**Comment by GaelVaroquaux** [comment]
> That was the fix 295eaf1. I just skipped all the remaining doctests,
> not sure whether there was a better way to do it ...

Tests are now failing under CircleCI:

https://circleci.com/gh/nilearn/nilearn/75

we need to make it so that all the tests passed.

**Pull request merged**
