### PR TITLE
Tidy up copyrights

### LINKED ISSUE #415: Please clarify copyrights
INRIA or nilearn developers?

```
$> git grep -i Copyright doc/conf.py COPYING 
COPYING:Copyright (c) 2007 - 2013 The nilearn developers.
doc/conf.py:copyright = u'INRIA Parietal 2010-2013'
```

you might also like to symlink COPYING into doc/ to avoid diverging them:

```
$> diff COPYING doc/COPYING
3c3
< Copyright (c) 2007 - 2013 The nilearn developers.
---
> Copyright (c) 2009 - 2013 nilearn developers.
15c15
<   c. Neither the name of the nilearn Developers nor the names of
---
>   c. Neither the name of the nilearn Developers  nor the names of
```
and would be neat if at least briefly copyright/licenses of used/shipped 3rd party modules were mentioned in COPYING:

```
doc/sphinxext/LICENSE.txt:Copyright (C) 2008 Stefan van der Walt <stefan@mentat.za.net>, Pauli Virtanen <pav@iki.fi>
doc/sphinxext/LICENSE.txt:Copyright (c) 2006, Enthought, Inc.
doc/sphinxext/LICENSE.txt:Copyright (c) 2002-2008 John D. Hunter; All Rights Reserved.
doc/themes/nilearn/static/jquery.jcarousel.min.js:* Copyright (c) 2014 Jan Sorgalla; Licensed MIT */
doc/themes/nilearn/static/sphinxdoc.css: * :copyright: Copyright 2007-2011 by the Sphinx team, see AUTHORS.
```

### PR DESCRIPTION
**Pull request by lesteve**
fixes #415.

I removed doc/COPYING because I didn't see the point compared to COPYING and used nilearn developers everywhere else.

One thing I didn't do is tackle @yarioptic's following comment:

> and would be neat if at least briefly copyright/licenses of used/shipped 3rd party modules were mentioned in COPYING:

the main reason being that scikit-learn doesn't do it so I don't have a good model to draw inspiration from. Suggestions more than welcome.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
To address @yarikoptic's comment, we should list all the code that we have included and that came from outside in the copying, with a pointer to the license. I can only see nilearn/doc/sphinxext

**Comment by lesteve** [comment]
Right I added licenses for all the incorporated software I could find via `git grep -iPl 'license|copyright'`.

I drew inspiration from the Sphinx [LICENSE](https://github.com/sphinx-doc/sphinx/blob/master/LICENSE).

While I was at it I rename COPYING to LICENSE.

**Comment by bthirion** [comment]
LGTM

**Comment by GaelVaroquaux** [comment]
Thank you! This is great. Merging!

**Pull request merged**
