### PR TITLE
[TST] Remove duplicate `permuted_ols` tests

### LINKED ISSUE #3246: Remove or fix duplicate tests in `mass_univariate`
The following tests in `nilearn.mass_univariate.tests` appear to be duplicates, and do not seem to test the parameters mentioned in the function names and/or docstrings.

1. [`test_permuted_ols_intercept_withcovar_multivariate`](https://github.com/nilearn/nilearn/blob/8b27bbb65f9fe021cb534794167d8c37e8bed713/nilearn/mass_univariate/tests/test_permuted_least_squares.py#L607) appears to be a duplicate of [`test_permuted_ols_intercept_statsmodels_withcovar `](https://github.com/nilearn/nilearn/blob/8b27bbb65f9fe021cb534794167d8c37e8bed713/nilearn/mass_univariate/tests/test_permuted_least_squares.py#L542), and, while it says that it's a multivariate test, the tested data only contain one regressor.
1. [`test_permuted_ols_intercept_nocovar_multivariate `](https://github.com/nilearn/nilearn/blob/8b27bbb65f9fe021cb534794167d8c37e8bed713/nilearn/mass_univariate/tests/test_permuted_least_squares.py#L576) appears to be a duplicate of [`test_permuted_ols_intercept_nocovar`](https://github.com/nilearn/nilearn/blob/8b27bbb65f9fe021cb534794167d8c37e8bed713/nilearn/mass_univariate/tests/test_permuted_least_squares.py#L509) and only uses one regressor as well.
1. [`test_permuted_ols_withcovar_multivariate`](https://github.com/nilearn/nilearn/blob/8b27bbb65f9fe021cb534794167d8c37e8bed713/nilearn/mass_univariate/tests/test_permuted_least_squares.py#L461) says it's a multivariate test, but it only has one tested regressor.

I am not sure if we need to fix these tests, or if it would be sufficient just to remove them.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #3246.

Changes proposed in this pull request:

- Remove the following duplicate tests, which do not test multiple regressors:
    - test_permuted_ols_intercept_withcovar_multivariate
    - test_permuted_ols_intercept_nocovar_multivariate
    - test_permuted_ols_withcovar_multivariate

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Review by ymzayek — APPROVED** [review]
LGTM too, thanks!

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks @tsalo !

**Comment by bthirion** [comment]
Merging, then.

**Pull request merged**
