### PR TITLE
[ENH] add footer to all masker reports

### LINKED ISSUE #4300: Standardize footer of reports
The GLM reports mention Nilearn and links to the repo.

This should be extended to all reports

image

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes #4300 
- Extracted from #4295

Changes proposed in this pull request:

- add footer to masker reports

### CODE REVIEW

**Comment by Remi-Gau** [comment]
# For review

### Before (current dev doc)

- maskers reports: https://nilearn.github.io/dev/modules/generated_reports/masker_reports_examples.html

### After

- maskers reports: https://output.circle-artifacts.com/output/job/2c9fcc23-9f65-4d3a-9154-958b9dcd5876/artifacts/0/dev/modules/generated_reports/masker_reports_examples.html

**Comment by bthirion** [comment]
I like the change.

**Comment by Remi-Gau** [comment]
Given that this is not a bug fix (next release should be mostly bug fixes) I think we can take the time to think about it and possibly find a way to not display them in notebooks.

**Comment by Remi-Gau** [comment]
probably worth refactoring the CSS across reports first

- blocked by #4368

**Comment by Remi-Gau** [comment]
Given that I am working on the surface masker reports I am getting back to this one too.

image

@emdupre (given our previous [convo](https://github.com/nilearn/nilearn/issues/4300#issuecomment-1975650231)) can you have a look and let me know if you feel this one extra-line in the report would be too much of an eye-sore for notebook users? 

### HTML
[masker_reports_with_footer.zip](https://github.com/user-attachments/files/15610114/masker_reports_with_footer.zip)

### Notebooks
[visualize_reports_in_notebook.zip](https://github.com/user-attachments/files/15610859/visualize_reports_in_notebook.zip)

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Review by man-shu — APPROVED** [review]
LGTM!

**Review by emdupre — APPROVED** [review]

**Pull request merged**
