### PR TITLE
Fix bug in fetching files for ABIDE.

### PR DESCRIPTION
**Pull request by AlexandreAbraham**
For BH tutorial.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
How did that slip by? What's the test case to reproduce (I'm not asking you for a unit test, just something that I can type in a terminal).

Will fixing in master be enough for the tutorial, or will you need a release?

**Comment by AlexandreAbraham** [comment]
> How did that slip by?

I have absolutely no idea given that we did use this code for OHBM tutorial... I would like to fix this ASAP and not look at the root of the problem.

> What's the test case to reproduce (I'm not asking you for a unit test, just something that I can type in a terminal).

This should do:
```python
from nilearn.datasets import fetch_abide_pcp
a = fetch_abide_pcp(derivatives=['rois_cc200'], SITE_ID=[b'NYU'], n_subjects=1)
```

> Will fixing in master be enough for the tutorial, or will you need a release?

I will do a release.

**Comment by GaelVaroquaux** [comment]
OK, I can reproduce the bug and the fix.

I am a bit bothered that circleCI doesn't run due to docs.scipy.org timing out. It seems that before a release, or before merging this PR, we'd like to check that all the examples run well.

**Comment by KamalakerDadi** [comment]
It would be great if you could also address the documentation conflict with n_subjects ? As we have discussed it should be > 94.

**Comment by AlexandreAbraham** [comment]
> we'd like to check that all the examples run well

I agree.

> It would be great if you could also address the documentation conflict with n_subjects ?

Doc is fixed, thanks for reminding me!

**Comment by GaelVaroquaux** [comment]
>     we'd like to check that all the examples run well

> I agree.

I've been restarting CircleCI in the hope that it completes. But it might
be a lost cause given that I cannot get access to it at all on my
browser.

**Comment by AlexandreAbraham** [comment]
> I've been restarting CircleCI in the hope that it completes. But it might be a lost cause given that I cannot get access to it at all on my browser.

Can't we just run the examples on drago?

**Comment by GaelVaroquaux** [comment]
> Can't we just run the examples on drago?

It's not as nice, because it's not a clean, controled environment. But we
might have to do that.

**Comment by GaelVaroquaux** [comment]
> > Can't we just run the examples on drago?

> It's not as nice, because it's not a clean, controled environment. But we
> might have to do that.

OK, I'm running it on drago.

**Comment by GaelVaroquaux** [comment]
> OK, I'm running it on drago.

I am merging: it completed on drago without problems.

Don't release, I'll try doing it after some manual QAing.

**Pull request merged**
