### PR TITLE
FIX: broken online documentation search

### LINKED ISSUE #1586: Online documentation search is broken
image

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Attempts to FIX #1586.

Lets see it is fixed after CircleCI build is succeeded. Just a try.

Steps I have done so far to fix this:
I have created a new search engine with nilearn.github.io/* and generated html code snippet and pasted at the relevant area in doc/themes/nilearn/layout.html

### CODE REVIEW

**Comment by KamalakerDadi** [comment]
Seems like the search is working. Can easily check with this link
https://2840-1235740-gh.circle-artifacts.com/0/home/ubuntu/nilearn/doc/_build/html/index.html

@chrisfilo Can you confirm ?

**Comment by bthirion** [comment]
Indeed. Thx for fixing this.

**Comment by chrisfilo** [comment]
Works! Thanks!

Best,
Chris

**Comment by GaelVaroquaux** [comment]
Fantastic! Merging! Thanks everybody

**Pull request merged**
