### PR TITLE
[MRG] Fixed bug related to  get_clusters_table

### LINKED ISSUE #2548: nistats: dependence between function calls – strange bug may affect reproducibility
Hi,

I've encountered very strange behavior of two functions – `map_threshold` from `nistats.thresholding` module and `get_clusters_table` from `nistats.reporting` module. It seems like the threshold value returned by `map_threshold` depends on the last output value(s) of `get_clusters_table` function or some internal function variables. Impact seems to be severe (the higher the `cluster_threshold` value passed to `get_cluster_table`, the higher the threshold returned by subsequent call of `map_threshold`). 

Here is a simple demonstration: https://github.com/kbonna/decidenet/blob/master/activation_analysis/nistats_map_threshold_bug.ipynb

I've tried to find a source of the problem studying code of both functions, but I everything seems to be ok at first glance. 

Am I missing something simple?

### PR DESCRIPTION
**Pull request by kbonna**
fixes #2548 

Changes: 

- `reporting.get_clusters_table` function now makes a copy of statistical image array in case `cluster_threshold` is not None
- added test that ensure stat_image is not modified by `get_clusters_table` function

### CODE REVIEW

**Comment by jeromedockes** [comment]
thanks again @kbonna . please merge the pr on this branch that fixes pep8 whitespace issues and then I can merge into master

**Comment by kbonna** [comment]
@jeromedockes what is the name of that branch? i cannot find it

**Comment by jeromedockes** [comment]
this one: https://github.com/kbonna/nilearn/pull/1
(or if you prefer you can have a look at the end of the flake8 report [here](https://travis-ci.com/github/nilearn/nilearn/jobs/367867858#L370) and address the couple of formatting complaints it has)

**Comment by thomasbazeille** [comment]
Hi @kbonna ! Would you have time to merge the PR mentionned above by @jeromedockes ? We'd love to include this fix in the upcoming release!

**Comment by thomasbazeille** [comment]
@jeromedockes can you commit your modifications directly so that we can merge this soon ?

**Comment by jeromedockes** [comment]
> @jeromedockes can you commit your modifications directly so that we can merge this soon ?

I added the pep8 fixed and merged master, if CI is green you can merge

**Comment by bthirion** [comment]
All right, merging.
Huge thanks !

**Pull request merged**
