### PR TITLE
[MAINT] Improve error for nifti masker when fit is called without imgs or mask_img

### PR DESCRIPTION
**Pull request by ymzayek**
- Related to https://github.com/nilearn/nilearn/pull/4126#issuecomment-1847137828

Changes proposed in this pull request:

- Raise a more meaningful error than 
```bash
E TypeError: Data given cannot be loaded because it is not compatible with nibabel format:
E None
```

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
LGTM.

**Review by Remi-Gau — APPROVED** [review]
Long live meaningful error messages

**Comment by Remi-Gau** [comment]
Just realized that another test is failing. 

Can fix as soon as I am not a tablet.

**Comment by ymzayek** [comment]
Ok I see, so the failure has to due with order of errors basically. If we give an incorrect value to masker_strategy this will fail when `_get_mask_strategy` is called. I added the new error just above that so I can either move it under or change the test to pass an image object to fit.

**Comment by Remi-Gau** [comment]
Thanks @ymzayek

**Pull request merged**
