### PR TITLE
[FIX] fix deploy on release

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes none

Changes proposed in this pull request:

- use same workflow to deploy doc on main for dev and stable
- refactor most of the deploy into a bash script that can be run locally

### CODE REVIEW

**Comment by Remi-Gau** [comment]
For this one I would suggest, we will only know if it works after merging.
I would suggest:
- merge and check that the classic deploy dev doc on main is not affected: if it is we revert this PR and go back to the drawing board
- if the dev deploy is not affected then we can go a dummy test of a github release to see if it triggers a stable doc build and deploy

**Comment by bthirion** [comment]
Looks good, but it should be checked whether the deployment work well...

**Comment by bthirion** [comment]
> For this one I would suggest, we will only know if it works after merging. I would suggest:
> 
>     * merge and check that the classic deploy dev doc on main is not affected: if it is we revert this PR and go back to the drawing board
> 
>     * if the dev deploy is not affected then we can go a dummy test of a github release to see if it triggers a stable doc build and deploy

Makes sense.

**Review by bthirion — APPROVED** [review]

**Review by man-shu — APPROVED** [review]
Yes let's try it

**Comment by Remi-Gau** [comment]
This failed on main.
Reverting.

**Pull request merged**
