### PR TITLE
Rewrite the modulation warning as a print

### LINKED ISSUE #2872: modulation column for make_first_level_design_matrix
When having a 'modulation' column in the events.tsv that is passed to ```nilearn.glm.first_level.make_first_level_design_matrix```, a UserWarning occurs saying 
```
UserWarning: ‘modulation’ column found in the given events data.
```
This should be changed into a simple message saying that the 'modulation'-column is being used rather than printing a warning which is confusing.

### Benefits to the change
Clearer information about what is happening 

### Pseudocode for the new behavior, if applicable

```python
if modulation:
    print('Modulation column is found in events-data and is used')

```

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Fixes #2872

### CODE REVIEW

**Comment by rob-luke** [comment]
Does nilearn have an info or debug logger that would be more appropriate than a print for this purpose? Something like https://mne.tools/stable/generated/mne.set_log_level.html ?

**Comment by NicolasGensollen** [comment]
@rob-luke AFAIK, there is `nilearn._utils.logger.py`, which does a few things but still ends up doing a simple print depending on the verbose level and message level parameters:

https://github.com/nilearn/nilearn/blob/372c19388da752caf724029c3d65c89dd88add0d/nilearn/_utils/logger.py#L79-L81

The function `check_events` has no verbose parameter that we could use here, so I ended up using a simple print rather than logging but I don't have a strong opinion on this.

**Comment by rob-luke** [comment]
Thanks for sharing your thought process. I'm still learning the code base, so I appreciate the description.

**Comment by bthirion** [comment]
We should get inspiration from MNE logging, which is much more consistent than in Nilearn !

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Comment by NicolasGensollen** [comment]
>We should get inspiration from MNE logging, which is much more consistent than in Nilearn !

I'll put that on my todo list then! :)

Merging, thanks!

**Pull request merged**
