### PR TITLE
[DOC] Fix position of plots in relation to code blocks

### PR DESCRIPTION
**Pull request by ymzayek**
Part of #3728.

Fix stuff like this:

To become this:

### CODE REVIEW

**Comment by ymzayek** [comment]
All the changed examples are the ones with the rendered thumbnails found here: https://output.circle-artifacts.com/output/job/d0c106ac-119e-4f16-b188-2a70c295791d/artifacts/0/dev/auto_examples/index.html

**Comment by bthirion** [comment]
LGTM so far.

**Comment by ymzayek** [comment]
This one's ready. The failures are being dealt with in another PR

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Review by Remi-Gau — APPROVED** [review]

**Comment by Remi-Gau** [comment]
Thanks @ymzayek

**Pull request merged**
