### PR TITLE
set aspect of surface plot axes to 1

### PR DESCRIPTION
**Pull request by jeromedockes**

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
The rendering looks quite broken to me: https://2936-1235740-gh.circle-artifacts.com/0/home/ubuntu/nilearn/doc/_build/html/auto_examples/01_plotting/plot_3d_map_to_surface_projection.html#sphx-glr-auto-examples-01-plotting-plot-3d-map-to-surface-projection-py

**Comment by jeromedockes** [comment]
> The rendering looks quite broken to me

agreed. without setting the aspect it also looks bad sometimes,

surf

and not in a consistent manner.
since both are bad I guess the user can set the aspect to what they want.

sorry for the noise

**Comment by jeromedockes** [comment]
or we could hardcode the aspect to .8:

surf

**Comment by bthirion** [comment]
But what do you gain by doing so ?

**Comment by jeromedockes** [comment]
> But what do you gain by doing so ?

to avoid images looking like this:



right now the aspect is not fixed so the image will not look the same for everybody

**Comment by GaelVaroquaux** [comment]
Have you checked that it looks good on a variety of images / projections? If so, I am +1 for your fix.

**Comment by jeromedockes** [comment]
f1
f2
f3
f4

**Comment by GaelVaroquaux** [comment]
Looks good!

I'll merge after checking on circleCI that the images also look good.

**Comment by GaelVaroquaux** [comment]
Looking closely, it seems that the aspect ratio isn't really the right one:

https://2940-1235740-gh.circle-artifacts.com/0/home/ubuntu/nilearn/doc/_build/html/auto_examples/01_plotting/plot_3d_map_to_surface_projection.html#sphx-glr-auto-examples-01-plotting-plot-3d-map-to-surface-projection-py
versus
http://nilearn.github.io/auto_examples/01_plotting/plot_3d_map_to_surface_projection.html#sphx-glr-auto-examples-01-plotting-plot-3d-map-to-surface-projection-py

The one in master seems to be more reasonnable.

**Comment by KamalakerDadi** [comment]
This can be closed as @GaelVaroquaux had did this in a seperate PR #1654

**Pull request closed without merging**
