### PR TITLE
[MRG] Fix failures due to numpy 1.20

### LINKED ISSUE #2677: Failures in build due to numpy 1.20
Need to fix broken tests with latest package versions.

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Fixes #2677

### CODE REVIEW

**Comment by NicolasGensollen** [comment]
This should fix the build failure but I think we will have to clean the code of numpy type aliases to decrease the number of deprecation warnings. I think it'd be better to do that in a separate PR rather than on this one.

**Review by jeromedockes — APPROVED** [review]
Thanks @NicolasGensollen  for fixing this. I agree with you: it is best to merge this one now and start rooting out the deprecation warnings after

**Review by bthirion — APPROVED** [review]
the changes LGTM. CI seems happy too ;-)

**Comment by NicolasGensollen** [comment]
Merging, thanks!

**Pull request merged**
