### PR TITLE
[WIP] Random Parcellation Based Inference continued PR

### PR DESCRIPTION
**Pull request by lesteve**
see #196 for context.

Rebased on master, fixed merge conflicts and updated examples to follow the changes that have happened since.

Things that still need to be done:
- [ ] Look at non-tackled comments in #196
- [ ] verbose parameters and print statements may need to be updated following #369
- [ ] example .py and .png in the rst doc need to be updated because examples have moved around
- [ ] small differences between #196 plots and the ones obtained from this PR need reviewing
- [ ] examples rst titles (just (2) added to the non-RPBI example title) is not great and sometimes you don't actually see a difference in the gallery titles.
- [ ] just checking: there is a standardize=True for the masker in plot_haxby_rpbi.py with a comment that says that it is important for RPBI. The thing is that standardize=True is not used for the other RPBI examples. Any reason why?

### CODE REVIEW

**Comment by AlexandreAbraham** [comment]
> just checking: there is a standardize=True for the masker in plot_haxby_rpbi.py with a comment that says that it is important for RPBI. The thing is that standardize=True is not used for the other RPBI examples. Any reason why?

We should check in RPBI that data is standardize and raise a warning if not.

**Comment by bcipolli** [comment]
@lesteve I have been looking at this today, I think it could be useful for some of the RSA things I've been doing in the background.

I'd be happy to help push this forward.  I can take care of the merge conflicts and take care of the printing / verbose issues, for example.  I also think the coding of the `plot_haxby_rpbi` example could be simplified.    

I also had a couple of questions about analysis choices made in the `plot_haxby_rpbi` example.  I worry that my questions / concerns may be naive (I am still very new to neuroimaging analysis), but I will follow up with them in case they're questions others might have in learning from the examples.

**Comment by bcipolli** [comment]
2 questions to start:
* Why does the Haxby example limit data to houses and faces?  I think a comment there would be helpful.
* The code mentions that it takes the mean image per condition, as different samples within the same session have dependencies in time.
    * Isn't this issue also true (to a lesser degree) between conditions (house vs. face)?
    * Would this be (at least partially) alleviated by passing `detrend=True` in the mask?
    * Is this really a concern in a block design (24s per stimulus, 12s of rest in-between)?

**Comment by lesteve** [comment]
> I'd be happy to help push this forward.

That would be great indeed! There was some interest about working on it during the 0.1 sprint but other issues were deemed more important at the time.

I guess the first thing would be to rebase on master and fix merge conflicts. The bullet points mentioned in my message at the very top are good next steps.

**Comment by eickenberg** [comment]
> Isn't this issue also true (to a lesser degree) between conditions (house vs. face)?

Probably, but the extent depends on long range temporal interactions (which are typically drift components) that are difficult to quantify

> Is this really a concern in a block design (24s per stimulus, 12s of rest in-between)?

Drift cutoff in nipy GLM is set by default to a period of 128s. If the interactions are really that long, then this would be a concern. 

> Would this be (at least partially) alleviated by passing detrend=True in the mask?

Probably. But as mentioned elsewhere, this detrending needs to be done by chunks (as indicated by the `chunk` variable in the label data)

**Comment by bcipolli** [comment]
Rebased to master / fixed merge conflicts:
https://github.com/bcipolli/nilearn/tree/rpbi

Thanks @eickenberg ; I can perhaps include some of that in the example (like the detrending in chunks), and a bit more in comments.  I also think the code can be cleaned up a bit (after working through the example for some of the RSA-focused work I'm doing).

I'll also take a look at the bullet points listed!

**Comment by AlexandreAbraham** [comment]
Should we kill this one? Or resurrect it?

**Comment by bthirion** [comment]
I am wondering what the right placeholder for that method is: Nilearn/Nistats. There are two blockers: 
* the structure instantiated to obtain the p-values through permutation is a bit complex / hard to maintain.
* Ward clustering is very slow. Renn should be implemented instead.
The second point is easy to address, not the first one.

An idea that we have currently is to have a procedure that does not require the permutations, but this is a topic of research. Should go to nilearn-sandbox ?

**Comment by lesteve** [comment]
Closing this one, since this is in nilearn_sandbox now, see https://github.com/nilearn/nilearn_sandbox/pull/8.

**Comment by thomasbazeille** [comment]
@bthirion I think you were talking about integrating RPBI in nilearn.stats at some point ? Do you think it's something worth listing among proposed enhancements for upcoming sprint ?

**Comment by bthirion** [comment]
It can be listed, though with low priority: we need to be conservative with new features.
Also, we should rather integrate the (much) faster version that does not require permutation tests (Hoyos-Idrobo et al. PRNI 2016 IIRC).

**Pull request closed without merging**
