### PR TITLE
Add tests matplotlib dev

### LINKED ISSUE #2592: Add tests for matplotlib-dev
Add tests for `matplotlib-dev` with failures allowed (or not?) in order to anticipate upcomming changes which could cause failures in future releases. 
See for example: #2591 and #2583

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Closes #2592 .

Changes proposed in this pull request:

- Add tests for `matplotlib-dev` such as to anticipate upcoming failures (see #2592).

*Note: Not sure this is the best/cleanest way to do it, I'm open to suggestions*

### CODE REVIEW

**Comment by jeromedockes** [comment]
looks good but I can't find the travis build?

**Comment by NicolasGensollen** [comment]
@jeromedockes Indeed, I couldn't see it either for some reason... 
I rebased it since changes occured in the mean time anyway, and Travis seems to be running for now.

**Comment by jeromedockes** [comment]
great! I think the job with matplotlib dev needs to be included in the matrix ( [doc](https://docs.travis-ci.com/user/build-matrix/#matching-jobs-with-allow_failures) ) . allowed_failures says which jobs in the build matrix are allowed to fail, it does not add jobs to the matrix

**Review by jeromedockes — APPROVED** [review]
LGTM, thanks!
failures with matplotlib dev seem genuine and can be addressed in separate prs if necessary

**Comment by NicolasGensollen** [comment]
@jeromedockes thanks! Merging this...

**Comment by GaelVaroquaux** [comment]
> failures with matplotlib dev seem genuine and can be addressed in separate prs if necessary

It's bad practice to have failing tests in master. I would have avoided
to merge this with failing tests.

Now, the race is open to fixing it :).

**Comment by jeromedockes** [comment]
that's true, but this particular job is an "allowed_failure"

**Comment by GaelVaroquaux** [comment]
> that's true, but this particular job is an "allowed_failure"

Point taken. Good job team!

**Comment by jeromedockes** [comment]
surf stat map failure is due to https://github.com/matplotlib/matplotlib/issues/18939

**Pull request merged**
