### PR TITLE
[FIX] LGTM errors

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Fixes some LGTM errors:
https://lgtm.com/projects/g/nilearn/nilearn/?mode=list&severity=error

### CODE REVIEW

**Review by agramfort — APPROVED** [review]
thx @DimitriPapadopoulos !

**Comment by DimitriPapadopoulos** [comment]
The codecov alert doesn't make sense, as is often the case with Codecov. It's a false positive.

**Review by agramfort — APPROVED** [review]

**Review by jeromedockes — APPROVED** [review]
thanks!

**Comment by agramfort** [comment]
Thx @DimitriPapadopoulos

**Comment by bthirion** [comment]
Thx !

**Pull request merged**
