### PR TITLE
Fix nilearn under scikit-learn 0.24

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Do not import from modules that have been made private and moved

Currently, nilearn does not run on sklearn 0.24. This PR fixes it.

### CODE REVIEW

**Comment by jeromedockes** [comment]
one travis failure is unrelated and would be fixed by #2514 
[this one](https://api.travis-ci.com/v3/job/348940066/log.txt) seems genuine?
I am also wondering if we should have a ci job running with the master branches of the dependencies (I am thinking a scheduled one with master, rather than one triggered by pull requests) we have one using release candidates ("pre-release checks"), but I am not sure if all dependencies make release candidates and how long before the releases, and I am not sure it makes sense to trigger it for PRs

**Comment by kchawla-pi** [comment]
This was outlined in #1728 . If you wish, you can reopen that discussion.

**Comment by jeromedockes** [comment]
> This was outlined in #1728 . If you wish, you can reopen that discussion.

yes I think we can. With respect to #2224 which closed #1728 I am
wondering if we should:

- test with master branches or nightly builds besides or instead of alpha, beta, rc releases
- make this a scheduled job rather than one triggered by PRs

WDYT?

**Comment by kchawla-pi** [comment]
I'll opine in #1728 to not clutter this PR.

**Comment by GaelVaroquaux** [comment]
I've fixed the genuine failure. This PR is now green.

**Comment by bthirion** [comment]
Will be merged within 24hrs unless I hear otherwise.

**Comment by GaelVaroquaux** [comment]
Based on the feedback above, I am merging this.

**Pull request merged**
