### PR TITLE
Enh update badges

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Update build badge since we are relying on Travis since #2633

### CODE REVIEW

**Comment by emdupre** [comment]
The GitHub Actions Build Status doesn't [look quite right](https://github.com/NicolasGensollen/nilearn/blob/enh-update-badges/README.rst), likely because this PR also changes the workflow name.

You could avoid that change -- and get the currently correct badge -- using this URL: https://github.com/nilearn/nilearn/workflows/nilearn%20tests%20on%20GitHub%20Actions/badge.svg?branch=master&event=push

But I'm not sure if you'd prefer to change the workflow name to 'build' more generally !

**Comment by NicolasGensollen** [comment]
Thanks @emdupre ! 

>The GitHub Actions Build Status doesn't look quite right, likely because this PR also changes the workflow name.

Exactly, but the button should be OK once this is merged (assuming I didn't mess up the URL...).
I changed the workflow name mostly for aesthetic reasons (the previous name was a bit too long and not rendering well in a badge in my opinion). But we can leave it as before or split the badge addition and workflow name change in two separate PRs to be sure that there is no rendering issues. I'm OK with all strategies.

**Comment by emdupre** [comment]
> I changed the workflow name mostly for aesthetic reasons (the previous name was a bit too long and not rendering well in a badge in my opinion).

I certainly respect aesthetic reasons 🙂
This LGTM, then ! Thx !

**Review by emdupre — APPROVED** [review]

**Review by bthirion — APPROVED** [review]
LGTM, Thx

**Pull request merged**
