### PR TITLE
[WIP] Add JunitXML support to CircleCI

### PR DESCRIPTION
**Pull request by kchawla-pi**

### CODE REVIEW

**Comment by kchawla-pi** [comment]
THe CircleCI build passed here:
https://circleci.com/gh/kchawla-pi/nilearn/188#tests/containers/0

**Comment by kchawla-pi** [comment]
The file generated in build artifacts is this one: https://188-139860812-gh.circle-artifacts.com/0/home/circleci/project/doc/_build/test-results/sphinx-gallery/junit.xml

Anything more to be done here?
@GaelVaroquaux

**Comment by bthirion** [comment]
The xml file does not render well in my browser.

**Comment by kchawla-pi** [comment]
Mine neither, but neither does the Junit xml of MNE

**Comment by GaelVaroquaux** [comment]
Weird. Circle is not showing up in this PR.

**Comment by kchawla-pi** [comment]
That's because I added CircleCI to my fork of Nilearn so it wouldn't use the containers available to Nilearn proper.
Here's the link for the CircleCI run: https://circleci.com/gh/kchawla-pi/nilearn/188

**Comment by GaelVaroquaux** [comment]
> Here's the link for the CircleCI run: https://circleci.com/gh/kchawla-pi/ nilearn/188

OK. It works: the test summary it properly displayed. It seems that this
should be mergeable, no?

**Comment by bthirion** [comment]
+1 for merge

**Pull request merged**
