### PR TITLE
[MAINT] No need to inherit `object` in Python 3

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Classes inherit from `object` implicitly.

### CODE REVIEW

**Review by NicolasGensollen — APPROVED** [review]
Was about time to get rid of these...
Thanks @DimitriPapadopoulos ! 👍

**Review by ymzayek — COMMENTED** [review]
Thanks @DimitriPapadopoulos ! I found one that is not included here https://github.com/nilearn/nilearn/blob/6920ffae3bbc2eafefd0f66ff36af5ca4c9f22ee/nilearn/decoding/space_net.py#L206

Otherwise LGTM!

**Review by ymzayek — APPROVED** [review]
Great thanks!

**Review by bthirion — APPROVED** [review]
Thx !

**Pull request merged**
