### PR TITLE
Fixed bug in intersect_mask

### PR DESCRIPTION
**Pull request by arthurmensch**
Fixed bug #622 arising when providing a list of string to `intersect_mask`

### CODE REVIEW

**Comment by bthirion** [comment]
looks good. I think it's worth adding a test.

**Comment by arthurmensch** [comment]
Conda with python 3.4 seems to fail loading, does anyone know where this comes from ?

**Comment by GaelVaroquaux** [comment]
Not sure why. I just restarted the run to see if it's reproducible, or just a glitch in the continuous integration system.

**Comment by GaelVaroquaux** [comment]
So, it completed!

You should however add a test before we can merge. One that is failing without your fix and passing with your fix.

**Comment by arthurmensch** [comment]
Done : added test fails on master

**Comment by GaelVaroquaux** [comment]
Excellent! Merging. Thank you.

**Pull request merged**
