### PR TITLE
[MRG] Broken links. Solved #684

### PR DESCRIPTION
**Pull request by MartinPerez**
I fixed the links of the right top corner of the banner in layout.html. Solution for issue #684

### CODE REVIEW

**Comment by lesteve** [comment]
Did you mean to have the code adding the installation GUI (i.e. from #687) in here?

**Comment by MartinPerez** [comment]
This has nothing to do with #687 , The links in the top corner of the banner of the webpage had to be fixed to the correct links. They had the wrong references;

**Comment by AlexandreAbraham** [comment]
Yes, but the code of your PR #687 is included in this PR.

**Comment by MartinPerez** [comment]
Oh I am sorry I realized I branched from the other branch instead of master. I will fix this.

**Comment by AlexandreAbraham** [comment]
No problem ;). It happened to all of us.

**Comment by MartinPerez** [comment]
I created a clean branch with the correct commit, only 7 lines modified.

**Comment by lesteve** [comment]
Good effort, but it looks like you need to try again :confounded:

**Pull request closed without merging**
