### PR TITLE
WIP FIX: score method for all components decomp estimators

### LINKED ISSUE #1744: Finding Optimal Number of Components using dict_learning as well as canICA
Dear All,
Thanks a lot for helping in Voxel based Morphometry using dictionary learning as well as using canICA.
Regarding selecting the optimal number of components, we can select the log (the number of data points). So the number of data points would be the total number of data points right?

log(x=60 * y=72 * z=60 * n=600) = 18.8 ~19  so
n_components = 19 ??
[here 600 is the number of subjects]

Thanks a lot.

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Fixes #1744

### CODE REVIEW

**Comment by KamalakerDadi** [comment]
This PR is ready. I made this WIP in order to replace with new dataset.

**Comment by KamalakerDadi** [comment]
Exactly, can't be merged without solving memory intensive line coded ```return np.maximum(0., 1. - res_var / np.sum(X ** 2))```
Caution: When X is huge data matrix you will have memory errors.

**Comment by kchawla-pi** [comment]
Good to know. Thanks.

**Comment by kchawla-pi** [comment]
Does this mean this feature is unusable, unworkable?

**Comment by kchawla-pi** [comment]
> Exactly, can't be merged without solving memory intensive line coded

This is not the PR i had commented on about the example.

**Comment by jeromedockes** [comment]
> Exactly, can't be merged without solving memory intensive line coded `return np.maximum(0., 1. - res_var / np.sum(X ** 2))`
> Caution: When X is huge data matrix you will have memory errors.

but it does not allocate anything bigger than X or res_var ?

**Comment by KamalakerDadi** [comment]
>Does this mean this feature is unusable, unworkable?

Your question doesn't help how to solve this potential problem I am discussing.

**Comment by KamalakerDadi** [comment]
>  Exactly, can't be merged without solving memory intensive line coded return np.maximum(0., 1. -> res_var / np.sum(X ** 2))
   > Caution: When X is huge data matrix you will have memory errors.

>but it does not allocate anything bigger than X or res_var ?

Yeah. When X is large ?

**Comment by KamalakerDadi** [comment]
@jeromedockes 
You can see here the build was failing because of that issue. 

https://circleci.com/gh/nilearn/nilearn/4142?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

It was on adhd.

**Comment by jeromedockes** [comment]
> Yeah. When X is large ?

you can avoid allocating memory for `X **2 ` by replacing `np.sum(X**2)` with `np.einsum('ij,ij', x, x)`

**Comment by KamalakerDadi** [comment]
>    Yeah. When X is large ?

>you can avoid allocating memory for X **2 by replacing np.sum(X**2) with np.einsum('ij,ij', x, x)

Ok. Let me profile it to see the benefit of ```np.einsum``` to ```np.sum```.

**Comment by jeromedockes** [comment]
> Ok. Let me profile it to see the benefit of ```np.einsum``` to ```np.sum```.

the benefit is not of `einsum` vs `sum`, but avoiding to store `X**2`

**Comment by bthirion** [comment]
> May be I will try to demo on one of the estimator in plot_compare_decomposition.

Makes sense, thx.

**Comment by KamalakerDadi** [comment]
Superseded by #2577

**Pull request closed without merging**
