### PR TITLE
Add pathlib.Path support for nilearn.datasets

### PR DESCRIPTION
**Pull request by RaphaelMeudec**
This PR adds support for `pathlib.Path` to `data_dir` argument in datasets fetchers. All the fetchers from `nilearn.datasets` now accepts `pathlib.Path` or a string (instead of string only).

I have modified the tests from all fetchers which had to cast the `tmp_path` fixture to a string. Now the fixture is used directly as `data_dir` argument. This means there is no more tests for `data_dir` as a string, and I wasn't sure if I needed to keep both case (through a parametrize for each test for example)

The PR can easily be read commit by commit:

1. Changes to `nilearn.datasets.utils` that add `pathlib.Path` support
2. Modifications of the tests to avoid casting `tmp_path` to string everytime
3. Update document variable `data_dir`
4. Whatnew entry

I'm open to your opinions on the "no more `data_dir` as string tests". Maybe I could add both cases (`pathlib.Path` or string) in the tests of the following methods (`nilearn.datasets.utils.get_dataset_dir` and `nilearn.datasets.utils.fetch_files`) and leave the pathlib everywhere else?

### CODE REVIEW

**Comment by jeromedockes** [comment]
great, thanks! that's very useful

> Maybe I could add both cases (`pathlib.Path` or string) in the tests of the following methods (`nilearn.datasets.utils.get_dataset_dir` and `nilearn.datasets.utils.fetch_files`) and leave the pathlib everywhere else?

yes that sounds good! it's useful to check that these 2 continue working with strings, but probably not worth the trouble to parametrize every fetcher's test

**Comment by RaphaelMeudec** [comment]
@jeromedockes I pushed the changes, let me know if there are stuff to change!

**Comment by jeromedockes** [comment]
> @jeromedockes I pushed the changes, let me know if there are stuff to change!

everything looks great, thanks! On a similar topic if you have time you can have a look at #2803 :)

**Review by jeromedockes — APPROVED** [review]

**Review by NicolasGensollen — APPROVED** [review]
Looks great ! Thanks @RaphaelMeudec ! :+1:

**Review by bthirion — APPROVED** [review]

**Comment by bthirion** [comment]
LGTM. Merging, thx !

**Pull request merged**
