### PR TITLE
Release 0.8.0

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Prepare release `0.8.0`.

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Comment by NicolasGensollen** [comment]
Thanks!
Merging...

**Comment by jeromedockes** [comment]
IIRC you wanted to merge #2605  before doing a release?

**Comment by jeromedockes** [comment]
> I haven't looked at it since then, so I think there is some work to do to update it. If you think we should merge it before doing this release, I can try to update it today.

I don't have a preference; I just came across the comment that said it
should be merged before next release and put a reminder here in case it
had been forgotten. If after all you prefer to leave it for the 0.8.1
that's fine by me!

**Comment by NicolasGensollen** [comment]
I decided to finish the release as it was already on its way...
I'll resurrect the PR for 0.8.1 :)

**Pull request merged**
