### PR TITLE
[DOC] Issue 2692 unpaired/paired example

### LINKED ISSUE #2692: Add example of two-sample t-test
Examples [9.6.3](https://nilearn.github.io/auto_examples/05_glm_second_level/plot_second_level_paired_sample_test.html#sphx-glr-auto-examples-05-glm-second-level-plot-second-level-paired-sample-test-py) and [9.6.4](https://nilearn.github.io/auto_examples/05_glm_second_level/plot_second_level_two_sample_test.html#sphx-glr-auto-examples-05-glm-second-level-plot-second-level-two-sample-test-py) are the same with different titles, I believe.

It seems that both of them refer to the 'paired-sample t-test'. In this case, example 9.6.3 is correct but 9.6.4 has to be fixed.

### PR DESCRIPTION
**Pull request by psadil**
Closes #2692  .

Changes proposed in this pull request:

- Adds unpaired t-test example 
- I goofed while renaming the file, and so it looks like a whole file was replaced (i.e., most of the content from what was `plot_second_level_paired_sample_test.py` is in `plot_second_level_two_sample_test.py`).
- changing the filename changes the order of the examples

### CODE REVIEW

**Comment by psadil** [comment]
> 
> 
> I don't see CircleCI in the checklist, that's weird... 🤔
> Could you request a full build to trigger it?
> 
> ```
> git commit --allow-empty -m "[circle full] Request full build"
> ```

Will do. 

Which checklist is this? Are you talking about the auto checks on this pull request? Or was there a checklist I should have followed before requesting the pull?


> 
> 
> LGTM ! Can you rebuild the example in the doc ?

Sure! But, just checking, does that happen when there is a full CircleCI build?

**Comment by NicolasGensollen** [comment]
>Are you talking about the auto checks on this pull request?

Yes, I might get tired but I don't see circleCI in the list...

>Sure! But, just checking, does that happen when there is a full CircleCI build?

Yes, full build will rebuild everything, including the new example you added.

**Comment by psadil** [comment]
It looks like that commit message didn't trigger a full build. Is there some other step I'm missing?

**Comment by bthirion** [comment]
I've run the example on my box, and it is fine.
Thx !

**Comment by bthirion** [comment]
> It looks like that commit message didn't trigger a full build. Is there some other step I'm missing?

Not really. Can you may be pull from master and re-trigger the doc build ?

**Comment by psadil** [comment]
not sure whether this is relevant, but I'm now noticing the following warning when I build the docs locally (e.g., in the main `nilearn` folder, when I run `make doc-plot`). I assume it was there before and that I just wasn't looking closely. 

```
checking consistency... <**path-hidden**>/nilearn/doc/auto_examples/05_glm_second_level/plot_second_level_paired_sample_test.rst: WARNING: document isn't included in any toctree
```

**Comment by bthirion** [comment]
You probably have to edit doc/glm/second_level_model.rst
Thx again !

**Comment by NicolasGensollen** [comment]
@psadil I pushed a fix to your branch. Note that, for the doc to build, you will need to merge or rebase on top of master to get a recent fix (#2825) . Once this is done, just make an empty commit with `[circle full]` to build the full doc.
Let me know if this isn't clear, I can help!

**Comment by psadil** [comment]
I think the issue with circleci no running may have been due to my account. The second to last commit with `[circle full]` (e835a45) didn't trigger a build. But then I linked my github account to circleci (I didn't previously have a circleci account). It seems like the last commit (4bb6ebc) worked.

**Review by bthirion — APPROVED** [review]
looks great, thx !

**Pull request merged**
