### PR TITLE
[MAINT] Put pep8 checks in dedicated workflow

### PR DESCRIPTION
**Pull request by NicolasGensollen**
As running them as part of the Python 3.5 workflow was confusing.

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
LGTM, but where does the output appear in the checks ?

**Comment by NicolasGensollen** [comment]
>LGTM, but where does the output appear in the checks ?

Indeed, I messed up the indentation again... :sweat: 
It is fixed and PEP8 is running correctly now, thanks!

**Comment by jeromedockes** [comment]
> Indeed, I messed up the indentation again... 

the joys of yaml :)

**Review by jeromedockes — APPROVED** [review]
thanks!

**Review by bthirion — APPROVED** [review]

**Comment by bthirion** [comment]
Merging, thx !

**Pull request merged**
