### PR TITLE
Fix doc in Region Extractor

### PR DESCRIPTION
**Pull request by AlexandreAbraham**
Taking over #898.

### CODE REVIEW

**Comment by KamalakerDadi** [comment]
@AlexandreAbraham Circleci is failing if you haven't noticed.

May be space is missing in the attributes as I have seen some previous direct fixes in master.

**Comment by AlexandreAbraham** [comment]
> May be space is missing in the attributes as I have seen some previous direct fixes in master.

Your indentation is good. It's the exact same as in CanICA. I don't understand what's failing.

**Comment by KamalakerDadi** [comment]
@AlexandreAbraham Its a dirty idea but could you break the line and run again to see if it passes. May be line is lengthy ?

**Comment by AlexandreAbraham** [comment]
For the moment I'm trying to generate the doc locally to debug faster and it doesn't work... Did you managed to do it?

**Comment by KamalakerDadi** [comment]
> Did you managed to do it?
No. I am searching solutions in sphinx repository. May be I will fetch this PR and try some solutions locally.

**Pull request merged**
