### PR TITLE
Fix example 9.3.12

### LINKED ISSUE #2624: Bug in example 9.3.12
It looks like the last section (`9.3.12.4`) in this [example](https://nilearn.github.io/auto_examples/02_decoding/plot_haxby_different_estimators.html#sphx-glr-auto-examples-02-decoding-plot-haxby-different-estimators-py) is not doing what it is supposed to. 

More precisely, the following lines

```python
# Restrict the decoding to face vs house
condition_mask = np.logical_or(stimuli == b'face', stimuli == b'house')
stimuli = stimuli[condition_mask]
fmri_niimgs_condition = index_img(func_filename, condition_mask)
```

build objects that aren't used afterwards for the plotting of the stat maps. 

Moreover, with Pandas `1.1.3`, the condition mask I get is empty:

```python
condition_mask = np.logical_or(stimuli == b'face', stimuli == b'house')
sum(condition_mask.values)
0
```

```python
condition_mask = np.logical_or(stimuli == 'face', stimuli == 'house')
sum(condition_mask.values)
216
```

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Closes #2624

### CODE REVIEW

**Comment by KamalakerDadi** [comment]
Any reason why Travis is not listed in the CIs. It also happened to my PR.

**Comment by NicolasGensollen** [comment]
@KamalakerDadi it looks like Travis just changed their pricing policy (see this [link](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)), such that we don't have enough credits as can be seen [here](https://travis-ci.com/github/nilearn/nilearn/requests)
See also this [post](https://dev.to/yoursunny/travis-ci-pricing-change-usage-based-billing-5gba)

**Comment by bthirion** [comment]
Then we have to send an application to Travis to get credit as an OSS (see scikit image).

**Comment by NicolasGensollen** [comment]
Indeed, from [here](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing):

_We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment._ 
_Please include:_

- _Your account name and VCS provider (like `travis-ci.com/github/[your account name]` )_
- _How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or discuss a renewable amount)_

If I understand correctly, we have to estimate our monthly needs in terms of credits (10K corresponds to 1000 minutes build time in a Linux env).

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Comment by KamalakerDadi** [comment]
Rather than fitting a model twice, can we not save ```coef_img_``` with respect to conditions face or house?

**Comment by NicolasGensollen** [comment]
@KamalakerDadi as far as I understand, this is what was done before (the map was saved for house for each classifier and plotted afterwards). However, as the text of the last section was explaining that the decoding was restricted to face vs house and applying a condition mask accordingly, I supposed that this is what was intended when writing the example. 
I can go back to saving the map for house and delete the masking and second training code if this is better, but I think we'd have to change the text and legends accordingly.

**Comment by KamalakerDadi** [comment]
>@KamalakerDadi as far as I understand, this is what was done before (the map was saved for house for each classifier and plotted afterwards). However, as the text of the last section was explaining that the decoding was restricted to face vs house and applying a condition mask accordingly

Makes sense. LGTM.

**Comment by KamalakerDadi** [comment]
>@KamalakerDadi it looks like Travis just changed their pricing policy (see this link), such that we don't have enough credits as can be seen here
See also this post

Thanks.

**Comment by NicolasGensollen** [comment]
Thanks! Merging...

**Pull request merged**
