### PR TITLE
BF: "<i8" ==> "int" in test_fetch_adhd (fixes issue #658

### PR DESCRIPTION
**Pull request by dohmatob**

### CODE REVIEW

**Comment by AlexandreAbraham** [comment]
Thanks, you're the best to detect "leaks" ;).

Merging.

**Comment by banilo** [comment]
+1

**Comment by lesteve** [comment]
Just curious about this one: `np.dtype('i8')` is the same as `np.dtype('int')` (at least on a 64bit machine, it may well be the same as 'i4' on a 32bit machine). I don't see how this change could fix anything. Also the subject numbers are nowhere close to 2**63 ...

**Comment by dohmatob** [comment]
Short answer: on my 64-bit machine "<i8" and "int" are indeed different. If
you want an int, just say "int" explicitly and don't play around with
endianness, etc. just for fun. Plus the code is more readable. Maybe it's
time to have more coverage on 64-bit machines, etc. ?

On Tue, Jul 14, 2015 at 10:25 PM, Loïc Estève <notifications@github.com>
wrote:

> Just curious about this one: np.dtype('i8') is the same as np.dtype('int')
> (at least on a 64bit machine, it may well be the same as 'i4' on a 32bit
> machine). I don't see how this change could fix anything. Also the subject
> numbers are nowhere close to 2**63 ...
>
'cause I have a 64-bit box...

>
>
—
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/pull/663#issuecomment-121371988>.
>



-- 
DED

**Comment by lesteve** [comment]
Sorry, what ? Better to chat face to face about this one ...

**Comment by AlexandreAbraham** [comment]
I don't understand it either.

**Comment by AlexandreAbraham** [comment]
We agree on the fact that, on 64 bit machines (most of them now) this patch does not change anything. BTW, all our test machines are 64 bits. I merge it because Elvis is right on the fact that specifying that this is an 8 bit integer is absolutely not necessary and may trouble people. There was no bug in the first place.

**Comment by dohmatob** [comment]
Bottom line is the fix worked for me. OK, people let's move ahead. I will
not spend more time on this (which i don't have, BTW). Have fun ;)

On Wed, Jul 15, 2015 at 10:52 AM, Alexandre Abraham <
notifications@github.com> wrote:

> We agree on the fact that, on 64 bit machines (most of them now) this
> patch does not change anything. BTW, all our test machines are 64 bits. I
> merge it because Elvis is right on the fact that specifying that this is an
> 8 bit integer is absolutely not necessary and may trouble people. There was
> no bug in the first place.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/pull/663#issuecomment-121534077>.
>



-- 
DED

**Comment by AlexandreAbraham** [comment]
Well, that was just for you. If '<i8' and 'int' are different on your 64 bit machine, you may have a serious problem.

But the patch was useful, yes, thanks for that.

**Pull request merged**
