### PR TITLE
[DOC] Workaround for sphinx warning reference target not found for 2 scikit-learn (v1.3) classes

### PR DESCRIPTION
**Pull request by ymzayek**
See #3800. See also https://github.com/scikit-learn/scikit-learn/issues/26761

This warning fails the full doc build

Changes proposed in this pull request:

- Add nitpicky option to conf.py
- Add reference targets to ignore
-

### CODE REVIEW

**Comment by glemaitre** [comment]
You can resolve the problem by using intersphinx to make the link work as done there: https://github.com/microsoft/LightGBM/pull/5956/files

You can see the https://github.com/scikit-learn/scikit-learn/pull/26747#issuecomment-1619128349 for more details.

**Comment by Remi-Gau** [comment]
@glemaitre 

I am pretty sure we are already using intersphinx: 🤷🏾‍♂️

**Review by Remi-Gau — APPROVED** [review]

**Comment by ymzayek** [comment]
@glemaitre we already use it and it works correctly as can be seen in our stable docs based on sklearn v1.2 e.g. see link to Pipeline class here: https://nilearn.github.io/stable/modules/generated/nilearn.regions.RegionExtractor.html#nilearn.regions.RegionExtractor.set_params. That's why I suspect it comes from the source code particularly from the file referenced in my comment in https://github.com/scikit-learn/scikit-learn/issues/26761. Maybe just a syntax thing?

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Pull request merged**
