### PR TITLE
[MRG+1] Fix comment PR #1299, removed calling double get_data for dtype

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Addressing comment from PR #1299

### CODE REVIEW

**Comment by KamalakerDadi** [comment]
```python
File "C:\Miniconda-x64\lib\site-packages\nilearn\input_data\tests\test_nifti_maps_masker.py", line 81, in test_nifti_maps_masker
    assert_raises(ValueError, masker11.fit)
  File "C:\Miniconda-x64\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "C:\Miniconda-x64\lib\site-packages\nilearn\_utils\testing.py", line 207, in write_tmp_imgs
    os.remove(filename)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\nilearn_hvjmhw.nii'
```
```python
File "C:\Miniconda-x64\lib\site-packages\nilearn\tests\test_niimg_conversions.py", line 282, in test_check_niimg_wildcards
    img_3d.get_data())
  File "C:\Miniconda-x64\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Miniconda-x64\lib\site-packages\nilearn\_utils\testing.py", line 207, in write_tmp_imgs
    os.remove(filename)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\nilearn_ovmkef.nii'
```
I am not sure why suddenly these errors ?

Shall we try ```del masker11``` and ```del img_3d``` ? If yes, I can push and see if it fixes ```WindowsError``` with AppVeyor ?

**Comment by KamalakerDadi** [comment]
Also CircleCI failure seems like spurious to me. Locally, I can see building html successfully.

**Comment by KamalakerDadi** [comment]
Can I have reviews on this please ?

**Comment by aabadie** [comment]
LGTM +1. Appveyor fixes are ok.

**Comment by GaelVaroquaux** [comment]
LGTM. Thanks a lot. Merging. Sorry for the delay in reviewing.

**Pull request merged**
