### PR TITLE
fix comparison to string

### LINKED ISSUE #2915: syntax error in glm
#2532 introduced a syntax error that is breaking the MNE-Python CIs.  Specifically:

https://github.com/nilearn/nilearn/blob/f9deafe828dc21d5d4dd54b772da820ee1f4cac5/nilearn/glm/first_level/first_level.py#L147

leads to this in our documentation CI build:

```
Traceback (most recent call last):
  File "/home/circleci/project/tutorials/inverse/20_dipole_fit.py", line 24, in <module>
    from nilearn.plotting import plot_anat
  File "/home/circleci/.local/lib/python3.8/site-packages/nilearn/plotting/__init__.py", line 51, in <module>
    from .matrix_plotting import (plot_matrix, plot_contrast_matrix,
  File "/home/circleci/.local/lib/python3.8/site-packages/nilearn/plotting/matrix_plotting.py", line 13, in <module>
    from nilearn.glm.contrasts import expression_to_contrast_vector
  File "/home/circleci/.local/lib/python3.8/site-packages/nilearn/glm/__init__.py", line 31, in <module>
    from nilearn.glm import first_level
  File "/home/circleci/.local/lib/python3.8/site-packages/nilearn/glm/first_level/__init__.py", line 6, in <module>
    from nilearn.glm.first_level.first_level import (
  File "/home/circleci/.local/lib/python3.8/site-packages/nilearn/glm/first_level/first_level.py", line 147
    if ((noise_model[:2] != 'ar') and (noise_model is not 'ols')):
                                       ^
SyntaxError: "is not" with a literal. Did you mean "!="?
```

Nilearn version: looks like our CI installs 0.8.0

cc @rob-luke

### PR DESCRIPTION
**Pull request by drammock**
closes #2915

### CODE REVIEW

**Review by rob-luke — APPROVED** [review]
Thanks @drammock, sorry I broke the CI

**Review by tsalo — APPROVED** [review]
The changes look good to me. Thanks for the fix.

**Comment by agramfort** [comment]
Thx @drammock

**Comment by bthirion** [comment]
Thx for the fix !

**Comment by drammock** [comment]
any chance someone could push out a 0.8.1 release, now that this is merged?

**Comment by jeromedockes** [comment]
there might be one in September but probably not before AFAIK

**Comment by bthirion** [comment]
Maybe we can do one next week if this is important for you.

**Comment by drammock** [comment]
> Maybe we can do one next week if this is important for you.

for now we've changed our CIs to install a specific commit from GitHub so the urgency is gone.

**Pull request merged**
