### PR TITLE
Grammar fix

### PR DESCRIPTION
**Pull request by banilo**
Tries to fix an expression about passing on arguments etc. to other functions that appears in various contexsts.

"function argument passed to" -> 231.000 hits on google
"function argument passed on to" -> 120.000.000 hits on google

### CODE REVIEW

**Comment by eickenberg** [comment]
-1000

> No results found for "function argument passed on to".

1) "Passed to" is perfectly fine (cf "passed by reference", "passed by value" also)
2) check your google search - it probably took away the quotes. If you take away the quotes you get 121e6 results. If you keep them, you get 0.

**Comment by banilo** [comment]
> -1000

thesis! ;)

But, you are probably right. Hm...

**Comment by eickenberg** [comment]
sorry to thwart your efforts to be top contributor to nilearn wrt lines commited measure ;)

**Comment by lesteve** [comment]
:confused: did you read [that](https://github.com/nilearn/nilearn/pull/562/files#r29421198)? And have you looked at your commit history + diff ?

Closing this one as a pure :trollface:

**Pull request closed without merging**
