### PR TITLE
[INFRA] Configure doc build CI to always host artifacts

### PR DESCRIPTION
**Pull request by ymzayek**
- Closes None

With the current set up, a failure on the doc build prevents circleci from hosting the docs that have been built. This is annoying since the htmls exist but cannot be easily viewed (sometimes for very trivial errors) and thus hinders the review process. This PR changes the configuration so that the docs are always hosted if a build exists. Note that deploy will still only run on main only with a successful doc build.

I've tested this on my fork on [main](https://github.com/ymzayek/nilearn) and in a [PR](https://github.com/ymzayek/nilearn/pulls)

### CODE REVIEW

**Comment by bthirion** [comment]
This PR is a bit cryptic to me. Any way to check that it works OK ?

**Comment by ymzayek** [comment]
@bthirion I've run several tests on my fork on [main](https://github.com/ymzayek/nilearn) and in a [PR](https://github.com/ymzayek/nilearn/pulls)

**Comment by ymzayek** [comment]
> At some point we are going to need a diagram how the CI for the doc works. I am still not as good as you are juggling with it.

Yes happy to discuss it and explain why we do it this way. We can also think about how to document it better for devs

**Comment by Remi-Gau** [comment]
> > At some point we are going to need a diagram how the CI for the doc works. I am still not as good as you are juggling with it.
> 
> Yes happy to discuss it and explain why we do it this way. We can also think about how to document it better for devs.

Can we use mermaid, pretty please?!

```mermaid
flowchart LR
    build-docs.yml --> build_type.sh
```

# 😃

**Comment by ymzayek** [comment]
I don't know it but sure happy to try it out!

**Pull request merged**
