### PR TITLE
Fix css

### PR DESCRIPTION
**Pull request by GaelVaroquaux**

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
I now have the proper fix: this fixes the background gradient on my computer, but keeps increased white space.

**Comment by GaelVaroquaux** [comment]
Link to the rendered version: https://3434-1235740-gh.circle-artifacts.com/0/home/circleci/project/doc/_build/html/index.html
Seems right

**Comment by bthirion** [comment]
LGTM.

**Comment by KamalakerDadi** [comment]
This PR something to do with Quick Search ?

**Comment by GaelVaroquaux** [comment]
No, this PR didn't do anything with Quick Search. I don't know why, but it reapears on CircleCI for all PRs.

**Comment by GaelVaroquaux** [comment]
OK, merging this guy, as it fixes our CSS problem. I'll backport this to the current website.

**Pull request merged**
