### PR TITLE
[ENH] update keys for brain development dataset

### PR DESCRIPTION
**Pull request by emdupre**
After discussion with @KamalakerDadi, adds keys for all 150 subjects from the brain development dataset.

### CODE REVIEW

**Comment by KamalakerDadi** [comment]
@kchawla-pi do you have the opportunity to check AppVeyor or restart the kernel ?

**Comment by kchawla-pi** [comment]
I'll do that now.

**Comment by KamalakerDadi** [comment]
Great!

**Comment by KamalakerDadi** [comment]
I am merging this one. CircleCI failure is a documentation build error. I will fix it in one of my PR.

Thank you @emdupre . Now we have full dataset for brain development.

**Pull request merged**
