### PR TITLE
[MRG] add symmetric_cmap option in view_img_on_surf

### PR DESCRIPTION
**Pull request by jeromedockes**
after all I think the symmetric_cmap option is useful for `view_img_on_surf`

### CODE REVIEW

**Comment by kchawla-pi** [comment]
What if one wants to plot only negative values?

**Comment by jeromedockes** [comment]
> What if one wants to plot only negative values?

it is handled as in other functions, for now they have to flip it I guess

**Comment by kchawla-pi** [comment]
Should we mention that in the doc string?

Kshitij

------------------------------------------------------------
"Those who never wander might be lost."

Working to be kind, aware, equanimous, and skilled at python.

**Comment by jeromedockes** [comment]
do you think it is a frequent use case?

**Comment by kchawla-pi** [comment]
> do you think it is a frequent use case?

I don't know that, but if it is a 1 line addition to the docstring, I would rather have it documented than not.

**Comment by jeromedockes** [comment]
> I don't know that, but if it is a 1 line addition to the docstring, I would rather have it documented than not.

sure, what would you write in the docstring? I can add it

**Comment by kchawla-pi** [comment]
> it is handled as in other functions, for now they have to flip it I guess

If you tell me exactly which args to pass, I can come up with the language.

**Comment by jeromedockes** [comment]
> If you tell me exactly which args to pass, I can come up with the language.

it's not arguments to pass to this function, it's just that symmetric_cmap=False is only accepted if the map is positive, as stated in the docstring. If they have a negative map, it is not supported but I guess we could add that. If the map is neither positive nor negative, symmetric_cmap should be forced to be True, as is currently the case

**Comment by kchawla-pi** [comment]
I suppose if no one has filed an issue asking for it, we should not feature bloat.

**Comment by jeromedockes** [comment]
so is there anything else?

**Comment by kchawla-pi** [comment]
Shouldn't we add the param at the end? WOn't the current placement break positional arguments?

**Comment by kchawla-pi** [comment]
The code changes LGTM. WOuld you tell me the path to the bult image so I can look at it as well in CircleCI artifacts?

**Comment by jeromedockes** [comment]
sorry I'm not sure I know, what do I need to do?

**Comment by kchawla-pi** [comment]
Never mind that.

We should at this feature in one of the examples.
We should also make an entry in What's New.

**Comment by jeromedockes** [comment]
> We should at this feature in one of the examples.

maybe we need an example dedicated to interactive plots, but that would be a separate PR. I'm not sure showing this in one of the existing examples is a good idea because it would add clutter to an example to explain a feature which is not essential and easy to understand from the docstring

**Comment by kchawla-pi** [comment]
OK. 

The current placement of `vmin` in function signatures breaks positional arguments in certain functions.
The ones I notice are:
 1. view_surf
 2. full_brain_info
 3. view_img_on_surf
 4. full_brain_info
 
In addition, the docstring for `vmin` says:
```
       If `symmetric_cmap` is `True`, `vmin` is always equal to `-vmax` and
        cannot be chosen.
        If `symmetric_cmap` is `False`, `vmin` defaults to the min of the
        image, or 0 when a threshold is used.
``` 
But I don't see the code logic for implementing this. What am I missing?

**Comment by jeromedockes** [comment]
> OK.
> 
> The current placement of `vmin` in function signatures breaks positional arguments in certain functions.
> The ones I notice are:
> 
>     1. view_surf
> 
>     2. full_brain_info
> 
>     3. view_img_on_surf
> 
>     4. full_brain_info

- in view_surf it doesn't, last two arguments (vmin and symmetric_cmap) are both being added in this PR
- full_brain_info isn't exposed to users from the `plotting` package

**Comment by jeromedockes** [comment]
> But I don't see the code logic for implementing this. What am I missing?

it's here:

https://github.com/nilearn/nilearn/blob/4a072a3e0cffa71e83f979de05a2735e8228b89a/nilearn/plotting/js_plotting_utils.py#L205

**Comment by kchawla-pi** [comment]
OK. Should we rename `full_brain_info` to `_full_brain_info`, maybe another PR?

Dunno how I missed the code logic for ` if symmetric_cmap and vmin is not None: `.
Since `vmin` is None or float, we can simply write
```python
 if symmetric_cmap and vmin: 
```
Also, instead of setting vmin to None, shoud we set it to -vmax? 
If not, should we change the warning to:
```python
  warnings.warn('vmin cannot be chosen when cmap is symmetric. Setting vmin to None.')
```

**Comment by kchawla-pi** [comment]
I'll let you decide this, I don't think I have anything to add.

**Comment by jeromedockes** [comment]
> Also, instead of setting vmin to None, shoud we set it to -vmax?

it gets changed to -vmax later, I guess we could just remove this line. but I don't think it matters very much. I would keep the warning as it is because vmin will be set to -vmax.

**Comment by jeromedockes** [comment]
> OK. Should we rename `full_brain_info` to `_full_brain_info`, maybe another PR?

yes that would make sense. in another PR. it's not urgent since this not exposed in plotting, which is what users import

**Comment by jeromedockes** [comment]
ping @kchawla-pi did you have more comments on this?

**Comment by kchawla-pi** [comment]
Nope. Take it home Jerome.

**Pull request merged**
