### PR TITLE
Split datasets in several files

### PR DESCRIPTION
**Pull request by AlexandreAbraham**
I'm doing this PR because @banilo can't do it. Because he has a mac that messes up git history. That's the ghost of Steve Jobs.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
> I'm doing this PR because @banilo can't do it. Because he has a mac that messes
> up git history. That's the ghost of Steve Jobs.

I am ordering valium.

I also think that it's time for you to grab beers.

**Comment by AlexandreAbraham** [comment]
> I am ordering valium.

Don't worry, this PR is not to be merged. We're fixing @banilo's history ;).

**Comment by GaelVaroquaux** [comment]
So, I gather that this PR is the one that should be merged instead of #647, right?

**Comment by GaelVaroquaux** [comment]
If so, can you rebase/merge this PR on master: I am afraid of a difficult merge. This will give us CircleCI, which will in effect test the downloading code.

**Comment by GaelVaroquaux** [comment]
> Don't worry, this PR is not to be merged. We're fixing @banilo's history ;).

OK, so please rebase the other (or merge it if it's too hard).

**Pull request closed without merging**
