### PR TITLE
[MAINT] Test with Python 3.9

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Add Python 3.9 to build matrix.
Thanks to @emdupre for catching this! :+1: 

Note: Currently failing as expected. We need to merge #2751 before.

### CODE REVIEW

**Comment by emdupre** [comment]
Thanks so much, @NicolasGensollen ! 

It looks like the only failing test is indeed in `fetch_atlas_aal`. I think that we'll want to change [these lines](https://github.com/nilearn/nilearn/blob/05ade8989ece76ca8a5cbcb222a64be26e94d461/nilearn/datasets/atlas.py#L799-L804).

**Comment by tsalo** [comment]
It might also be worth adding 3.8 and 3.9 under the classifiers in setup.py:

https://github.com/nilearn/nilearn/blob/05ade8989ece76ca8a5cbcb222a64be26e94d461/setup.py#L89-L91

Also, what about a badge for the Python versions in the README? 
[PyPI - Python Version](https://pypi.python.org/pypi/nilearn/)

**Comment by NicolasGensollen** [comment]
>I think that we'll want to change these lines.

@emdupre yes indeed, I opened #2751 as a fix.

**Comment by NicolasGensollen** [comment]
@tsalo adding the badge in #2729 seems indeed better. 
I'll add python 3.8 and 3.9 to setup.py in this one, thanks for the suggestion! :+1:

**Review by bthirion — APPROVED** [review]
Thx !

**Comment by NicolasGensollen** [comment]
Thanks! Merging...

**Pull request merged**
