### PR TITLE
Pinned Conda to version 4.6 due to incompatibilities & errors in 4.7.5

### PR DESCRIPTION
**Pull request by kchawla-pi**
- Reassessment in 1 month.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
>   • Pinned Conda to version 4.6 due to incompatibilities & errors in 4.7.5

it's really a problem that we need to pin versions. Is there a way
forward?

**Comment by kchawla-pi** [comment]
If we decide to do this, I intend to reassess this in a month.

I was also doin because of this #2079 . Pinning conda version was the only way for this. However, i was shocked to find that this one passed: https://github.com/nilearn/nilearn/pull/2078 . I am guessing Conda was fixed yesterday after hours.
If we wish we can merge this.

Nistats is not playing nice yet. I don't think it's because of Conda, there are weird HTTP redirect errors happening that could be due to localizer migration to OSF, but I don't really understand them yet.

 I would rather bump versions for both simultaneously, so until Nistats' troubles were diagnosed I was also trying out version pinning, because all this became rather complex and too many changes.

I figured I'll I'll give things time to settle & fix before bumping versions.

WDYT?

**Comment by kchawla-pi** [comment]
Nistats CircleCI is still failing. https://circleci.com/gh/kchawla-pi/nistats/447?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

If you wish we can cancel conda version pinning for Nilearn, since #2078 passed, and deal with Nistats separately. I am beginning to lean towards this.

**Comment by GaelVaroquaux** [comment]
> If you wish we can cancel conda version pinning for Nilearn, since #2078
> passed, and deal with Nistats separately. I am beginning to lean towards this.

Cool

**Pull request closed without merging**
