### PR TITLE
FIX: nibabel bumpup compatible changes

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Should fix some issues to more get_affine(img) to img.affine

Please reviews ?

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
LGTM. Thank you.

Let's wait for the tests to run, and merge after.

**Comment by GaelVaroquaux** [comment]
The failure is due to a network glitch

**Comment by GaelVaroquaux** [comment]
OK, merging without waiting for Circle: this will be very useful for the sprint.

**Comment by KamalakerDadi** [comment]
>The failure is due to a network glitch

I am trying to get some clue from google

**Comment by KamalakerDadi** [comment]
>The failure is due to a network glitch

FYI:Network is now up and running.

**Pull request merged**
