### PR TITLE
[MRG] Surface plot titles

### PR DESCRIPTION
**Pull request by jeromedockes**

### CODE REVIEW

**Comment by bthirion** [comment]
Can you provide an example of the behavior before/after ? To help us understand.
Thx !

**Comment by jeromedockes** [comment]
sure!
before:
Screenshot from 2019-07-15 09-40-50

after:

Screenshot from 2019-07-15 09-40-21

**Comment by bthirion** [comment]
Thx ! 
IIUC the new functionality is note xplicitly tested. Could it be ?
LGTM otherwise.

**Comment by jeromedockes** [comment]
@kchawla-pi any comments?

**Comment by kchawla-pi** [comment]
Looks good. Merging.

**Pull request merged**
