### PR TITLE
Nilearn.stats - 1: Incorporate Nistats into Nilearn with former's commit history intact

### PR DESCRIPTION
**Pull request by kchawla-pi**
As per discussion in issue #2298

### CODE REVIEW

**Comment by kchawla-pi** [comment]
@GaelVaroquaux I think @emdupre 's suggestion is great. We can merge this first, and since Nistats dir is not in the Nilearn package, Nilearn will keep functioning very well, independent of the PR. 

I can change the references and move the files in subsequent PRs.

If you green or red light this quickly, I can move along to the next steps, after merging or closing this one .

**Comment by GaelVaroquaux** [comment]
I had in mind to merge the decoder first, with the hope that it would
help decreasing the number of examples, to speed up the build process.

I worry about the length of circleCI once we merge this guy.

**Comment by kchawla-pi** [comment]
Even if we merge this immediately, it won't affect anything else, except create the `nistats` directory. The current CT suites will not find it, as can be seen in the test run results above. I think that is the best approach.

This won't interfere with the meta-estimator decoder PR, or indeed Nilearn, at all. I don't want to wait for the decoder PR since it keeps getting pushed back. The MetaEstimatorDecoder PR and 2 followup PRs for speed and one additional feature, need 2 weeks of focused work and rapid feedback. I am considering speaking with @bertrand about asking Binh, soon as he is back ,to let him dedicate the time in Feb. If he gets rapid feedback on them, we can merge all 3 quickly. Then examples can be reworked for speed and compactness. WDYT?

I  was concerned about CircleCI runtimes as well and have a plan and an issue opened to attend to that in #2286 . If you wish I can simultaneously work on this issue, and merge this one before anything else.

Finally, we don't have to merge this PR right away, i can create a new branch off this PR and keep working on this.

**Comment by bthirion** [comment]
The plan sounds good.

**Comment by GaelVaroquaux** [comment]
> I was concerned about CircleCI runtimes as well and have a plan and an issue opened to attend to that in #2286 

I think that we need to tackle runtimes first. I fear that if we merge in
nistats now, we will make every thing harder.

**Comment by kchawla-pi** [comment]
Okay. Here's what I propose:

I work on the PR to speed up CircleCI using differential doc building.
I can keep working on this using this PR's branch as the base. 
We complete the MetaEstimatorDecoder PRs and faster examples.

AFTER all this:

We can merge this PR.
Then the derived PR where I adapt and reorganize the code but not the examples
Finally the derived PR with the examples.

WDYT?

**Comment by GaelVaroquaux** [comment]
In principle I am OK with this plan. Thank you!

Caveat emptor: The present PR might receive some comments.

But overall, this is the right direction.

**Comment by kchawla-pi** [comment]
> Caveat emptor: The present PR might receive some comments.

I don't understand. Isn't that business as usual? What's caveat emptor here?
Also, comments on this PR, ASAP, would be good. I don't want to start 2 PRs based on this, then have this PR torpedoed.

**Comment by kchawla-pi** [comment]
@GaelVaroquaux I believe we will need to regular merge this PR (not squash merge it like we usually do) if we want to maintain the commit history and user contribution.

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux I believe we will need to regular merge this PR (not squash
> merge it like we usually do) if we want to maintain the commit history and user
> contribution.

Fine with me. I like pragmatic solutions!

**Comment by kchawla-pi** [comment]
@bthirion Once I merge this specific PR, I can no longer pull from Nistats repo. Any changes made in Nistats will then have to be manually incorporated into Nilearn. This is an FYI. My time to leave is near so I do wanna merge these before I go.

@GaelVaroquaux If there are no objections, I'll merge this specific PR and the 2nd one today

**Comment by bthirion** [comment]
> @bthirion Once I merge this specific PR, I can no longer pull from Nistats repo. Any changes made in Nistats will then have to be manually incorporated into Nilearn. This is an FYI. My time to leave is near so I do wanna merge these before I go.

Fine with me. This has to happen one day ;-)

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux If there are no objections, I'll merge this specific PR and the 2nd one today

Go ahead

**Comment by kchawla-pi** [comment]
@jeromedockes Hey, I want to confirm something. THe Flake8 test in Travis compares the diff with the master to ascertain formatting errors correct? If I merge this R and the 2nd one as it is without changing it, it won't affect future PR's test results right?

AFAIK I had fixed them for the code and left them as they were for the examples, but Travis' Flake8 test shows a bunch of failures., which I don't think are worth the effort.

**Comment by jeromedockes** [comment]
> @jeromedockes Hey, I want to confirm something. THe Flake8 test in Travis compares the diff with the master to ascertain formatting errors correct? If I merge this R and the 2nd one as it is without changing it, it won't affect future PR's test results right?
>
> AFAIK I had fixed them for the code and left them as they were for the examples, but Travis' Flake8 test shows a bunch of failures., which I don't think are worth the effort.

That is correct. If the PR is ready besides flake8 errors in examples go
ahead and merge.

(Still if you see any errors such as unused variables or imports or
comparisons to None or False with == those should be easy and may be
worth fixing)

**Comment by emdupre** [comment]
It looks like this was squashed and merged, so we lost the commit history. Not sure if this is something worth addressing at this point, but wanted to point it out before you get deep in resolving the merge conflicts in #2307 , @kchawla-pi  !

**Comment by kchawla-pi** [comment]
No, i merged it using a merge commit, not squash merge.

**Comment by kchawla-pi** [comment]
Did i enable regular merge and then squash merge it anyway????
Oh please no! I don't know if I did.

**Comment by kchawla-pi** [comment]
Okay I must undo this and the 2nd merge...
Any one has suggestions?

**Comment by kchawla-pi** [comment]
If I have indeed made a mistake and someone can fix it. help me out.
Otherwise I'll try and fix this tomorrow. Spent for the day. Don't wanna make another mistake.

**Comment by kchawla-pi** [comment]
I am thinking of doing the following:

1. Revert my local master to the commit just before this one.
2. Then merge my local branch for this PR into that rolled-back master, using a merge commit.
3. Then squash merge the 2nd PR using my local branch into that.
4. Then force push the master branch to nilearn master.

If there's a deficiency in this plan, please point it out. I'll attempt this tomorrow.
@GaelVaroquaux @emdupre @jeromedockes

**Comment by kchawla-pi** [comment]
Hey @emdupre I am fairly certain I did not do a squash merge of this branch. I remember re-enabling regular merges and selecting and clicking Merge PR instead of Squash merge.

When I do checkout the master branch at the point where this PR was merged and do
```bash
git log | grep "thompson"
git log | grep "chrplr"
```
I get results for Jessica Thompson and Christophe Pallier which AFAIK contributed to Nistats but never Nilearn.

What makes you suspect that the commit history has not been carried forward? I can look there and see if all is well or not.

**Comment by kchawla-pi** [comment]
> I get results for Jessica Thompson and Christophe Pallier which AFAIK contributed to Nistats but never Nilearn.

okay I figured why I got results for them. But I am certain I didn't make a mistake. More investigating.

**Comment by kchawla-pi** [comment]
Okay I fixed it locally. You were right Elizabeth. Will push it once it passes on my fork.

**Comment by kchawla-pi** [comment]
Thanks!!!

**Comment by kchawla-pi** [comment]
I think that fixed it. Thanks @emdupre

**Pull request merged**
