### PR TITLE
[FIX] Fix sphinx errors in contributing docs

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Fix broken doc build on circleCI due to recent merge of #2755

### CODE REVIEW

**Comment by NicolasGensollen** [comment]
Artifacts look good. Merging fast to fix master...

**Comment by thomasbazeille** [comment]
sorry about those mistakes Nicolas

**Comment by bthirion** [comment]
Thx to all of you !

**Comment by NicolasGensollen** [comment]
>sorry about those mistakes Nicolas

No prob, I should have asked for a full build at the end to be sure it was running fine ;)

**Pull request merged**
