### PR TITLE
[FIX] Return `h0_fmax` for all regressors from `permuted_ols`

### LINKED ISSUE #3180: permuted_ols only returns h0_fmax for first regressor
When there is more than one regressor in `tested_vars`, `permuted_ols` returns only the null distribution of maximum t-statistics for the first regressor.

Here is the relevant code:

https://github.com/nilearn/nilearn/blob/e7804ebe858349781674c0d2b5c78e27afb52fa1/nilearn/mass_univariate/permuted_least_squares.py#L512

Nilearn version: `main` as of e7804ebe858349781674c0d2b5c78e27afb52fa1.

### Expected behavior

When `n_regressors` is >1, I would expect `h0_fmax` to have that number of rows.

### Actual behavior

`h0_fmax` is a 1D array, with one element per 

### Steps and code to reproduce bug

Here is some code, adapted from one of the permuted_ols tests, that should reproduce the bug.

```python
from sklearn.utils import check_random_state
from nilearn.mass_univariate import permuted_ols

random_state = 0
rng = check_random_state(random_state)

# design parameters
n_samples = 50
n_descriptors = 10
n_regressors = 2
n_covars = 2
n_perm = 10

# create design
target_vars = rng.randn(n_samples, n_descriptors)
tested_vars = rng.randn(n_samples, n_regressors)
confounding_vars = rng.randn(n_samples, n_covars)

neg_log10_pvals, own_scores, h0_fmax = permuted_ols(
    tested_vars,
    target_vars,
    confounding_vars,
    model_intercept=False,
    n_perm=n_perm,
    random_state=random_state,
)
assert own_scores.shape == (n_regressors, n_descriptors)
assert neg_log10_pvals.shape == (n_regressors, n_descriptors)
assert h0_fmax.shape == (n_regressors, n_perm)
# AssertionError, assert (10,) == (2, 10)
```

### PR DESCRIPTION
**Pull request by tsalo**
Closes #3180.

Changes proposed in this pull request:

- Return `h0_fmax` (the null distribution of maximum t-statistics used for voxel-level FWE correction) for all regressors, instead of just the first regressor.
- Update tests to check for the right shape.
- Add a versionchanged directive to the `permuted_ols` docstring reflecting this change.
- Add a whatsnew entry for the change.

NOTE: It doesn't look like `non_parametric_inference` retains `h0_fmax` from `permuted_ols`, and none of the examples that use `permuted_ols` seem to retain `h0_fmax` either, so I think the scope of these changes is limited to the function and its tests.

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
LGTM, thx !

**Review by NicolasGensollen — APPROVED** [review]
The changes LGTM! Thanks @tsalo ! 👍 
Without the CircleCI issue, I would have asked for a full doc build to check that we are not breaking an example. Did you check locally that examples relying on `permuted_ols` were running fine?

**Comment by tsalo** [comment]
@NicolasGensollen it looks like the only examples that use `permuted_ols` are:

- examples/02_decoding/plot_oasis_vbm.py
- examples/07_advanced/plot_haxby_mass_univariate.py
- examples/07_advanced/plot_localizer_mass_univariate_methods.py

None of the three actually uses `h0_fmax`. They all just assign that output to `_`. `nilearn.glm.second_level.non_parametric_inference` does the same thing, and I believe that's the only _function_ that uses `permuted_ols`, so I think the impact of the change is minimal.

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Review by emdupre — APPROVED** [review]

**Comment by NicolasGensollen** [comment]
Thanks @tsalo ! 👍 
Merging then, since we have 3 approvals.

**Pull request merged**
