### PR TITLE
[MRG+1] Suppress UserWarning on calls to affine_transform

### PR DESCRIPTION
**Pull request by cancan101**
Closes https://github.com/nilearn/nilearn/issues/1363

### CODE REVIEW

**Comment by cancan101** [comment]
not sure why this failed circle-ci

**Comment by KamalakerDadi** [comment]
I am not sure whether #1363 is to suppress warnings. But, we can wait for others opinion on this PR.

I think CircleCI failure is a glitch.

**Comment by GaelVaroquaux** [comment]
Overall, this is great, and this is very useful.

One small comment: the filter, as it's implemented, will filter out a lot, and might filter relevant warnings.
This warning only appears in scipy 0.18 (and maybe 1.0, can someone check?). We should turn on the filter only for the corresponding scipy version by calling warnings.simplefilter in an if clause testing the scipy version (the test needs to be done as it's done a few lines above).

**Comment by GaelVaroquaux** [comment]
Overall, this is great, and this is very useful.

One small comment: the filter, as it's implemented, will filter out a lot, and might filter relevant warnings.
This warning only appears in scipy 0.18 (and maybe 1.0, can someone check?). We should turn on the filter only for the corresponding scipy version by calling warnings.simplefilter in an if clause testing the scipy version (the test needs to be done as it's done a few lines above).

**Comment by GaelVaroquaux** [comment]
Overall, this is great, and this is very useful.

One small comment: the filter, as it's implemented, will filter out a lot, and might filter relevant warnings.
This warning only appears in scipy 0.18 (and maybe 1.0, can someone check?). We should turn on the filter only for the corresponding scipy version by calling warnings.simplefilter in an if clause testing the scipy version (the test needs to be done as it's done a few lines above).

**Comment by GaelVaroquaux** [comment]
Overall, this is great, and this is very useful.

One small comment: the filter, as it's implemented, will filter out a lot, and might filter relevant warnings.
This warning only appears in scipy 0.18 (and maybe 1.0, can someone check?). We should turn on the filter only for the corresponding scipy version by calling warnings.simplefilter in an if clause testing the scipy version (the test needs to be done as it's done a few lines above).

**Comment by GaelVaroquaux** [comment]
Overall, this is great, and this is very useful.

One small comment: the filter, as it's implemented, will filter out a lot, and might filter relevant warnings.
This warning only appears in scipy 0.18 (and maybe 1.0, can someone check?). We should turn on the filter only for the corresponding scipy version by calling warnings.simplefilter in an if clause testing the scipy version (the test needs to be done as it's done a few lines above).

**Comment by KamalakerDadi** [comment]
Suppressing warnings and we never know if there is fuzzy stuff going on.

**Comment by KamalakerDadi** [comment]
>the filter, as it's implemented, will filter out a lot, and might filter relevant warnings.
This warning only appears in scipy 0.18 (and maybe 1.0, can someone check?)

No it didn't disappeared. It can be easily checked from one our travis environment 
https://travis-ci.org/nilearn/nilearn/jobs/299005132
and search for affine_transform

**Comment by GaelVaroquaux** [comment]
Thanks Kamalakar.

**Comment by cancan101** [comment]
So what do you want to do with this PR?

**Comment by GaelVaroquaux** [comment]
> So what do you want to do with this PR?

I would say: add the check on scipy versions, and it's good to go.

**Comment by GaelVaroquaux** [comment]
LGTM. +1 for merge. Thank you

**Comment by cancan101** [comment]
not sure what is failing here.

**Comment by KamalakerDadi** [comment]
>not sure what is failing here.

Failures are not related to your PR. I am preparing a FIX for that.

**Comment by KamalakerDadi** [comment]
>   not sure what is failing here.

>Failures are not related to your PR. I am preparing a FIX for that.

Failures are now fixed in master. Could please rebase ?

**Comment by cancan101** [comment]
done and squashed

**Comment by KamalakerDadi** [comment]
>done and squashed

Thanks

**Comment by GaelVaroquaux** [comment]
LGTM. Merging. Thank you very much.

**Pull request merged**
