### PR TITLE
[MRG+1] replace corrcoef by ConnectivityMeasure in hint

### PR DESCRIPTION
**Pull request by salma1601**
Fixes: #1221

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
LGTM. :+1: for merge.

**Comment by AlexandreAbraham** [comment]
I am merging it but, if possible, try not to create one issue for each 2 line patch ;). You can directly submit the PR, it is even better than an issue because people can directly see the impact.

**Comment by GaelVaroquaux** [comment]
When I mentionned creating issues, it was for bigger changes, like
merging several examples.

**Comment by salma1601** [comment]
>if possible, try not to create one issue for each 2 line patch ;)

OK :D

**Pull request merged**
