### PR TITLE
[MAINT] test install and run windows tests with github actions

### LINKED ISSUE #3779: switch more CI away from azure and into GH actions
It looks like a lot of our CI in azure could be done in github.

A GH replacement would need:
- a workflow to test install on all OSes
- run tests on windows

Is there a reason why we have to rely on azure for those? Or is it just a case of: we never made the switch.

### PR DESCRIPTION
**Pull request by Remi-Gau**
Closes #3779 

Changes proposed in this pull request:

- test install in gh actions
- run tests for windows in gh actions

### CODE REVIEW

**Comment by Remi-Gau** [comment]
OK the errors on windows seem to happen in a non deterministic manner but seem to always be due to 

- There appear to be 2 leaked folder objects to clean up at shutdown


<details>

<pre>

Windows fatal exception: access violation

Thread 0x00000cc8 (most recent call first):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\kaleido\scopes\base.py", line 149 in _collect_standard_error
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\runner.py", line 262 in <lambda>
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\runner.py", line 341 in from_call
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\runner.py", line 261 in call_runtest_hook
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\runner.py", line 222 in call_and_report
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\runner.py", line 133 in runtestprotocol
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\runner.py", line 114 in pytest_runtest_protocol
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\main.py", line 349 in pytest_runtestloop
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\main.py", line 324 in _main
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\main.py", line 270 in wrap_session
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\main.py", line 317 in pytest_cmdline_main
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_callers.py", line 80 in _multicall
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_manager.py", line 112 in _hookexec
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_hooks.py", line 433 in __call__
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\config\__init__.py", line 166 in main
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\config\__init__.py", line 189 in console_main
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts\pytest.exe\__main__.py", line 7 in <module>
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\runpy.py", line 87 in _run_code
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\runpy.py", line 197 in _run_module_as_main
C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py:310: UserWarning: resource_tracker: There appear to be 2 leaked folder objects to clean up at shutdown
  warnings.warn(
C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py:326: UserWarning: resource_tracker: C:\Users\VSSADM~1\AppData\Local\Temp\joblib_memmapping_folder_2448_22a07b0389c94d50b9b0dc10d9b0e882_3c7869e8849444b3aa0abd1a61e63688: FileNotFoundError(2, 'The system cannot find the path specified')
  warnings.warn(f'resource_tracker: {name}: {e!r}')
C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py:326: UserWarning: resource_tracker: C:\Users\VSSADM~1\AppData\Local\Temp\joblib_memmapping_folder_2448_22a07b0389c94d50b9b0dc10d9b0e882_b56149fc0efd42378409b1534b136f5c: FileNotFoundError(2, 'The system cannot find the path specified')
  warnings.warn(f'resource_tracker: {name}: {e!r}')

</pre>

</details>

**Comment by Remi-Gau** [comment]
Seems that the codecov reports are not uploaded when running tests with GH on windows

https://github.com/nilearn/nilearn/actions/runs/5386895758/jobs/9777500494?pr=3780#step:9:37

I don't think this should block this PR, especially that we do not use flags on the code-cov action: we possibly may want to do something like this to have coverage reports for different OS / python


```
- uses: codecov/codecov-action@v3
  with: 
    flags: ${{ matrix.os }}_${{ matrix.python-version }}
```

**Comment by ymzayek** [comment]
> Seems that the codecov reports are not uploaded when running tests with GH on windows

We can try setting a token (even though it's supposed to be not required for public repos)

**Comment by Remi-Gau** [comment]
> re running failed jobs only

OK it seems that re running failed jobs can make them pass, so there is something flaky but I am not yet sure it comes from us.

**Comment by Remi-Gau** [comment]
OK things seem to be green but I am not holding my breath for it to always pass, but at least we are only on GH now.

**Review by ymzayek — APPROVED** [review]
LGTM thx! Before merging can you update `.github/workflows/README.md` and add the new installing workflow?

**Comment by Remi-Gau** [comment]
> LGTM thx! Before merging can you update `.github/workflows/README.md` and add the new installing workflow?

good catch: I had totally forgotten about the existence of this README

**Pull request merged**
