### PR TITLE
[MAINT] Expose `standardize` parameter in function signatures to allow handling of deprecation

### LINKED ISSUE #3825: Silence standardize deprecation warnings not possible with functions that set parameter internally
One issue with silencing all instances of this warning in our examples gallery is that the ones that are still throwing the warning come from the functions `plot_carpet` and `ConnectivityMeasure.fit_transform` which call `signal.clean` with the parameter `standardize` equal to `True` or `"zscore"` internally so these are not exposed to the user. Hence the warning doesn't make sense for these cases as the user has no control and cannot call the new behavior. Probably best to open a new issue to see how to resolve this. Might need to add a deprecated parameter to allow the user to access the new behavior with these functions.

The relevant lines are:
https://github.com/nilearn/nilearn/blob/bce754beea677d4d4a51191e21c64d09002f1429/nilearn/connectome/connectivity_matrices.py#L497
and 
https://github.com/nilearn/nilearn/blob/bce754beea677d4d4a51191e21c64d09002f1429/nilearn/plotting/img_plotting.py#L1430

_Originally posted by @ymzayek in https://github.com/nilearn/nilearn/issues/3821#issuecomment-1625330400_

### PR DESCRIPTION
**Pull request by ymzayek**
- Closes #3825

Changes proposed in this pull request:

- Add standardize parameter to `plot_carpet` and `ConnectivityMeasure` so users can deal with "zscore" deprecation
- Update examples
- Update/add tests that warnings are not raised with new input

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
LGTM so far, but we need to check that the behavior of the examples is still fine.

**Comment by ymzayek** [comment]
Showing main branch build versus changes in this PR for affected examples:

plot_carpet: [main version](https://nilearn.github.io/dev/auto_examples/01_plotting/plot_carpet.html#sphx-glr-auto-examples-01-plotting-plot-carpet-py) vs [this pr](https://output.circle-artifacts.com/output/job/0fa45598-90e2-4909-a593-67da10dab177/artifacts/0/dev/auto_examples/01_plotting/plot_carpet.html#sphx-glr-auto-examples-01-plotting-plot-carpet-py)

plot_atlas_comparison: [main version](https://nilearn.github.io/dev/auto_examples/03_connectivity/plot_atlas_comparison.html) vs [this pr](https://output.circle-artifacts.com/output/job/0fa45598-90e2-4909-a593-67da10dab177/artifacts/0/dev/auto_examples/03_connectivity/plot_atlas_comparison.html)

plot_extract_regions_dictlearning_maps: [main version](https://nilearn.github.io/dev/auto_examples/03_connectivity/plot_extract_regions_dictlearning_maps.html) vs [this pr](https://output.circle-artifacts.com/output/job/0fa45598-90e2-4909-a593-67da10dab177/artifacts/0/dev/auto_examples/03_connectivity/plot_extract_regions_dictlearning_maps.html)

plot_group_level_connectivity: [main version](https://nilearn.github.io/dev/auto_examples/03_connectivity/plot_group_level_connectivity.html) vs [this pr](https://output.circle-artifacts.com/output/job/0fa45598-90e2-4909-a593-67da10dab177/artifacts/0/dev/auto_examples/03_connectivity/plot_group_level_connectivity.html)

plot_probabilistic_atlas_extraction: [main version](https://nilearn.github.io/dev/auto_examples/03_connectivity/plot_probabilistic_atlas_extraction.html) vs [this pr](https://output.circle-artifacts.com/output/job/0fa45598-90e2-4909-a593-67da10dab177/artifacts/0/dev/auto_examples/03_connectivity/plot_probabilistic_atlas_extraction.html)

plot_signal_extraction: [main version](https://nilearn.github.io/dev/auto_examples/03_connectivity/plot_signal_extraction.html) vs [this pr](https://output.circle-artifacts.com/output/job/0fa45598-90e2-4909-a593-67da10dab177/artifacts/0/dev/auto_examples/03_connectivity/plot_signal_extraction.html)

plot_sphere_based_connectome: [main version](https://nilearn.github.io/dev/auto_examples/03_connectivity/plot_sphere_based_connectome.html) vs [this pr](https://output.circle-artifacts.com/output/job/0fa45598-90e2-4909-a593-67da10dab177/artifacts/0/dev/auto_examples/03_connectivity/plot_sphere_based_connectome.html)

plot_age_group_prediction_cross_val: [main version](https://nilearn.github.io/dev/auto_examples/07_advanced/plot_age_group_prediction_cross_val.html) vs [this pr](https://output.circle-artifacts.com/output/job/0fa45598-90e2-4909-a593-67da10dab177/artifacts/0/dev/auto_examples/07_advanced/plot_age_group_prediction_cross_val.html)

**Comment by ymzayek** [comment]
Is there a reason that standardize_confounds was not passed to RegionExtractor?

**Comment by bthirion** [comment]
> 

Thx ! LGTM

**Comment by bthirion** [comment]
> 

No, I think it was simply forgotten.

**Review by bthirion — APPROVED** [review]

**Pull request merged**
