### PR TITLE
ENH add dtype option for NiftiMasker

### PR DESCRIPTION
**Pull request by SylvainLan**
This PR aims at solving issue #1669 

I only used `_utils.check_niimg` which already has this `dtype` feature and is used in both `NiftiMasker` and `MultiNiftiMasker`

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
You're on fire!!! That's awesome!!

I don't promise that we merge this PR before the release, but let's see.

**Comment by GaelVaroquaux** [comment]
Any chance that I can convince you to add this for the other maskers in input_data? Let's not do it in things like CanICA for now, as we'll need , but the other maskers would need it for consistency.

And maybe a note (directive ".. topic:: ") in the documentation, for instance on http://nilearn.github.io/manipulating_images/masker_objects.html#common-data-preparation-steps-smoothing-filtering-resampling
That note should say that forcing float32 can help save memory and is often a good-enough numerical precision.

Also, this needs an entry in whats_new.

**Comment by GaelVaroquaux** [comment]
Could you rebase or merge on master, to get the tests to pass?

**Comment by SylvainLan** [comment]
> We still need the added paragraph to the discussion, as mentioned in my above review, as well as as an entry in the whats_new.rst file. Something important is that the entry in the whats_new should state that there is a change in default behavior: now nifti images will more often get cast to float32

I'm doing it ! But the default dtype option right now is `None`, which won't change the dtype, so either we can make default to `auto` or leave it to `None`. What do you think ?

**Comment by SylvainLan** [comment]
This PR is open for reviews !

**Comment by GaelVaroquaux** [comment]
LGTM. +1 for merge when CI is green.

**Comment by GaelVaroquaux** [comment]
Merging!

**Pull request merged**
