### PR TITLE
Issue templates

### PR DESCRIPTION
**Pull request by kchawla-pi**
Carried over from PR #1905
Added issue templates for bug report & feature requests, indicating question should be posted on Neurostars

### CODE REVIEW

**Comment by emdupre** [comment]
Looks good ! I might iterate on the wording a bit to make it welcoming (personally), but I think the functionality is clearer, now :+1: Thanks !

**Comment by kchawla-pi** [comment]
Not sure why you are saying thanks, you are the one helping me! :-)
Thank you so much for all this.

> make it welcoming 

Hehe

**Comment by bthirion** [comment]
Sorry, I don't see where these templates can be found (currently looking at CirceCI artifacts). Can you point to these ? Thx.

**Comment by kchawla-pi** [comment]
They are in the /.github/ directory. You can't really see the effects until they are merged, since they are only visible when filing a new issue. 
You won't see them in CircleCI artifacts since I don't upload them as such.

**Comment by bthirion** [comment]
OK, LGTM.

**Comment by emdupre** [comment]
Just to say -- I had missed the wording update but I think they look great ! Thanks again :tada:

**Comment by kchawla-pi** [comment]
Thank you for guiding me so well!

**Pull request merged**
