### PR TITLE
[MAINT] nilearn.interface: make private functions used outside of their module public

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Relates to #3319 

Changes proposed in this pull request:

- remove `nilearn.interface.bids._utils` and move functions closer to where they are used or into a new `nilearn.interface.bids.utils`
- make private functions public if used in `nilearn.interface.fmriprep` used outside of their module

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Several functions interfaces/fmriprep seem to be unused in the code base.

@htwangtw is this to be expected?
 

- '_load_motion' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.
- '_load_high_pass' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.
- '_load_wm_csf' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.
- '_load_global_signal' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.
- '_load_compcor' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.
- '_load_ica_aroma' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.
- '_load_scrub' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.
- '_load_non_steady_state' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.

**Comment by htwangtw** [comment]
> Several functions interfaces/fmriprep seem to be unused in the code base.
> 
> @htwangtw is this to be expected?
>  
> 
> - '_load_motion' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.
> - '_load_high_pass' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.
> - '_load_wm_csf' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.
> - '_load_global_signal' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.
> - '_load_compcor' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.
> - '_load_ica_aroma' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.
> - '_load_scrub' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.
> - '_load_non_steady_state' mentioned only 1 time in nilearn/interfaces/fmriprep/load_confounds_components.py.

Yes - here's how these `_load_*` functions are used in the code:
https://github.com/nilearn/nilearn/blob/main/nilearn%2Finterfaces%2Ffmriprep%2Fload_confounds.py#L485

**Comment by Remi-Gau** [comment]
Ah yes. Thanks.
Will add a comment at the top of that module in case future me forgets about this.

**Review by bthirion — COMMENTED** [review]
LGTM, but there are some codecov complaints...

**Comment by Remi-Gau** [comment]
> LGTM, but there are some codecov complaints...

looks like some of those are "false positive".

will double check but I think that in any case there are couple of lines in the incriminated files that were not hit by the tests so I will to cover them with some new tests

**Comment by Remi-Gau** [comment]
OK should improve the coverage of those lines: https://app.codecov.io/gh/nilearn/nilearn/blob/master/nilearn%2Finterfaces%2Fbids%2Fglm.py#L98

Had to do some refactoring of the test suite so probably increase the number of line changes

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Review by htwangtw — APPROVED** [review]
LGTM!

**Pull request merged**
