### PR TITLE
Automatic commenting on new PR

### LINKED ISSUE #2962: Automatically commenting on opened PR
Issue off-loaded from previous documentation PR : #2755.

### Topic

When a PR is opened, set-up an automatic comment to ask the contributor to make sure his PR and give informations that are important to structure the review process e.g. :

> Thank your for sending code in. Please make sure it is compliant with our contributing guidelines. Don't hesitate to ask questions early if needed.

> Until this PR is ready for review, you can include the [WIP] tag in its title, or leave it as a github draft. When you remove those, we will review it as quick as possible.

### Affected pages

Benefits :

- Would give a strong reminder to new and non-frequent contributors about our guidelines and where to find them
- Would likely help smoothen the review process

Cost : 

- Would require to set up a GH action, probably [auto-comment](https://github.com/marketplace/actions/auto-comment).

### PR DESCRIPTION
**Pull request by thomasbazeille**
Closes #2962 .

Changes proposed in this pull request:

- First draft of auto-commenting to support discussion on what its content should be.

Main hurdles : If we want to include a checklist as @tsalo proposed, it is hard to know which elements should absolutely be included.

### CODE REVIEW

**Comment by NicolasGensollen** [comment]
Thanks @thomasbazeille ! :+1: 
There seems to be a small issue with the rendering of the list, but looks good otherwise.

**Comment by thomasbazeille** [comment]
I think I solved the rendering, to test it I might close this PR at some point and reopen a new one.

**Review by bthirion — APPROVED** [review]
The PR LGTM (yet dunno how to check the rendering)

**Review by NicolasGensollen — APPROVED** [review]
I tried it elsewhere and it seems to work and render as expected! :tada: 
Thanks @thomasbazeille !

**Comment by thomasbazeille** [comment]
I'm not sure what text format to use in the .yml. I added a contribution link in .md format.

Other than that @tsalo do you have any comment on the content ?

**Review by tsalo — APPROVED** [review]
The comment and checklist look great to me.

**Comment by NicolasGensollen** [comment]
Merging since we have 3 approvals. :tada: 
Thanks!

**Pull request merged**
