### PR TITLE
fix incorrect docstring in neurovault localizer fetchers

### PR DESCRIPTION
**Pull request by jeromedockes**

### CODE REVIEW

**Comment by bthirion** [comment]
LGTM.

**Comment by kchawla-pi** [comment]
How is this incorrect? The Neurovault ids are not for left-right, auditory etc?

**Comment by jeromedockes** [comment]
> How is this incorrect? The Neurovault ids are not for left-right, auditory etc?

it doesnt use the fetch_localizer

**Comment by kchawla-pi** [comment]
whats_new entry?

**Comment by jeromedockes** [comment]
> whats_new entry?

doesn't it pollute the whats_new to include tiny changes like this? this pr doesn't change anything for users

**Pull request merged**
