### PR TITLE
Added compatibility packages related to version six

### LINKED ISSUE #506: Add test for compatibility of old version of six
For the moment, we are compatible with the latest version of six. Recently, somebody pointed out that we did not support six 1.5.2. We should investigate, decide which version we should be compatible with and then add this to Travis.

### PR DESCRIPTION
**Pull request by KamalakerDadi**
Fix #506.

### CODE REVIEW

**Comment by lesteve** [comment]
Eventually if we agree on a six version it will need to be added to both README.rst and nilearn/version.py.

**Comment by AlexandreAbraham** [comment]
After asking the culprits, I learned that version 1.4.1 was chosen because it is the first one with urllib.

**Comment by AlexandreAbraham** [comment]
Great, thanks!

**Comment by lesteve** [comment]
> After asking the culprits, I learned that version 1.4.1 was chosen because it is the first one with urllib.

Yeah basically this was the oldest six version that got the test passing on my machine without having to change code.

For completeness:

```
~/dev/scikit-learn $ piprot <(echo six==1.4.1)
six (1.4.1) is 487 days out of date. Latest is 1.9.0
```

**Comment by lesteve** [comment]
Hmmm actually this comment was forgotten in the process:

> Eventually if we agree on a six version it will need to be added to both README.rst and nilearn/version.py.

@KamalakerDadi can you look at it.

**Pull request merged**
