### PR TITLE
New version of section 6

### PR DESCRIPTION
**Pull request by SylvainLan**
I purposely mainly put direct code in the .rst file over inclusions from the plot_decoding_tutorial.py to be run directly by copy and paste. 

I also reordered the parts, and corrected the condition paragraph with didn't make sense to the condition in the code.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
That's not the right approach: code in the RST file is not well tested
and hard to maintain. The approach that we are taking is to enrich the
example files with blocks of rich comments and trying to remove as much
as possible from the rst files.

**Comment by SylvainLan** [comment]
Ok, so the code in the rst file is not supposed to be run? And what is your opinion on the order of this part?

**Comment by GaelVaroquaux** [comment]
> Ok, so the code in the rst file is not supposed to be run?

I think that I'd like to move as much as possible out to a long tutorial
example, and reference that example. I think that the narrative parts of
the documentation should be as much as possible about high-level
concepts, and the code should be as much as possible in examples
referenced from the docs.

> And what is your opinion on the order of this part?

I am not sure that I love it :$. We can discuss that at a coffee break.

**Comment by SylvainLan** [comment]
consequently close this PR

**Pull request closed without merging**
