### PR TITLE
[MAINT] Removed all mentions of "License" from headers

### LINKED ISSUE #3771: Remove mention of license in "header" of *.py file
The license of nilearn is mentioned in the "header" of many files.

These should be removed.

_Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/issues/3728#issuecomment-1597444375_
            
### List of files to modify

```bash
$ find nilearn -name '*.py' -exec grep -H "License" {} \;

nilearn/datasets/data/convert_templates.py:# License: simplified BSD
nilearn/datasets/struct.py:# License: simplified BSD
nilearn/datasets/neurovault.py:# License: simplified BSD
nilearn/datasets/tests/test_atlas.py:# License: simplified BSD
nilearn/datasets/tests/test_func.py:# License: simplified BSD
nilearn/datasets/tests/test_struct.py:# License: simplified BSD
nilearn/datasets/tests/test_utils.py:# License: simplified BSD
nilearn/datasets/tests/test_neurovault.py:# License: simplified BSD
nilearn/masking.py:# License: simplified BSD
nilearn/tests/test_signal.py:# License: simplified BSD
nilearn/tests/test_masking.py:# License: simplified BSD
nilearn/image/resampling.py:# License: simplified BSD
nilearn/image/image.py:# License: simplified BSD
nilearn/decoding/objective_functions.py:# License: simplified BSD
nilearn/decoding/space_net.py:# License: simplified BSD
nilearn/decoding/space_net_solvers.py:# License: simplified BSD
nilearn/decoding/fista.py:# License: simplified BSD
nilearn/decoding/decoder.py:# License: simplified BSD
nilearn/decoding/tests/test_decoder.py:# License: simplified BSD
nilearn/decoding/tests/test_searchlight.py:# License: simplified BSD
nilearn/decoding/searchlight.py:# License: simplified BSD
nilearn/decoding/proximal_operators.py:# License: simplified BSD
nilearn/maskers/multi_nifti_masker.py:# License: simplified BSD
nilearn/maskers/tests/test_multi_nifti_masker.py:# License: simplified BSD
nilearn/maskers/tests/test_nifti_masker.py:# License: simplified BSD
nilearn/maskers/nifti_masker.py:# License: simplified BSD
nilearn/maskers/base_masker.py:# License: simplified BSD
nilearn/_utils/extmath.py:# License: BSD
nilearn/_utils/ndimage.py:# License: simplified BSD
nilearn/_utils/numpy_conversions.py:# License: simplified BSD
nilearn/_utils/niimg_conversions.py:# License: simplified BSD
nilearn/_utils/tests/test_niimg_conversions.py:# License: simplified BSD
nilearn/_utils/logger.py:# License: simplified BSD
nilearn/_utils/testing.py:# License: simplified BSD
nilearn/_utils/niimg.py:# License: simplified BSD
nilearn/_utils/cache_mixin.py:# License: simplified BSD
nilearn/decomposition/dict_learning.py:# License: BSD 3 clause
nilearn/decomposition/canica.py:# License: BSD 3 clause
nilearn/plotting/edge_detect.py:# License: BSD
nilearn/plotting/img_plotting.py:# License: BSD
nilearn/plotting/find_cuts.py:# License: BSD
nilearn/signal.py:# License: simplified BSD
nilearn/regions/signal_extraction.py:# License: simplified BSD
nilearn/regions/tests/test_signal_extraction.py:# License: simplified BSD
nilearn/regions/rena_clustering.py:# License: simplified BSD
nilearn/connectome/group_sparse_cov.py:# License: simplified BSD
```

### PR DESCRIPTION
**Pull request by czarinasy**
Closes #3771.

Changes proposed in this pull request:

- Removed the "License" comment from all listed headers

### CODE REVIEW

**Review by ymzayek — COMMENTED** [review]
LGTM thanks @czarinasy ! As a first time contributor you also need to add your name to [CITATION.cff](https://github.com/nilearn/nilearn/blob/main/CITATION.cff) under authors in alphabetical order by first name.

**Comment by czarinasy** [comment]
Thanks for the tip @ymzayek! I've made the update now

**Review by Remi-Gau — APPROVED** [review]
LGTM

**Review by ymzayek — APPROVED** [review]

**Comment by Remi-Gau** [comment]
Rerunning the CI workflow that cancelled after 6 hours... 99.99999% sure it is unrelated to this but I just want to see how flaky this failure is.

**Comment by Remi-Gau** [comment]
all green now

merging

thanks @czarinasy

**Pull request merged**
