### PR TITLE
[MRG]: fixing cast/type issue in high_variance confounds #896

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
A fix to cast/type issue in high_variance confounds #896

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
This is now an MRG

**Comment by AlexandreAbraham** [comment]
+1

**Comment by lesteve** [comment]
The AppVeyor tests seem like a genuine error to me:

```
======================================================================
FAIL: Test custom detrend implementation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3-x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda3-x64\lib\site-packages\nilearn\tests\test_signal.py", line 222, in test_detrend
    < 15. * np.finfo(np.float).eps)
AssertionError: False is not true
 ```

**Comment by AlexandreAbraham** [comment]
Yes, sorry, I am now used to failing appveyor with no reason...

**Comment by GaelVaroquaux** [comment]
I fixed the AppVeyoer problem.

**Comment by bthirion** [comment]
LGTM.

**Pull request merged**
