### PR TITLE
[IGNORE] Testing auto-comment failure

### PR DESCRIPTION
**Pull request by thomasbazeille**
Closes # .

Changes proposed in this pull request:

-
-

### CODE REVIEW

**Comment by thomasbazeille** [comment]
@NicolasGensollen my PRs seem to work with auto-comment, could you try to open one yourself to see if it works as well or if its a config pb ?

I'll close this one afterwards

**Comment by NicolasGensollen** [comment]
@thomasbazeille it looks like it doesn't work because the action doesn't have write permissions on the upstream repo, only on forks (see this [link](https://github.community/t/github-actions-are-severely-limited-on-prs/18179) for example).
I'm not sure to understand why it is working for your PR though... :thinking: 

A way around might be to rely on something like [this](https://github.com/behaviorbot/welcome) where you give the bot the necessary rights to comment on issues/PRs.
WDYT?

**Comment by thomasbazeille** [comment]
When comparing the auto-comment run on the two PRs it turns out it has write autorization on my PR and only read on yours (cf below). Question is, how to give it write permissions on any PR


Capture d’écran 2021-09-23 à 11 55 13

Capture d’écran 2021-09-23 à 11 55 23

**Comment by thomasbazeille** [comment]
Thanks @NicolasGensollen. I think I fixed the problem in #2984 following : https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions

Could you merge it if you think it is ok and try open a new PR for testing ? 

Thanks again, closing this one!

**Pull request closed without merging**
