### PR TITLE
Release `0.9.0`

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Release 0.9.0.

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
Looks great !

**Comment by bthirion** [comment]
What is still missing for release ? #2829 ?

**Comment by NicolasGensollen** [comment]
@bthirion Yes, we're still missing #2829 and we should be good to go.

**Comment by NicolasGensollen** [comment]
I think this is ready

**Review by bthirion — APPROVED** [review]
LGTM. We can proceed !

**Comment by NicolasGensollen** [comment]
Alright! Thanks! Merging....

**Pull request merged**
