### PR TITLE
Fixing some py3 issues in Space-Net

### PR DESCRIPTION
**Pull request by dohmatob**
Fixes issue #998.

### CODE REVIEW

**Comment by bthirion** [comment]
LGTM

**Comment by aabadie** [comment]
LGTM +1

**Comment by aabadie** [comment]
Merging thanks !

**Comment by AlexandreAbraham** [comment]
For me, this is not a good fix. I think that we should return unicode strings and not rely on byte strings otherwise people will get in trouble when trying to select conditions.

**Comment by GaelVaroquaux** [comment]
I was wondering whether it was not possible / more elegant to solve this issue by loading bytes with a:

```
labels = np.recfromcsv(data_files.session_target[0], delimiter=" ", dtype='str,f8')
```

**Comment by GaelVaroquaux** [comment]
> For me, this is not a good fix. I think that we should return unicode strings
> and not rely on byte strings otherwise people will get in trouble when trying
> to select conditions.

It would probably be indeed preferable.

**Comment by aabadie** [comment]
@GaelVaroquaux, I tried your proposition, using  `dtype='str,f8'` but it doesn't make it : it returns empty labels.

**Comment by AlexandreAbraham** [comment]
What Gael said was an indication. The right way to specify it is:
`np.recfromcsv(data_files.session_target[0], delimiter=" ", dtype=[('labels', 'U12'), ('chunks', 'i8')])`

**Pull request merged**
