### PR TITLE
[MAINT] add missing __init__.py in tests folders

### PR DESCRIPTION
**Pull request by Remi-Gau**
Relates to #3660

Changes proposed in this pull request:

- add missing __init__.py in tests and tests/data folders

### CODE REVIEW

**Comment by ymzayek** [comment]
@Remi-Gau any idea about the failures here? I think we should get this PR in before the release next week

**Comment by Remi-Gau** [comment]
actually in this case adding `nilearn/_utils/tests/__init__.py` causes the tests to fail

```
FAILED nilearn/_utils/tests/test_cache_mixin.py::test_cache_memory_level - AssertionError: assert 0 == 1
FAILED nilearn/_utils/tests/test_cache_mixin.py::test_cache_shelving - AssertionError: assert 0 == 1
```

**Comment by Remi-Gau** [comment]
fixed locally: let's see what CI says.

**Review by ymzayek — APPROVED** [review]
Thanks @Remi-Gau!

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Pull request merged**
