### PR TITLE
[Fix] Fix test decoder

### LINKED ISSUE #3251: Test `test_decoder_dummy_classifier` is failing
The test `nilearn/decoding/tests/test_decoder.py::test_decoder_dummy_classifier` is failing in #3248, #3249, and #3250, even though at least one of those PRs doesn't change any dependencies or relevant code.

Nilearn version: 0.9.2dev at [a547961](https://github.com/nilearn/nilearn/commit/a547961179ef2ce974cc2078e77574fd63f76fe4).

### Expected behavior

The test would pass.

### Actual behavior

It seems to fail on a subset of the CI jobs.

### Steps and code to reproduce bug

I'm having trouble reproducing the bug locally, but hypothetically one could do the following:

```bash
pytest test_decoder.py -k test_decoder_dummy_classifier
```

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Closes #3251

### CODE REVIEW

**Review by ymzayek — APPROVED** [review]
It passes now, thx!

**Review by tsalo — APPROVED** [review]
Thanks for fixing this!

**Review by bthirion — APPROVED** [review]
It's doing the job, thx.

**Comment by bthirion** [comment]
Merging.

**Pull request merged**
