### PR TITLE
[NOMRG] Fix link in docs for circle

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Integrating the fix by @larsoner

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
@larsoner : circle failed, and looking at the failure, it seems related.

**Comment by GaelVaroquaux** [comment]
I am closing this one. I don't think that it should be merged.

**Comment by larsoner** [comment]
I have no idea why it worked locally but not remotely. It looks like in the `make html-strict` builds the image for that example isn't produced for some reason.

**Comment by larsoner** [comment]
(To clarify, locally it worked when building and changing the pattern regex to run that one example, I didn't try re-running the full `make html-strict` build because it takes a very long time. Presumably it wouldn't work locally either.)

**Pull request closed without merging**
