### PR TITLE
[MAINT] use pytest-reporter-html1 to create test reports

### LINKED ISSUE #4451: [TEST] Extract useful metrics from test suite's output
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

The idea is to get some nice visualization of the test suite's outputs, for example, the number of warnings thrown.

See #4444 for more details and some tools that can do this.

### Benefits to the change

This is to make the developers' as well as users' lives easier in terms of sifting through the output from the test suite.

### Pseudocode for the new behavior, if applicable

```python
# insert your code below

```

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes #4451

Changes proposed in this pull request:

- add html report to testing suite

Merged #4444 prematurely so reverted it and opening this one that reimplements it so we can get other dev opinions on it.

### CODE REVIEW

**Review by bthirion — APPROVED** [review]
LGTM so far

**Comment by emdupre** [comment]
Thx @Remi-Gau !

I can't quickly find it (sorry !) : could you link the generated html report ?

**Comment by Remi-Gau** [comment]
> I can't quickly find it (sorry !) : could you link the generated html report ?

it should show up on any run of the tests workflow:

https://github.com/nilearn/nilearn/actions/runs/9887014375/job/27307868492?pr=4486#step:7:27

just need to download and unzip the report (still a bit of friction that we can improve on later if needed)

**Comment by Remi-Gau** [comment]
Note that all the reports artefacts are also downloadable from the summary page of that run:

https://github.com/nilearn/nilearn/actions/runs/9887014375?pr=4486

**Comment by emdupre** [comment]
Thanks !! Just flagging that a number of tests show this in the report in place of a test description :

Screenshot 2024-08-02 at 17 53 34

Don't have time right now to look at why (sorry !) but I wanted to raise in case it's a quick fix. Otherwise, I don't think it's hindering the actual reporting functionality.

**Comment by bthirion** [comment]
Indeed, would be good to fix this before merging.

**Comment by Remi-Gau** [comment]
> Just flagging that a number of tests show this in the report in place of a test description

good catch

let me have a look

**Comment by Remi-Gau** [comment]
seems that the report is also printing things for some non-test related things that pytest list calls and also includes in its output (not sure why)


```
================================================================== slowest durations ==================================================================
9.91s call     nilearn/image/tests/test_resampling.py::test_resample_img_segmentation_fault[True]
9.01s call     nilearn/image/tests/test_resampling.py::test_resample_img_segmentation_fault[False]
0.56s call     nilearn/image/tests/test_image.py::test_threshold_img
0.53s call     nilearn/image/tests/test_image.py::test_clean_img
0.22s call     nilearn/image/tests/test_image.py::test_validity_threshold_value_in_threshold_img
0.22s call     nilearn/image/tests/test_image.py::test_mean_img[images_to_mean2]
0.22s call     nilearn/image/tests/test_image.py::test_math_img_exceptions
0.22s call     nilearn/image/tests/test_image.py::test_mean_img[images_to_mean3]
0.20s call     nilearn/image/image.py::nilearn.image.image.math_img  <--- SEE HERE
0.19s call     nilearn/image/image.py::nilearn.image.image.binarize_img  <--- SEE HERE
```

**Comment by Remi-Gau** [comment]
> (not sure why)

ok those are doc tests, makes sense

**Comment by Remi-Gau** [comment]
Opened an issue in the upstream repo: https://github.com/christiansandberg/pytest-reporter-html1/issues/27

**Comment by Remi-Gau** [comment]
> a number of tests show this in the report in place of a test description :

@emdupre
now fixed:

image

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Review by man-shu — APPROVED** [review]
LGTM too!

**Pull request merged**
