### PR TITLE
BUG: fix min value in nifti header

### LINKED ISSUE #1310: Wrong value for Nifti header
https://github.com/nilearn/nilearn/blob/9ee1c8d3b5d26937629cc62ce04cf8d4eb18a028/nilearn/image/image.py#L631

This should be `cal_min`
`header['cal_max'] = np.min(data) if data.size > 0 else 0.`

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Fixes #1310

### CODE REVIEW

**Comment by AlexandreAbraham** [comment]
+1, but I would have fixed it tonight ;).

**Comment by GaelVaroquaux** [comment]
I guess that I needed a recreation

**Comment by KamalakerDadi** [comment]
Failure of circleCI seems to happen quite often, though it is fixed in master. I don't know why ?

**Comment by GaelVaroquaux** [comment]
Is this good to merge?

**Pull request merged**
