### PR TITLE
Fix whatsnew sphinx unindent warning introduced by 3227

### PR DESCRIPTION
**Pull request by jeromedockes**

### CODE REVIEW

**Comment by jeromedockes** [comment]
not sure why there wasn't an error in the circleci build of the #3227 PR: https://app.circleci.com/pipelines/github/nilearn/nilearn/4351/workflows/024789f9-50e3-4766-9edc-ebf2ce5746ca/jobs/9674/steps

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Review by emdupre — APPROVED** [review]

**Comment by emdupre** [comment]
> not sure why there wasn't an error in the circleci build of the https://github.com/nilearn/nilearn/pull/3227 PR

I'm not sure either -- can look into it if you think it's important to identify. This fix looks right to me, though, thanks !

**Comment by jeromedockes** [comment]
thanks for the reviews!

**Pull request merged**
