### PR TITLE
Update Craddock 2000 url

### PR DESCRIPTION
**Pull request by vascosa**
Closes # .

Changes proposed in this pull request:

-
-

### CODE REVIEW

**Review by NicolasGensollen — COMMENTED** [review]
Thanks for fixing this @vascosa ! 👍 
Could you add an entry in `doc/changes/latest.rst` in the `FIX`section. Since this is your first contribution to Nilearn, you'll also need to add your name and link to your profile to `doc/changes/names.rst`.

**Comment by ymzayek** [comment]
Thanks @vascosa for this fix! Are you able to make the additions requested by @NicolasGensollen in the comment above so we can merge it? Otherwise, we can also take it over and finish it.

**Comment by vascosa** [comment]
Thanks for the reminder. Just made the additions.

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Review by ymzayek — APPROVED** [review]
I think this is good to go now!

**Review by NicolasGensollen — APPROVED** [review]
Yes, I also think this is ready to merge !

**Pull request merged**
