### PR TITLE
[FIX] fix typo and rendering in `first_level_from_bids`

### LINKED ISSUE #4342: [DOC] Error in docstring for `nilearn.glm.first_level.first_level_from_bids`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

The autodocs for [`nilearn.glm.first_level.first_level_from_bids`](https://nilearn.github.io/dev/modules/generated/nilearn.glm.first_level.first_level_from_bids.html) say to use kwargs prefixed with `confound_`, which will be passed to [`nilearn.interfaces.fmriprep.load_confounds`](https://nilearn.github.io/dev/modules/generated/nilearn.interfaces.fmriprep.load_confounds.html), but that is incorrect as it should be `confounds_` (plural). Also:
1. No error is raised if the wrong prefix is used (and it is unclear what happens to kwargs not starting with `confounds`)
2. The rendering of some parts of the docstring does not look good (see screenshot below)

Screenshot 2024-03-26 at 2 48 36 PM

### List any pages that would be impacted.

https://nilearn.github.io/dev/modules/generated/nilearn.interfaces.fmriprep.load_confounds.html

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes #4342

### CODE REVIEW

**Comment by Remi-Gau** [comment]
relevant section

image

**Review by bthirion — APPROVED** [review]
LGTM, thx !

**Comment by man-shu** [comment]
Good for me as well :)

**Comment by Remi-Gau** [comment]
Let's wait before merging as @michellewang has done some duplicate work for this in #4352: will try to merge the 2 PRs to get the best of each.

**Comment by Remi-Gau** [comment]
closing in favor of #4352

**Pull request closed without merging**
