### PR TITLE
[FIX] improve colorbar in mosaic display

### LINKED ISSUE #4283: [BUG] Colorbar is unreadable with plot_stat_map in mosaic mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [X] Mac
- [ ] Windows

### Operating system version

- Mac OS Version 14.2.1 "Sonoma"

### Python version

- [ ] 3.12
- [ ] 3.11
- [ ] 3.10
- [X] 3.9
- [ ] 3.8

### nilearn version

0.10.3

### Expected behavior

I would expect the colorbar to be thick enough to interpret, with labels large enough to read.

### Current behavior & error messages

No error message, but here is an example figure:
image

### Steps and code to reproduce bug

```python
from nilearn import datasets, plotting

stat_img = datasets.load_sample_motor_activation_image()
display = plotting.plot_stat_map(stat_img, display_mode="mosaic", annotate=False, output_file="test.png")
```

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes #4283 

Changes proposed in this pull request:

- increase width of colorbar in mosaic display
-

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Too big I guess.
Also the font size needs to be adapted.

test

**Comment by Remi-Gau** [comment]
with different number of cuts

test_1
test_7
test_14

**Review by tsalo — COMMENTED** [review]
It looks awesome, thank you! Any chance you could modify the labels as well?

**Comment by Remi-Gau** [comment]
will do 
juggling with a bunch of bug fixes and also trying to deal with admonition in the bids spec and there is only 24 hours in one day... sigh...

**Comment by tsalo** [comment]
There's definitely no rush on my part. Tedana will bump its nilearn requirement only once 0.10.4 is released, which will probably be a couple of months from now.

**Comment by Remi-Gau** [comment]
probably sooner than this actually

we want to have a quick new release that will just be bug fixes

**Comment by tsalo** [comment]
Ah, in that case, maybe something like the following at line 566?

```diff
-        for tick in self._colorbar_ax.yaxis.get_ticklabels():
-            tick.set_color(tick_color)
-        self._colorbar_ax.yaxis.set_tick_params(width=0)
+        self._colorbar_ax.yaxis.set_tick_params(
+            width=0,
+            color=tick_color,
+            labelsize=self._colorbar_width * 100,
+        )
```

**Comment by bthirion** [comment]
Just wondering: isn't it ultimately simpler to reduce the figsize in order to have all labels not dwarfed by the plot size ?

**Comment by Remi-Gau** [comment]
> Just wondering: isn't it ultimately simpler to reduce the figsize in order to have all labels not dwarfed by the plot size ?

thanks for the hint @bthirion, changing the default figure size seems easier.

will copy paste a few examples to let you judge

**Comment by Remi-Gau** [comment]
The default figure size is now much more in the range of that of the other displays.

**Comment by tsalo** [comment]
Wow, changing the figure size worked wonders!

**Review by bthirion — APPROVED** [review]
LGTM, thx.

**Pull request merged**
