### PR TITLE
[MRG] BUG: fix non-imported VisibleDeprecationWarning

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Necessary to fix CI: https://travis-ci.org/nilearn/nilearn/jobs/655871459?utm_medium=notification&utm_source=github_status

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
It seems that our backport of VisibleDepractionWarning is no longer needed for the versions of nilearn that we support. I will remove it (@kchawla-pi : maybe nistats will need to adapt).

**Comment by kchawla-pi** [comment]
Never really got the need for it. FutureWarning does a fine job.

**Comment by GaelVaroquaux** [comment]
That PR fixes CI (as visible from the test results above). It's ready for merge.

**Comment by kchawla-pi** [comment]
LGTM.

**Pull request merged**
