### PR TITLE
[MRG+1] Fix vmin and vmax problem in plot_probabilistic_atlas file without test

### PR DESCRIPTION
**Pull request by KamalakerDadi**

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Hey Kamalakar,

Thanks! Could you include a screen shot of the example with the changes.

Cheers

**Comment by KamalakerDadi** [comment]
Example changes:
```python
# Now add as an overlay the maps for the ACC and the left and right
# parietal nodes
display.add_overlay(image.index_img(atlas_filename, 5),
                    cmap=plotting.cm.black_blue)
display.add_overlay(image.index_img(atlas_filename, 6),
                    cmap=plotting.cm.black_green)
display.add_overlay(image.index_img(atlas_filename, 3),
                    cmap=plotting.cm.black_pink)

plt.show()
```
Basically removed vmin and vmax arguments.

For this, changed add_overlay codebase in displays.py
```python
if 'vmin' not in kwargs:
            kwargs['vmin'] = np.ma.min([d.min() for d in data_2d_list
                                                         if d is not None])
        if 'vmax' not in kwargs:
            kwargs['vmax'] = np.ma.max([d.max() for d in data_2d_list
                                                          if d is not None])
```

figure_1

**Comment by KamalakerDadi** [comment]
@GaelVaroquaux Is that what you mean ?

**Comment by GaelVaroquaux** [comment]
Yes, this is what I meant.

This works well. :+1: for merge. Thanks!

**Pull request merged**
